// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/DecoAnalyticsScript.ts";
import * as $$$$$$0 from "./sections/Analytics/DecoAnalytics.tsx";

const manifest = {
  "loaders": {
    "analytics/loaders/DecoAnalyticsScript.ts": $$$0,
  },
  "sections": {
    "analytics/sections/Analytics/DecoAnalytics.tsx": $$$$$$0,
  },
  "name": "analytics",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
