// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Analytics/Jitsu.tsx";
import * as $$$$$$1 from "./sections/Analytics/Plausible.tsx";

const manifest = {
  "sections": {
    "analytics/sections/Analytics/Jitsu.tsx": $$$$$$0,
    "analytics/sections/Analytics/Plausible.tsx": $$$$$$1,
  },
  "name": "analytics",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
