// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/read.ts";
import * as $$$1 from "./loaders/search.ts";

const manifest = {
  "loaders": {
    "sheet-db-nps/loaders/read.ts": $$$0,
    "sheet-db-nps/loaders/search.ts": $$$1,
  },
  "name": "sheet-db-nps",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
