// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/askPerplexity.ts";
import * as $$$1 from "./loaders/chat.ts";

const manifest = {
  "loaders": {
    "perplexity/loaders/askPerplexity.ts": $$$0,
    "perplexity/loaders/chat.ts": $$$1,
  },
  "name": "perplexity",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
