// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/auction/addBid.ts";
import * as $$$$$$$$$1 from "./actions/cart/addCoupon.ts";
import * as $$$$$$$$$2 from "./actions/cart/addItem.ts";
import * as $$$$$$$$$3 from "./actions/cart/updateItem.ts";
import * as $$$$$$$$$4 from "./actions/login.ts";
import * as $$$$$$$$$5 from "./actions/newsletter/subscribe.ts";
import * as $$$$0 from "./handlers/sitemap.ts";
import * as $$$1 from "./loaders/auction/detailsPage.ts";
import * as $$$2 from "./loaders/auction/list.ts";
import * as $$$0 from "./loaders/auction/ListBids.ts";
import * as $$$3 from "./loaders/cart.ts";
import * as $$$4 from "./loaders/page.ts";
import * as $$$5 from "./loaders/pages.ts";
import * as $$$6 from "./loaders/path.ts";
import * as $$$7 from "./loaders/product/detailsPage.ts";
import * as $$$8 from "./loaders/product/list.ts";
import * as $$$9 from "./loaders/product/listingPage.ts";
import * as $$$10 from "./loaders/product/suggestions.ts";
import * as $$$11 from "./loaders/proxy.ts";
import * as $$$12 from "./loaders/user.ts";

const manifest = {
  "loaders": {
    "linx/loaders/auction/detailsPage.ts": $$$1,
    "linx/loaders/auction/list.ts": $$$2,
    "linx/loaders/auction/ListBids.ts": $$$0,
    "linx/loaders/cart.ts": $$$3,
    "linx/loaders/page.ts": $$$4,
    "linx/loaders/pages.ts": $$$5,
    "linx/loaders/path.ts": $$$6,
    "linx/loaders/product/detailsPage.ts": $$$7,
    "linx/loaders/product/list.ts": $$$8,
    "linx/loaders/product/listingPage.ts": $$$9,
    "linx/loaders/product/suggestions.ts": $$$10,
    "linx/loaders/proxy.ts": $$$11,
    "linx/loaders/user.ts": $$$12,
  },
  "handlers": {
    "linx/handlers/sitemap.ts": $$$$0,
  },
  "actions": {
    "linx/actions/auction/addBid.ts": $$$$$$$$$0,
    "linx/actions/cart/addCoupon.ts": $$$$$$$$$1,
    "linx/actions/cart/addItem.ts": $$$$$$$$$2,
    "linx/actions/cart/updateItem.ts": $$$$$$$$$3,
    "linx/actions/login.ts": $$$$$$$$$4,
    "linx/actions/newsletter/subscribe.ts": $$$$$$$$$5,
  },
  "name": "linx",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
