// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/deployments/create.ts";
import * as $$$$$$$$$1 from "./actions/projects/create.ts";

const manifest = {
  "actions": {
    "deno-subhosting/actions/deployments/create.ts": $$$$$$$$$0,
    "deno-subhosting/actions/projects/create.ts": $$$$$$$$$1,
  },
  "name": "deno-subhosting",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
