// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/cancel-order.ts";
import * as $$$$$$$$$1 from "./actions/create-shipping.ts";
import * as $$$$$$$$$2 from "./actions/generate-label.ts";
import * as $$$$$$$$$3 from "./actions/print-label.ts";
import * as $$$0 from "./loaders/addresses.ts";
import * as $$$1 from "./loaders/freight-quote.ts";
import * as $$$2 from "./loaders/order-info.ts";
import * as $$$3 from "./loaders/services-info.ts";
import * as $$$4 from "./loaders/user-info.ts";

const manifest = {
  "loaders": {
    "superfrete/loaders/addresses.ts": $$$0,
    "superfrete/loaders/freight-quote.ts": $$$1,
    "superfrete/loaders/order-info.ts": $$$2,
    "superfrete/loaders/services-info.ts": $$$3,
    "superfrete/loaders/user-info.ts": $$$4,
  },
  "actions": {
    "superfrete/actions/cancel-order.ts": $$$$$$$$$0,
    "superfrete/actions/create-shipping.ts": $$$$$$$$$1,
    "superfrete/actions/generate-label.ts": $$$$$$$$$2,
    "superfrete/actions/print-label.ts": $$$$$$$$$3,
  },
  "name": "superfrete",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
