// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

const manifest = {
  "loaders": {
    "pncp/loaders/buscarDocumentos.ts": () => import("./loaders/buscarDocumentos.ts"),
    "pncp/loaders/obterDocumento.ts": () => import("./loaders/obterDocumento.ts"),
    "pncp/loaders/listarOrgaos.ts": () => import("./loaders/listarOrgaos.ts"),
    "pncp/loaders/obterOrgao.ts": () => import("./loaders/obterOrgao.ts"),
    "pncp/loaders/obterEstatisticas.ts": () => import("./loaders/obterEstatisticas.ts"),
  },
  "actions": {
    "pncp/actions/notificarLicitacao.ts": () => import("./actions/notificarLicitacao.ts"),
  },
  "name": "pncp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;