// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/categories/tree.ts";
import * as $$$2 from "./loaders/product/productDetailsPage.ts";
import * as $$$1 from "./loaders/product/ProductList.ts";
import * as $$$3 from "./loaders/product/productListingPage.ts";

const manifest = {
  "loaders": {
    "sap/loaders/categories/tree.ts": $$$0,
    "sap/loaders/product/productDetailsPage.ts": $$$2,
    "sap/loaders/product/ProductList.ts": $$$1,
    "sap/loaders/product/productListingPage.ts": $$$3,
  },
  "name": "sap",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
