// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/hooks/create.ts";
import * as $$$$$$$$$1 from "./actions/hooks/delete.ts";
import * as $$$0 from "./loaders/hooks/list.ts";
import * as $$$1 from "./loaders/me.ts";
import * as $$$2 from "./loaders/recordings/get.ts";
import * as $$$3 from "./loaders/recordings/list.ts";
import * as $$$4 from "./loaders/recordings/transcriptSrt.ts";
import * as $$$5 from "./loaders/recordings/transcriptVtt.ts";
import * as $$$6 from "./loaders/views/list.ts";

const manifest = {
  "loaders": {
    "grain/loaders/hooks/list.ts": $$$0,
    "grain/loaders/me.ts": $$$1,
    "grain/loaders/recordings/get.ts": $$$2,
    "grain/loaders/recordings/list.ts": $$$3,
    "grain/loaders/recordings/transcriptSrt.ts": $$$4,
    "grain/loaders/recordings/transcriptVtt.ts": $$$5,
    "grain/loaders/views/list.ts": $$$6,
  },
  "actions": {
    "grain/actions/hooks/create.ts": $$$$$$$$$0,
    "grain/actions/hooks/delete.ts": $$$$$$$$$1,
  },
  "name": "grain",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
