// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createFraudScore.ts";
import * as $$$$$$$$$1 from "./actions/createTransaction.ts";
import * as $$$0 from "./loaders/getFraudScore.ts";
import * as $$$1 from "./loaders/getTransaction.ts";

const manifest = {
  "loaders": {
    "clearsale/loaders/getFraudScore.ts": $$$0,
    "clearsale/loaders/getTransaction.ts": $$$1,
  },
  "actions": {
    "clearsale/actions/createFraudScore.ts": $$$$$$$$$0,
    "clearsale/actions/createTransaction.ts": $$$$$$$$$1,
  },
  "name": "clearsale",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
