// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

const manifest = {
  "name": "deco-sites/std",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
