// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/product/productDetailsPage.ts";
import * as $$$1 from "./loaders/proxy.ts";

const manifest = {
  "loaders": {
    "woocommerce/loaders/product/productDetailsPage.ts": $$$0,
    "woocommerce/loaders/proxy.ts": $$$1,
  },
  "name": "woocommerce",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
