// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sendMessage.ts";

const manifest = {
  "actions": {
    "discohook/actions/sendMessage.ts": $$$$$$$$$0,
  },
  "name": "discohook",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
