// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/transcribeAudio.ts";

const manifest = {
  "loaders": {
    "vertex-mcp/loaders/transcribeAudio.ts": $$$0,
  },
  "name": "vertex-mcp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;