// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sendMessage.ts";
import * as $$$$$$$$$1 from "./actions/addReaction.ts";
import * as $$$$$$$$$2 from "./actions/banMember.ts";
import * as $$$$$$$$$3 from "./actions/createChannel.ts";
import * as $$$$$$$$$4 from "./actions/deleteMessage.ts";
import * as $$$$$$$$$5 from "./actions/editMessage.ts";
import * as $$$$$$$$$6 from "./actions/pinMessage.ts";
import * as $$$$$$$$$7 from "./actions/unpinMessage.ts";
import * as $$$$$$$$$8 from "./actions/removeReaction.ts";
import * as $$$$$$$$$9 from "./actions/createThread.ts";
import * as $$$$$$$$$10 from "./actions/joinThread.ts";
import * as $$$$$$$$$11 from "./actions/leaveThread.ts";
import * as $$$$$$$$$12 from "./actions/createRole.ts";
import * as $$$$$$$$$13 from "./actions/editRole.ts";
import * as $$$$$$$$$14 from "./actions/deleteRole.ts";
import * as $$$$$$$$$15 from "./actions/createWebhook.ts";
import * as $$$$$$$$$16 from "./actions/executeWebhook.ts";
import * as $$$$$$$$$17 from "./actions/deleteWebhook.ts";
import * as $$$0 from "./loaders/getChannelMessages.ts";
import * as $$$1 from "./loaders/getGuildChannels.ts";
import * as $$$2 from "./loaders/getGuild.ts";
import * as $$$3 from "./loaders/getGuildMembers.ts";
import * as $$$4 from "./loaders/listBotGuilds.ts";
import * as $$$5 from "./loaders/getMessage.ts";
import * as $$$6 from "./loaders/getMessageReactions.ts";
import * as $$$7 from "./loaders/getPinnedMessages.ts";
import * as $$$8 from "./loaders/getActiveThreads.ts";
import * as $$$9 from "./loaders/getArchivedThreads.ts";
import * as $$$10 from "./loaders/getGuildRoles.ts";
import * as $$$11 from "./loaders/getCurrentUser.ts";
import * as $$$12 from "./loaders/getUser.ts";
import * as $$$13 from "./loaders/listWebhooks.ts";

const manifest = {
  "loaders": {
    "discord-bot/loaders/getChannelMessages.ts": $$$0,
    "discord-bot/loaders/getGuildChannels.ts": $$$1,
    "discord-bot/loaders/getGuild.ts": $$$2,
    "discord-bot/loaders/getGuildMembers.ts": $$$3,
    "discord-bot/loaders/listBotGuilds.ts": $$$4,
    "discord-bot/loaders/getMessage.ts": $$$5,
    "discord-bot/loaders/getMessageReactions.ts": $$$6,
    "discord-bot/loaders/getPinnedMessages.ts": $$$7,
    "discord-bot/loaders/getActiveThreads.ts": $$$8,
    "discord-bot/loaders/getArchivedThreads.ts": $$$9,
    "discord-bot/loaders/getGuildRoles.ts": $$$10,
    "discord-bot/loaders/getCurrentUser.ts": $$$11,
    "discord-bot/loaders/getUser.ts": $$$12,
    "discord-bot/loaders/listWebhooks.ts": $$$13,
  },
  "actions": {
    "discord-bot/actions/sendMessage.ts": $$$$$$$$$0,
    "discord-bot/actions/addReaction.ts": $$$$$$$$$1,
    "discord-bot/actions/banMember.ts": $$$$$$$$$2,
    "discord-bot/actions/createChannel.ts": $$$$$$$$$3,
    "discord-bot/actions/deleteMessage.ts": $$$$$$$$$4,
    "discord-bot/actions/editMessage.ts": $$$$$$$$$5,
    "discord-bot/actions/pinMessage.ts": $$$$$$$$$6,
    "discord-bot/actions/unpinMessage.ts": $$$$$$$$$7,
    "discord-bot/actions/removeReaction.ts": $$$$$$$$$8,
    "discord-bot/actions/createThread.ts": $$$$$$$$$9,
    "discord-bot/actions/joinThread.ts": $$$$$$$$$10,
    "discord-bot/actions/leaveThread.ts": $$$$$$$$$11,
    "discord-bot/actions/createRole.ts": $$$$$$$$$12,
    "discord-bot/actions/editRole.ts": $$$$$$$$$13,
    "discord-bot/actions/deleteRole.ts": $$$$$$$$$14,
    "discord-bot/actions/createWebhook.ts": $$$$$$$$$15,
    "discord-bot/actions/executeWebhook.ts": $$$$$$$$$16,
    "discord-bot/actions/deleteWebhook.ts": $$$$$$$$$17,
  },
  "name": "discord-bot",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;