// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/prompt/run.ts";
import * as $$$0 from "./loaders/getSavedPrompts.ts";
import * as $$$1 from "./loaders/listAvailablePrompts.ts";

const manifest = {
  "loaders": {
    "decopilot-app/loaders/getSavedPrompts.ts": $$$0,
    "decopilot-app/loaders/listAvailablePrompts.ts": $$$1,
  },
  "actions": {
    "decopilot-app/actions/prompt/run.ts": $$$$$$$$$0,
  },
  "name": "decopilot-app",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
