import { Offer, Product } from "../../../commerce/types.ts";
import { MagentoProduct } from "../../utils/client/types.ts";

export const productFromMagento: MagentoProduct = {
  id: 5891,
  sku: "7896512970268",
  name: "Kit Lata Sabonetes em Barra Rosmarino",
  url: "string",
  price: 82,
  status: 1,
  visibility: 4,
  type_id: "simple",
  created_at: "2024-03-14 20:58:25",
  updated_at: "2024-04-26 21:30:02",
  weight: 0.3,
  extension_attributes: {
    website_ids: [1],
    category_links: [
      { position: -9, category_id: "861" },
      { position: -4, category_id: "876" },
      { position: -17, category_id: "897" },
      { position: -11, category_id: "915" },
      { position: -3, category_id: "1885" },
      { position: -18, category_id: "924" },
      { position: 7, category_id: "3992" },
      { position: 3, category_id: "1289" },
      { position: 7, category_id: "4049" },
      { position: 23, category_id: "2082" },
      { position: 2, category_id: "4060" },
      { position: 1, category_id: "2343" },
      { position: 5, category_id: "2969" },
    ],
  },
  custom_attributes: [
    { attribute_code: "volume_length", value: "16" },
    {
      attribute_code: "url_key",
      value: "kit-lata-sabonetes-em-barra-rosmarino",
    },
    { attribute_code: "gift_message_available", value: "2" },
    { attribute_code: "fragrancias", value: "287" },
    { attribute_code: "image", value: "/e/a/ean7896512970268_09.jpg" },
    { attribute_code: "marca", value: "639" },
    { attribute_code: "page_layout", value: "1column" },
    { attribute_code: "gift_wrapping_available", value: "2" },
    { attribute_code: "volume_height", value: "2" },
    { attribute_code: "options_container", value: "container2" },
    {
      attribute_code: "meta_title",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    {
      attribute_code: "small_image",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      attribute_code: "thumbnail",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      attribute_code: "meta_keyword",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    { attribute_code: "volume_width", value: "11" },
    {
      attribute_code: "description",
      value: "string",
    },
    {
      attribute_code: "swatch_image",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      attribute_code: "meta_description",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    { attribute_code: "lead_time", value: "0" },
    { attribute_code: "fragile", value: "0" },
    { attribute_code: "linha", value: "554" },
    { attribute_code: "msrp_display_actual_price_type", value: "0" },
    { attribute_code: "free_shipping__phebo", value: "0" },
    {
      attribute_code: "como_usar__phebo",
      value: "string",
    },
    { attribute_code: "wesupply_estimation_display", value: "1" },
    { attribute_code: "tag__phebo", value: "Novidade" },
    { attribute_code: "tax_class_id", value: "2" },
    { attribute_code: "required_options", value: "0" },
    { attribute_code: "has_options", value: "0" },
    {
      attribute_code: "category_ids",
      value: [
        "861",
        "876",
        "897",
        "915",
        "1885",
        "924",
        "3992",
        "1289",
        "4049",
        "2082",
        "4060",
        "2343",
        "2969",
      ],
    },
    { attribute_code: "is_returnable", value: "2" },
    { attribute_code: "mst_search_weight", value: "0" },
    { attribute_code: "review_count", value: "1" },
    { attribute_code: "best_seller", value: "70" },
    { attribute_code: "top_rated", value: "100" },
    { attribute_code: "most_viewed", value: "0" },
    {
      attribute_code: "hover_catalog",
      value: "/e/a/ean7896512970268_09.jpg",
    },
  ],
  price_info: {
    final_price: 149,
    max_price: 149,
    max_regular_price: 149,
    minimal_regular_price: 149,
    special_price: null,
    minimal_price: 149,
    regular_price: 149,
    formatted_prices: {
      final_price: '<span class="price">R$ 149,00</span>',
      max_price: '<span class="price">R$ 149,00</span>',
      minimal_price: '<span class="price">R$ 149,00</span>',
      max_regular_price: '<span class="price">R$ 149,00</span>',
      minimal_regular_price: null,
      special_price: null,
      regular_price: '<span class="price">R$ 149,00</span>',
    },
    extension_attributes: {
      msrp: {
        msrp_price: '<span class="price">R$ 0,00</span>',
        is_applicable: "",
        is_shown_price_on_gesture: "",
        msrp_message: "",
        explanation_message: "string",
      },
      tax_adjustments: {
        final_price: 149,
        max_price: 149,
        max_regular_price: 149,
        minimal_regular_price: 149,
        special_price: 149,
        minimal_price: 149,
        regular_price: 149,
        formatted_prices: {
          final_price: '<span class="price">R$ 149,00</span>',
          max_price: '<span class="price">R$ 149,00</span>',
          minimal_price: '<span class="price">R$ 149,00</span>',
          max_regular_price: '<span class="price">R$ 149,00</span>',
          minimal_regular_price: null,
          special_price: '<span class="price">R$ 149,00</span>',
          regular_price: '<span class="price">R$ 149,00</span>',
        },
      },
      weee_attributes: [],
      weee_adjustment: '<span class="price">R$ 149,00</span>',
    },
  },
  images: [
    {
      url: "string",
      code: "recently_viewed_products_grid_content_widget",
      height: 450,
      width: 350,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 350,
      resized_height: 450,
    },
    {
      url: "string",
      code: "recently_viewed_products_list_content_widget",
      height: 450,
      width: 350,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 350,
      resized_height: 450,
    },
    {
      url: "string",
      code: "recently_viewed_products_images_names_widget",
      height: 122,
      width: 95,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 95,
      resized_height: 122,
    },
    {
      url: "string",
      code: "recently_compared_products_grid_content_widget",
      height: 450,
      width: 350,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 350,
      resized_height: 450,
    },
    {
      url: "string",
      code: "recently_compared_products_list_content_widget",
      height: 450,
      width: 350,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 350,
      resized_height: 450,
    },
    {
      url: "string",
      code: "recently_compared_products_images_names_widget",
      height: 450,
      width: 350,
      label: "Eau de Toilette Suzette 100ml",
      resized_width: 350,
      resized_height: 450,
    },
  ],
  currency_code: "BRL",
};

export const expectedProduct: Product = {
  "@type": "Product",
  productID: "5891",
  sku: "7896512970268",
  url: "string",
  name: "Kit Lata Sabonetes em Barra Rosmarino",
  additionalProperty: [
    { "@type": "PropertyValue", name: "volume_length", value: "16" },
    {
      "@type": "PropertyValue",
      name: "url_key",
      value: "kit-lata-sabonetes-em-barra-rosmarino",
    },
    {
      "@type": "PropertyValue",
      name: "gift_message_available",
      value: "2",
    },
    { "@type": "PropertyValue", name: "fragrancias", value: "287" },
    {
      "@type": "PropertyValue",
      name: "image",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    { "@type": "PropertyValue", name: "marca", value: "639" },
    { "@type": "PropertyValue", name: "page_layout", value: "1column" },
    {
      "@type": "PropertyValue",
      name: "gift_wrapping_available",
      value: "2",
    },
    { "@type": "PropertyValue", name: "volume_height", value: "2" },
    {
      "@type": "PropertyValue",
      name: "options_container",
      value: "container2",
    },
    {
      "@type": "PropertyValue",
      name: "meta_title",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    {
      "@type": "PropertyValue",
      name: "small_image",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      "@type": "PropertyValue",
      name: "thumbnail",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      "@type": "PropertyValue",
      name: "meta_keyword",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    { "@type": "PropertyValue", name: "volume_width", value: "11" },
    {
      "@type": "PropertyValue",
      name: "description",
      value: "string",
    },
    {
      "@type": "PropertyValue",
      name: "swatch_image",
      value: "/e/a/ean7896512970268_09.jpg",
    },
    {
      "@type": "PropertyValue",
      name: "meta_description",
      value: "Kit Lata Sabonetes em Barra Rosmarino",
    },
    { "@type": "PropertyValue", name: "lead_time", value: "0" },
    { "@type": "PropertyValue", name: "fragile", value: "0" },
    { "@type": "PropertyValue", name: "linha", value: "554" },
    {
      "@type": "PropertyValue",
      name: "msrp_display_actual_price_type",
      value: "0",
    },
    {
      "@type": "PropertyValue",
      name: "free_shipping__phebo",
      value: "0",
    },
    {
      "@type": "PropertyValue",
      name: "como_usar__phebo",
      value: "string",
    },
    {
      "@type": "PropertyValue",
      name: "wesupply_estimation_display",
      value: "1",
    },
    { "@type": "PropertyValue", name: "tag__phebo", value: "Novidade" },
    { "@type": "PropertyValue", name: "tax_class_id", value: "2" },
    { "@type": "PropertyValue", name: "required_options", value: "0" },
    { "@type": "PropertyValue", name: "has_options", value: "0" },
    {
      "@type": "PropertyValue",
      name: "category_ids",
      value: "861,876,897,915,1885,924,3992,1289,4049,2082,4060,2343,2969",
    },
    { "@type": "PropertyValue", name: "is_returnable", value: "2" },
    { "@type": "PropertyValue", name: "mst_search_weight", value: "0" },
    { "@type": "PropertyValue", name: "review_count", value: "1" },
    { "@type": "PropertyValue", name: "best_seller", value: "70" },
    { "@type": "PropertyValue", name: "top_rated", value: "100" },
    { "@type": "PropertyValue", name: "most_viewed", value: "0" },
    {
      "@type": "PropertyValue",
      name: "hover_catalog",
      value: "/e/a/ean7896512970268_09.jpg",
    },
  ],
  image: [
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
    {
      "@type": "ImageObject",
      encodingFormat: "image",
      alternateName: "string",
      url: "string",
    },
  ],
  offers: {
    "@type": "AggregateOffer",
    highPrice: 149,
    lowPrice: 149,
    offerCount: 1,
    offers: [
      {
        "@type": "Offer",
        availability: "https://schema.org/OutOfStock",
        inventoryLevel: { value: 0 },
        itemCondition: "https://schema.org/NewCondition",
        price: 149,
        priceCurrency: "BRL",
        priceSpecification: [],
        sku: "7896512970268",
      },
    ],
  },
};

export const outOfStockOffer: Offer[] = [
  {
    "@type": "Offer",
    availability: "https://schema.org/OutOfStock",
    inventoryLevel: { value: 0 },
    itemCondition: "https://schema.org/NewCondition",
    price: 149,
    priceCurrency: "BRL",
    priceSpecification: [],
    sku: "7896512970268",
  },
];
