// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/getOrganization.ts";
import * as $$$1 from "./loaders/searchOrganizations.ts";

const manifest = {
  "loaders": {
    "affinity/loaders/getOrganization.ts": $$$0,
    "affinity/loaders/searchOrganizations.ts": $$$1,
  },
  "name": "affinity",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
