// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/mercadoSecundario.ts";

const manifest = {
  "loaders": {
    "anbima/loaders/mercadoSecundario.ts": $$$0,
  },
  "sections": {},
  "actions": {},
  "name": "anbima",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest; 