// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/docs/create.ts";
import * as $$$$$$$$$1 from "./actions/files/copy.ts";
import * as $$$$$$$$$2 from "./actions/files/create.ts";
import * as $$$$$$$$$3 from "./actions/files/delete.ts";
import * as $$$$$$$$$4 from "./actions/files/download.ts";
import * as $$$$$$$$$5 from "./actions/files/update.ts";
import * as $$$$$$$$$6 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$7 from "./actions/slides/create.ts";
import * as $$$0 from "./loaders/docs/get.ts";
import * as $$$1 from "./loaders/docs/list.ts";
import * as $$$2 from "./loaders/files/get.ts";
import * as $$$3 from "./loaders/files/list.ts";
import * as $$$4 from "./loaders/files/search.ts";
import * as $$$5 from "./loaders/oauth/start.ts";
import * as $$$6 from "./loaders/sheets/get.ts";
import * as $$$7 from "./loaders/sheets/list.ts";
import * as $$$8 from "./loaders/slides/get.ts";
import * as $$$9 from "./loaders/slides/list.ts";

const manifest = {
  "loaders": {
    "google-drive/loaders/docs/get.ts": $$$0,
    "google-drive/loaders/docs/list.ts": $$$1,
    "google-drive/loaders/files/get.ts": $$$2,
    "google-drive/loaders/files/list.ts": $$$3,
    "google-drive/loaders/files/search.ts": $$$4,
    "google-drive/loaders/oauth/start.ts": $$$5,
    "google-drive/loaders/sheets/get.ts": $$$6,
    "google-drive/loaders/sheets/list.ts": $$$7,
    "google-drive/loaders/slides/get.ts": $$$8,
    "google-drive/loaders/slides/list.ts": $$$9,
  },
  "actions": {
    "google-drive/actions/docs/create.ts": $$$$$$$$$0,
    "google-drive/actions/files/copy.ts": $$$$$$$$$1,
    "google-drive/actions/files/create.ts": $$$$$$$$$2,
    "google-drive/actions/files/delete.ts": $$$$$$$$$3,
    "google-drive/actions/files/download.ts": $$$$$$$$$4,
    "google-drive/actions/files/update.ts": $$$$$$$$$5,
    "google-drive/actions/oauth/callback.ts": $$$$$$$$$6,
    "google-drive/actions/slides/create.ts": $$$$$$$$$7,
  },
  "name": "google-drive",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
