// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/Cards.tsx";

const manifest = {
  "sections": {
    "cards/sections/Cards.tsx": $$$$$$0,
  },
  "name": "cards",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
