// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/TrustvoxProductReviews.tsx";
import * as $$$$$$1 from "./sections/TrustvoxRateConfig.tsx";
import * as $$$$$$2 from "./sections/TrustvoxStoreReviewsCarousel.tsx";

const manifest = {
  "sections": {
    "ra-trustvox/sections/TrustvoxProductReviews.tsx": $$$$$$0,
    "ra-trustvox/sections/TrustvoxRateConfig.tsx": $$$$$$1,
    "ra-trustvox/sections/TrustvoxStoreReviewsCarousel.tsx": $$$$$$2,
  },
  "name": "ra-trustvox",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
