// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/elements/addImage.ts";
import * as $$$$$$$$$1 from "./actions/elements/addTextBox.ts";
import * as $$$$$$$$$2 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$3 from "./actions/presentations/create.ts";
import * as $$$$$$$$$4 from "./actions/slides/create.ts";
import * as $$$$$$$$$5 from "./actions/text/replaceAllText.ts";
import * as $$$$$$$$$6 from "./actions/updateFromTemplateNames.ts";
import * as $$$$$$$$$7 from "./actions/updateSlideTemplates.ts";
import * as $$$0 from "./loaders/oauth/start.ts";
import * as $$$1 from "./loaders/presentation/get.ts";
import * as $$$2 from "./loaders/presentations/list.ts";

const manifest = {
  "loaders": {
    "google-slides/loaders/oauth/start.ts": $$$0,
    "google-slides/loaders/presentation/get.ts": $$$1,
    "google-slides/loaders/presentations/list.ts": $$$2,
  },
  "actions": {
    "google-slides/actions/elements/addImage.ts": $$$$$$$$$0,
    "google-slides/actions/elements/addTextBox.ts": $$$$$$$$$1,
    "google-slides/actions/oauth/callback.ts": $$$$$$$$$2,
    "google-slides/actions/presentations/create.ts": $$$$$$$$$3,
    "google-slides/actions/slides/create.ts": $$$$$$$$$4,
    "google-slides/actions/text/replaceAllText.ts": $$$$$$$$$5,
    "google-slides/actions/updateFromTemplateNames.ts": $$$$$$$$$6,
    "google-slides/actions/updateSlideTemplates.ts": $$$$$$$$$7,
  },
  "name": "google-slides",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
