// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$1 from "./actions/updateFromTemplateNames.ts";
import * as $$$$$$$$$2 from "./actions/updateSlideTemplates.ts";
import * as $$$0 from "./loaders/oauth/start.ts";
import * as $$$1 from "./loaders/presentation/get.ts";

const manifest = {
  "loaders": {
    "google-slides/loaders/oauth/start.ts": $$$0,
    "google-slides/loaders/presentation/get.ts": $$$1,
  },
  "actions": {
    "google-slides/actions/oauth/callback.ts": $$$$$$$$$0,
    "google-slides/actions/updateFromTemplateNames.ts": $$$$$$$$$1,
    "google-slides/actions/updateSlideTemplates.ts": $$$$$$$$$2,
  },
  "name": "google-slides",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
