// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/BlogPostItem.ts";
import * as $$$2 from "./loaders/BlogpostList.ts";
import * as $$$3 from "./loaders/BlogpostListing.ts";
import * as $$$1 from "./loaders/BlogPostPage.ts";
import * as $$$4 from "./loaders/BlogsByAuthor.ts";
import * as $$$5 from "./loaders/BlogsByTag.ts";
import * as $$$6 from "./loaders/GetAuthors.ts";
import * as $$$7 from "./loaders/GetTags.ts";
// Block sections: now sourced from blog app (single source of truth).
// Registered under spire/ keys for backward compatibility with existing sites.
import * as $$$$$$3 from "../blog/sections/blocks/BlockImage.tsx";
import * as $$$$$$4 from "../blog/sections/blocks/Callout.tsx";
import * as $$$$$$5 from "../blog/sections/blocks/CardGroup.tsx";
import * as $$$$$$6 from "../blog/sections/blocks/Checklist.tsx";
import * as $$$$$$7 from "../blog/sections/blocks/Code.tsx";
import * as $$$$$$8 from "../blog/sections/blocks/Comparison.tsx";
import * as $$$$$$9 from "../blog/sections/blocks/Cta.tsx";
import * as $$$$$$10 from "../blog/sections/blocks/Divider.tsx";
import * as $$$$$$11 from "../blog/sections/blocks/Heading.tsx";
import * as $$$$$$12 from "../blog/sections/blocks/List.tsx";
import * as $$$$$$13 from "../blog/sections/blocks/Paragraph.tsx";
import * as $$$$$$14 from "../blog/sections/blocks/Quote.tsx";
import * as $$$$$$15 from "../blog/sections/blocks/Stat.tsx";
import * as $$$$$$16 from "../blog/sections/blocks/StatGroup.tsx";
import * as $$$$$$17 from "../blog/sections/blocks/Steps.tsx";
import * as $$$$$$18 from "../blog/sections/blocks/Video.tsx";
import * as $$$$$$0 from "./sections/Seo/SeoBlogPost.tsx";
import * as $$$$$$1 from "./sections/Seo/SeoBlogPostListing.tsx";
import * as $$$$$$2 from "./sections/Template.tsx";

const manifest = {
  "loaders": {
    "spire/loaders/BlogPostItem.ts": $$$0,
    "spire/loaders/BlogpostList.ts": $$$2,
    "spire/loaders/BlogpostListing.ts": $$$3,
    "spire/loaders/BlogPostPage.ts": $$$1,
    "spire/loaders/BlogsByAuthor.ts": $$$4,
    "spire/loaders/BlogsByTag.ts": $$$5,
    "spire/loaders/GetAuthors.ts": $$$6,
    "spire/loaders/GetTags.ts": $$$7,
  },
  "sections": {
    "spire/sections/blocks/BlockImage.tsx": $$$$$$3,
    "spire/sections/blocks/Callout.tsx": $$$$$$4,
    "spire/sections/blocks/CardGroup.tsx": $$$$$$5,
    "spire/sections/blocks/Checklist.tsx": $$$$$$6,
    "spire/sections/blocks/Code.tsx": $$$$$$7,
    "spire/sections/blocks/Comparison.tsx": $$$$$$8,
    "spire/sections/blocks/Cta.tsx": $$$$$$9,
    "spire/sections/blocks/Divider.tsx": $$$$$$10,
    "spire/sections/blocks/Heading.tsx": $$$$$$11,
    "spire/sections/blocks/List.tsx": $$$$$$12,
    "spire/sections/blocks/Paragraph.tsx": $$$$$$13,
    "spire/sections/blocks/Quote.tsx": $$$$$$14,
    "spire/sections/blocks/Stat.tsx": $$$$$$15,
    "spire/sections/blocks/StatGroup.tsx": $$$$$$16,
    "spire/sections/blocks/Steps.tsx": $$$$$$17,
    "spire/sections/blocks/Video.tsx": $$$$$$18,
    "spire/sections/Seo/SeoBlogPost.tsx": $$$$$$0,
    "spire/sections/Seo/SeoBlogPostListing.tsx": $$$$$$1,
    "spire/sections/Template.tsx": $$$$$$2,
  },
  "name": "spire",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
