
// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// To generate this file: deno run -A scripts/openAPI.ts

export interface API {
/** @description Permite autorizar operações usando o access_token e a senha do usuário */
 "POST /api/v2/users/authorize": {
              searchParams:  {
  access_token?: string;
  password?: string;
}

            }
/** @description Realiza o login do usuário a partir do email e da senha */
 "POST /api/v2/users/login": {
              searchParams:  {
  email?: string;
  password?: string;
}

            }
/** @description Realiza o logout do usuário a partir do access_token do mesmo */
 "POST /api/v2/users/logout": {
              searchParams:  {
  /**
   * Token de validação de usuário logado
   *
   * O `access_token` é gerado quando o usuário loga no Admin
   */
  access_token?: string;
}

            }
/** @description Retorna os dados de um usuário pelo seu ID */
 "GET /api/v2/users/:id": {
              
            }
/** @description Atualiza um usuário */
 "PUT /api/v2/users/:id": {
              searchParams:  {
  email?: string;
  name?: string;
  role_name?:
    | {"0": "A"; "1": "g"; "2": "e"; "3": "n"; "4": "t"; "5": "e"}
    | {"0": "G"; "1": "e"; "2": "s"; "3": "t"; "4": "o"; "5": "r"}
    | {"0": "L"; "1": "o"; "2": "c"; "3": "a"; "4": "l"};
  password?: string;
  password_confirmation?: string;
  external_code?: string;
  phone_area?: string;
  phone?: string;
  tags?: string[];
}

            }
/** @description Retorna as versões da regra de bônus cadastrada */
 "GET /api/v2/credits/rules/versions": {
              
            }
/** @description Retorna as regras de bônus cadastradas */
 "GET /api/v2/credits/rules": {
              
            }
/** @description Permite atualizar as regras de bônus */
 "PUT /api/v2/credits/rules": {
              searchParams:  {
  /**
   * Percentual em cima do total do pedido que vai ser dado de bônus para o cliente
   */
  bonus?: number;
  /**
   * Número de dias em que o crédito começa a valer
   */
  valid_in?: number;
  /**
   * Número de dias para a expiração do crédito
   */
  valid_for?: number;
  /**
   * Valor mínimo do pedido para que o bônus possa ser transferido para o cliente
   */
  minimum_subtotal?: number;
  /**
   * Percentual do subtotal do pedido que pode ser pago com o bônus
   */
  maximum_usage_factor?: number;
}

            }
/** @description Permite remover as regras de bônus, desativando o recurso */
 "DELETE /api/v2/credits/rules": {
              
            }
/** @description Retorna os dados de um pedido usando o `code` ou `token` */
 "GET /api/v2/orders/:code": {
              
            }
/** @description Retorna uma lista de pedidos */
 "GET /api/v2/orders": {
              
            }
/** @description Faz a captura do pagamento no adquirente
Apenas para pedidos pagos com cartão de crédito */
 "POST /api/v2/orders/:code/capture": {
              
            }
/** @description Altera o status do pedido para "confirmado" */
 "POST /api/v2/orders/:code/confirm": {
              searchParams:  {
  /**
   * Para cartão de crédito deve ser enviado OBRIGATORIAMENTE o retorno da requisição para "/api/v2/orders/{code}/capture"
   */
  confirmation_data?: string;
}

            }
/** @description Faz o estorno do pagamento no adquirente
Apenas para pedidos pagos com cartão de crédito */
 "POST /api/v2/orders/:code/chargeback": {
              
            }
/** @description Altera o status do pedido para "cancelado" */
 "POST /api/v2/orders/:code/cancel": {
              searchParams:  {
  /**
   * Deve ser enviado algo que comprove que o pagamento foi devolvido.
   * Para cartão de crédito deve ser enviado OBRIGATORIAMENTE o retorno da requisição para "/api/v2/orders/{code}/chargeback"
   */
  cancelation_data?: string;
}

            }
/** @description Altera o status do pacote para "enviado" */
 "PATCH /api/v2/orders/:order_code/packages/:package_code/ship": {
              
            }
/** @description Altera o pacote para "entregue" */
 "PATCH /api/v2/orders/:order_code/packages/:package_code/deliver": {
              
            }
/** @description Recebe uma lista JSON com os SKUs que devem ser atualizados. A atualização será executada em segundo plano em aproximadamente 1 minuto  */
 "POST /api/v2/variants/quantity": {
              searchParams: {
  sku?: string;
  quantity?: number;
  /**
   * Informe somente para atualizar o estoque de um local específico
   */
  place_id?: number;
}[];

            }
/** @description Atualiza o estoque de uma variante de um produto */
 "POST /api/v2/variants/:sku/quantity": {
              
            }
/** @description Atualiza o estoque específico de um local */
 "PATCH /api/v2/variants/:sku/inventories/:place_id": {
              
            }
/** @description Permite listar as variantes de um produto */
 "GET /api/v2/products/:product_id/variants": {
              
            }
/** @description Permite criar uma variante */
 "POST /api/v2/products/:product_id/variants": {
              searchParams:  {
  sku?: string;
  name?: string;
  quantity?: number;
  main?: boolean;
  /**
   * Largura do produto, em centímetros
   */
  width?: number;
  /**
   * Altura do produto, em centímetros
   */
  height?: number;
  /**
   * Comprimento do produito, em centímetros
   */
  length?: number;
  /**
   * Massa do produto, em gramas
   */
  weight?: number;
  /**
   * Dias de manuseio da variante
   */
  handling_days?: number;
  price?: number;
  /**
   * Customização da variante
   */
  custom_attributes?: {};
  min_quantity?: number;
  norder?: number;
  property1?: string;
  property2?: string;
  property3?: string;
  barcode?: string;
}

            }
/** @description Permite remover uma variante */
 "DELETE /api/v2/products/:product_id/variants/:id": {
              
            }
/** @description Permite atualizar uma variante */
 "PATCH /api/v2/products/:product_id/variants/:id": {
              searchParams:  {
  sku?: string;
  name?: string;
  quantity?: number;
  main?: boolean;
  width?: number;
  height?: number;
  length?: number;
  weight?: number;
  handling_days?: number;
  price?: number;
  custom_attributes?: {};
  min_quantity?: number;
  norder?: number;
  property1?: string;
  property2?: string;
  property3?: string;
  barcode?: string;
  quantity_sold?: number;
}

            }
/** @description Permite determinar a ordem das variantes dentro de cada produto */
 "POST /api/v2/variants/reorder": {
              searchParams:  {
  /**
   * A ordem dos elementos será replicada para as variantes
   */
  ids?: number[];
}

            }
/** @description Retorna um template usando o path dele */
 "GET /api/v2/templates/:path": {
              
            }
/** @description Remove um template usando o path dele */
 "DELETE /api/v2/templates/:path": {
              
            }
/** @description Atualiza o conteúdo de um template usando o path dele */
 "PATCH /api/v2/templates/:path": {
              searchParams:  {
  body?: string;
}

            }
/** @description Retorna uma lista de templates */
 "GET /api/v2/templates": {
              
            }
/** @description Cria um novo template */
 "POST /api/v2/templates": {
              searchParams:  {
  path?: string;
  body?: string;
}

            }
/** @description Reativa um usuário que estiver desativado */
 "POST /api/v2/users/:id/activate": {
              
            }
/** @description Desativa um usuário */
 "POST /api/v2/users/:id/deactivate": {
              
            }
/** @description Lista os usuários */
 "GET /api/v2/users": {
              
            }
/** @description Cria um usuário */
 "POST /api/v2/users": {
              searchParams:  {
  email?: string;
  name?: string;
  role_name?:
    | {"0": "A"; "1": "g"; "2": "e"; "3": "n"; "4": "t"; "5": "e"}
    | {"0": "G"; "1": "e"; "2": "s"; "3": "t"; "4": "o"; "5": "r"}
    | {"0": "L"; "1": "o"; "2": "c"; "3": "a"; "4": "l"};
  password?: string;
  password_confirmation?: string;
  external_code?: string;
  phone_area?: string;
  phone?: string;
  tags?: string[];
}

            }
/** @description Lista os usuários */
 "GET /api/v2/users/tags": {
              
            }
/** @description Retorna a lista de carrinhos ativos nos últimos 60 dias */
 "GET /api/v2/carts": {
              
            }
/** @description Permite criar um carrinho */
 "POST /api/v2/carts": {
              searchParams: /**
 * Parâmetros criação e atualização de carrinho
 */
export interface ParametrosDeCarrinhoResumido {
  /**
   * Agente que criou o carrinho
   */
  agent?: string;
  /**
   * Código de Endereçamento Postal (CEP) do destinatário do pedido
   */
  zip?: string;
  /**
   * Código identificador `ID` do cliente
   */
  client_id?: number;
  /**
   * Código identificador `ID` do desconto do carrinho
   */
  coupon_code?: string;
  /**
   * @deprecated
   * Email do cliente
   */
  email?: string;
  /**
   * Token do desconto
   */
  rebate_token?: string;
}

            }
/** @description Permite retornar um carrinho */
 "GET /api/v2/carts/:id": {
              
            }
/** @description Permite criar um carrinho */
 "POST /api/v2/carts/:id": {
              searchParams:  {
  agent?: string;
  zip?: string;
  client_id?: number;
  coupon_code?: string;
  /**
   * DEPRECATED: enviar o `client_id`
   */
  email?: string;
  rebate_token?: string;
}

            }
/** @description Permite excluir um carrinho */
 "DELETE /api/v2/carts/:id": {
              
            }
/** @description Permite atualizar os atributos de um carrinho */
 "PATCH /api/v2/carts/:id": {
              searchParams:  {
  agent?: string;
  zip?: string;
  client_id?: number;
  /**
   * DEPRECATED: enviar o `client_id`
   */
  email?: string;
  rebate_token?: string;
}

            }
/** @description Permite calcular as parcelas referentes ao total do carrinho */
 "GET /api/v2/carts/:id/installments": {
              
            }
/** @description Lista os locais */
 "GET /api/v2/places": {
              
            }
/** @description Cria um local */
 "POST /api/v2/places": {
              searchParams:  {
  name?: string;
  address_line_1?: string;
  address_line_2?: string;
  city?: string;
  neighborhood?: string;
  zip?: string;
  home_page?: string;
  latitude?: number;
  longitude?: number;
  images?: string[];
  description?: string;
  email?: string;
  first_phone?: string;
  second_phone?: string;
  mobile_phone?: string;
  only_cash?: boolean;
  categories?: string[];
  marker_url?: string;
  state?: string;
  opening_hours?: string;
  warehouse?: boolean;
  legal_name?: string;
  cnpj?: string;
}

            }
/** @description Remove um local */
 "DELETE /api/v2/places/:id": {
              
            }
/** @description Atualiza um local */
 "PATCH /api/v2/places/:id": {
              searchParams:  {
  name?: string;
  address_line_1?: string;
  address_line_2?: string;
  city?: string;
  neighborhood?: string;
  zip?: string;
  home_page?: string;
  latitude?: number;
  longitude?: number;
  images?: string[];
  description?: string;
  email?: string;
  first_phone?: string;
  second_phone?: string;
  mobile_phone?: string;
  only_cash?: boolean;
  categories?: string[];
  marker_url?: string;
  state?: string;
  opening_hours?: string;
  warehouse?: boolean;
  legal_name?: string;
  cnpj?: string;
}

            }
/** @description Lista as notas fiscais */
 "GET /api/v2/orders/:code/packages/:package_code/invoices": {
              
            }
/** @description Cria uma nota fiscal */
 "POST /api/v2/orders/:code/packages/:package_code/invoices": {
              searchParams:  {
  number?: number;
  series?: number;
  issued_at?: string;
  key?: string;
  volumes?: number;
}

            }
/** @description Remove uma nota fiscal */
 "DELETE /api/v2/orders/:code/packages/:package_code/invoices/:number": {
              
            }
/** @description Atualiza uma nota fiscal */
 "PATCH /api/v2/orders/:code/packages/:package_code/invoices/:number": {
              searchParams:  {
  number?: number;
  series?: number;
  issued_at?: string;
  key?: string;
  volumes?: number;
}

            }
/** @description Será enviado por email um link para o cadastro da nova senha
O link tem validade de 24 horas */
 "POST /api/v2/users/reset_password": {
              searchParams:  {
  email?: string;
}

            }
/** @description Cadastra a nova senha */
 "PATCH /api/v2/users/reset_password": {
              searchParams:  {
  /**
   * Token pare renovação de senha enviado por email
   */
  token?: string;
  /**
   * Nova senha para o usuário
   */
  password?: string;
  /**
   * Confirmação da nova senha do usuário
   */
  password_confirmation?: string;
}

            }
/** @description Retorna o endereço de entrega */
 "GET /api/v2/orders/:code/shipping_address": {
              
            }
/** @description Lista os recebedores */
 "GET /api/v2/payment_recipients": {
              
            }
/** @description Cria um recebedor */
 "POST /api/v2/payment_recipients": {
              searchParams:  {
  tag_id?: number;
  recipient_id?: number;
  percentage?: number;
  active?: boolean;
  charge_processing_fee?: boolean;
  liable?: boolean;
  code?: string;
  place_id?: number;
  user_id?: number;
  /**
   * Indica se o frete deve ser incluído no split do pagamento
   */
  include_shipping?: boolean;
}

            }
/** @description Retorna um recebedor */
 "GET /api/v2/payment_recipients/:id": {
              
            }
/** @description Remove um recebedor */
 "DELETE /api/v2/payment_recipients/:id": {
              
            }
/** @description Atualiza um recebedor */
 "PATCH /api/v2/payment_recipients/:id": {
              searchParams:  {
  tag_id?: number;
  recipient_id?: number;
  percentage?: number;
  active?: boolean;
  charge_processing_fee?: boolean;
  liable?: boolean;
  code?: string;
  place_id?: number;
  user_id?: number;
  /**
   * Indica se o frete deve ser incluído no split do pagamento
   */
  include_shipping?: boolean;
}

            }
/** @description Permite a listagem de recebíveis do usuário */
 "GET /api/v2/users/:user_id/payables": {
              
            }
/** @description Lista os membros da audiência */
 "GET /api/v2/audience_members": {
              
            }
/** @description Permite criar um membro da audiência */
 "POST /api/v2/audience_members": {
              searchParams:  {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone_area?: string;
  phone?: string;
  tags?: string[];
}

            }
/** @description Permite remover um membro da audiência */
 "DELETE /api/v2/audience_members/:id": {
              
            }
/** @description Permite alterar um membro da audiência */
 "PATCH /api/v2/audience_members/:id": {
              searchParams:  {
  first_name?: string;
  last_name?: string;
  email?: string;
  phone_area?: string;
  phone?: string;
  tags?: string[];
}

            }
/** @description Lista os rastreios de um pacote de um pedido */
 "GET /api/v2/orders/:order_code/packages/:package_code/trackings": {
              
            }
/** @description Adiciona um rastreio para um pacote de um pedido */
 "POST /api/v2/orders/:order_code/packages/:package_code/trackings": {
              searchParams:  {
  /**
   * Código de rastreio
   */
  code?: string;
  /**
   * Transportadora
   */
  company?: string;
  /**
   * Link de rastreamento
   */
  url?: string;
}

            }
/** @description Remove um rastreio */
 "DELETE /api/v2/orders/:order_code/packages/:package_code/trackings/:id": {
              
            }
/** @description Lista os itens de um carrinho */
 "GET /api/v2/carts/:cart_id/items": {
              
            }
/** @description Permite criar um item do carrinho */
 "POST /api/v2/carts/:cart_id/items": {
              searchParams: /**
 * Modelo de carcaterística de produto para item no carrinho
 */
export interface Produto {
  /**
   * Código SKU da variante do produto
   */
  sku?: string;
  /**
   * Unidades do produto disponíveis fisicamente
   */
  quantity?: number;
  /**
   * Campo para registro de observações, chave ou valores necessários
   */
  extra?: {};
  /**
   * Código identificador do local do produto
   */
  place_id?: number;
  /**
   * Código de cupom
   */
  store_coupon_code?: string;
  /**
   * [Personalização](http://ajuda.vnda.com.br/pt-BR/articles/1763398-funcionalidades-produtos-personalizados) do produto
   */
  customizations?: {
    /**
     * [Personalização](http://ajuda.vnda.com.br/pt-BR/articles/1763398-funcionalidades-produtos-personalizados) incluídas no Admin da loja.
     * Se por exemplo a customização do produto é a cor, o parâmetro para a requisição deve ser `Color` ao invés de `CUstomization`.
     */
    Customization?: string;
  }[];
}

            }
/** @description Remove um item do carrinho */
 "DELETE /api/v2/carts/:cart_id/items/:id": {
              
            }
/** @description Atualiza um item do carrinho */
 "PATCH /api/v2/carts/:cart_id/items/:id": {
              searchParams:  {
  quantity?: number;
  place_id?: number;
  extra?: {};
  store_coupon_code?: string;
}

            }
/** @description Permite adicionar itens em bulk ao carrinho */
 "POST /api/v2/carts/:cart_id/items/bulk": {
              searchParams:  {
  sku?: string;
  quantity?: number;
  extra?: {};
  place_id?: number;
  /**
   * Itens do carrinho
   */
  items?: unknown[][];
}

            }
/** @description Cria uma promoção */
 "POST /api/v2/discounts": {
              searchParams:  {
  name?: string;
  start_at?: string;
  end_at?: string;
  valid_to?: {"0": "s"; "1": "t"; "2": "o"; "3": "r"; "4": "e"} | {"0": "c"; "1": "a"; "2": "r"; "3": "t"};
  description?: string;
  enabled?: boolean;
  email?: string;
  cpf?: string;
  tags?: string;
}

            }
/** @description Retorna uma promoção */
 "GET /api/v2/discounts/:id": {
              
            }
/** @description Remove uma promoção */
 "DELETE /api/v2/discounts/:id": {
              
            }
/** @description Altera uma promoção */
 "PATCH /api/v2/discounts/:id": {
              searchParams:  {
  name?: string;
  start_at?: string;
  end_at?: string;
  valid_to?: {"0": "s"; "1": "t"; "2": "o"; "3": "r"; "4": "e"} | {"0": "c"; "1": "a"; "2": "r"; "3": "t"};
  description?: string;
  enabled?: boolean;
  email?: string;
  cpf?: string;
  tags?: string;
}

            }
/** @description Lista as regras de desconto de uma promoção */
 "GET /api/v2/discounts/:discount_id/rules": {
              
            }
/** @description Cria uma regra de desconto */
 "POST /api/v2/discounts/:discount_id/rules": {
              searchParams:  {
  apply_to?:
    | {"0": "p"; "1": "r"; "2": "o"; "3": "d"; "4": "u"; "5": "c"; "6": "t"}
    | {"0": "t"; "1": "a"; "2": "g"}
    | {"0": "s"; "1": "u"; "2": "b"; "3": "t"; "4": "o"; "5": "t"; "6": "a"; "7": "l"}
    | {"0": "t"; "1": "o"; "2": "t"; "3": "a"; "4": "l"}
    | {"0": "s"; "1": "h"; "2": "i"; "3": "p"; "4": "p"; "5": "i"; "6": "n"; "7": "g"};
  amount_type?: {"0": "R"; "1": "$"} | {"0": "%"};
  amount?: number;
  product_id?: number;
  tag_name?: string;
  min_quantity?: number;
  shipping_method?: string;
  min_subtotal?: number;
  gift?: boolean;
  combinated_product_id?: number;
  client_tag?: string;
  shipping_rule?: string;
  gift_quantity?: number;
  agent_tag?: string;
  regions?: string[];
  channel?: string[];
}

            }
/** @description Remove uma regra de desconto */
 "DELETE /api/v2/discounts/:discount_id/rules/:id": {
              
            }
/** @description Altera uma regra de desconto */
 "PATCH /api/v2/discounts/:discount_id/rules/:id": {
              searchParams:  {
  apply_to?:
    | {"0": "p"; "1": "r"; "2": "o"; "3": "d"; "4": "u"; "5": "c"; "6": "t"}
    | {"0": "t"; "1": "a"; "2": "g"}
    | {"0": "s"; "1": "u"; "2": "b"; "3": "t"; "4": "o"; "5": "t"; "6": "a"; "7": "l"}
    | {"0": "t"; "1": "o"; "2": "t"; "3": "a"; "4": "l"}
    | {"0": "s"; "1": "h"; "2": "i"; "3": "p"; "4": "p"; "5": "i"; "6": "n"; "7": "g"};
  amount_type?: {"0": "R"; "1": "$"} | {"0": "%"};
  amount?: number;
  product_id?: number;
  tag_id?: number;
  min_quantity?: number;
  shipping_method?: string;
  min_subtotal?: number;
  gift?: boolean;
  combinated_product_id?: number;
  client_tag?: string;
  shipping_rule?: string;
  gift_quantity?: number;
  agent_tag?: string;
  regions?: string[];
  channel?: string[];
}

            }
/** @description Permite listar os cupons de desconto de uma promoção */
 "GET /api/v2/discounts/:discount_id/coupons": {
              
            }
/** @description Cria um cupom de desconto */
 "POST /api/v2/discounts/:discount_id/coupons": {
              searchParams:  {
  code?: string;
  uses_per_code?: number;
  uses_per_user?: number;
  referrer_email?: string;
  quantity?: number;
  user_id?: number;
}

            }
/** @description Remove um cupom de desconto */
 "DELETE /api/v2/discounts/:discount_id/coupons:id": {
              
            }
/** @description Atualiza um cupom de desconto */
 "PATCH /api/v2/discounts/:discount_id/coupons:id": {
              searchParams:  {
  /**
   * Caso deseje um uso ilimitado do cupom, o valor desse campo deverá ser 0
   */
  uses_per_code?: number;
  /**
   * Caso deseje um uso ilimitado do cupom, o valor desse campo deverá ser 0
   */
  uses_per_user?: number;
}

            }
/** @description Lista os produtos */
 "GET /api/v2/products": {
              
            }
/** @description Cria um produto */
 "POST /api/v2/products": {
              searchParams: /**
 * Modelo simplificado de um produto para atualização e criação
 */
export interface SimpleProduct {
  /**
   * Código de Referência do produto
   */
  reference?: string;
  /**
   * Nome do produto
   */
  name?: string;
  /**
   * Descrição do produto
   */
  description?: string;
  /**
   * Indica se o produto está ativo (`true`) ou invativo (`false`)
   */
  active?: boolean;
  /**
   * Tags associadas ao produto
   */
  tag_list?: string;
  /**
   * Tipo de produto
   */
  product_type?:
    | {"0": "p"; "1": "r"; "2": "o"; "3": "d"; "4": "u"; "5": "c"; "6": "t"}
    | {"0": "s"; "1": "a"; "2": "m"; "3": "p"; "4": "l"; "5": "e"}
    | {
        "0": "s";
        "1": "u";
        "2": "b";
        "3": "s";
        "4": "c";
        "5": "r";
        "6": "i";
        "7": "p";
        "8": "t";
        "9": "i";
        "10": "o";
        "11": "n";
      };
}

            }
/** @description Retorna um produto */
 "GET /api/v2/products/:id": {
              
            }
/** @description Remove um produto */
 "DELETE /api/v2/products/:id": {
              
            }
/** @description Atualiza um produto */
 "PATCH /api/v2/products/:id": {
              searchParams:  {
  name?: string;
  description?: string;
  active?: boolean;
  reference?: string;
  tag_list?: string;
}

            }
/** @description Permite atualizar um produto pela referência */
 "PATCH /api/v2/products/reference/:reference": {
              searchParams:  {
  reference?: string;
  name?: string;
  description?: string;
  active?: boolean;
  product_type?:
    | {"0": "p"; "1": "r"; "2": "o"; "3": "d"; "4": "u"; "5": "c"; "6": "t"}
    | {"0": "s"; "1": "a"; "2": "m"; "3": "p"; "4": "l"; "5": "e"}
    | {
        "0": "s";
        "1": "u";
        "2": "b";
        "3": "s";
        "4": "c";
        "5": "r";
        "6": "i";
        "7": "p";
        "8": "t";
        "9": "i";
        "10": "o";
        "11": "n";
      };
}

            }
/** @description Recebe uma avaliação e recalcula a pontuação atual */
 "POST /api/v2/products/:id/rate": {
              
            }
/** @description Busca os produtos de acordo com os parâmetros definidos */
 "GET /api/v2/products/search": {
              
            }
/** @description Retorna uma variante pelo SKU */
 "GET /api/v2/variants/:sku": {
              
            }
/** @description Permite atualizar uma variante pelo SKU */
 "PATCH /api/v2/variants/:sku": {
              searchParams:  {
  sku?: string;
  name?: string;
  quantity?: number;
  main?: boolean;
  /**
   * Largura do produto, em centímetros
   */
  width?: number;
  /**
   * Altura do produto, em centímetros
   */
  height?: number;
  /**
   * Comprimento do produito, em centímetros
   */
  length?: number;
  /**
   * Massa do produto, em gramas
   */
  weight?: number;
  /**
   * Dias de manuseio da variante
   */
  handling_days?: number;
  /**
   * Preço do item
   */
  price?: number;
  /**
   * Customização da variante
   */
  custom_attributes?: {};
  min_quantity?: number;
  norder?: number;
  property1?: VariantProperty;
  property2?: VariantProperty;
  property3?: VariantProperty;
  barcode?: string;
  /**
   * Quantidade de itens vendidos
   */
  quantity_sold?: number;
}
/**
 * Modelo que representa uma propriedade de uma variante
 */
export interface VariantProperty {
  /**
   * Nome da propriedade
   */
  name: string;
  /**
   * Valor da propriedade
   */
  value: string;
  /**
   * Indica se a variante possui uma definição (`true`) ou se a variante não possui (`false`)
   */
  defining: boolean;
}

            }
/** @description Lista as imagens de uma variante passando o SKU da mesma na URL */
 "GET /api/v2/products/:product_id/variants/:sku/images": {
              
            }
/** @description Lista as imagens de uma variante passando o SKU da mesma nos parâmetros */
 "GET /api/v2/products/:product_id/variants/images": {
              
            }
/** @description Calcula o frete para uma determinada variante */
 "GET /api/v2/variants/:sku/shipping_methods": {
              searchParams:  {
  quantity?: number;
  zip?: string;
}

            }
/** @description Permite listar as tags */
 "GET /api/v2/tags": {
              
            }
/** @description Cria uma tag */
 "POST /api/v2/tags": {
              searchParams:  {
  name?: string;
  title?: string;
  /**
   * Equivalente ao subtítulo
   */
  blurb?: string;
  description?: string;
  tag_type?: string;
  show_in_carts?: boolean;
}

            }
/** @description Lista os tipos de tags usados em alguma tag */
 "GET /api/v2/tags/types": {
              
            }
/** @description Retorna uma tag */
 "GET /api/v2/tags/:name": {
              
            }
/** @description Remove uma tag */
 "DELETE /api/v2/tags/:name": {
              
            }
/** @description Permite atualizar uma tag */
 "PATCH /api/v2/tags/:name": {
              
            }
/** @description Retorna os dados de um cupom usando o seu código */
 "GET /api/v2/coupon_codes/:code": {
              
            }
/** @description Cria um pedido no Paypal para que posteriormente possa receber um pagamento */
 "POST /api/v2/carts/:cart_id/payment/paypal": {
              
            }
/** @description Retorna uma lista de clientes. Caso seja informado o parâmetro "email", então apenas o cliente com esse email será retornado */
 "GET /api/v2/clients": {
              
            }
/** @description Permite criar um cliente */
 "POST /api/v2/clients": {
              searchParams:  {
  email?: string;
  first_name?: string;
  last_name?: string;
  birthdate?: string;
  gender?: {"0": "M"} | {"0": "F"};
  /**
   * separado por vírgula
   */
  tags?: string;
  lists?: string[];
  password?: string;
  password_confirmation?: string;
  terms?: boolean;
}

            }
/** @description Permite retornar as informações do cliente
O auth_token do cliente pode ser informado no lugar do ID na URL */
 "GET /api/v2/clients/:id": {
              
            }
/** @description Permite remover um cliente */
 "DELETE /api/v2/clients/:id": {
              
            }
/** @description Permite atualizar as informações do cliente */
 "PATCH /api/v2/clients/:id": {
              searchParams:  {
  email?: string;
  first_name?: string;
  last_name?: string;
  birthdate?: string;
  gender?: {"0": "M"} | {"0": "F"};
  /**
   * separado por vírgula
   */
  tags?: string;
  lists?: string[];
  password?: string;
  password_confirmation?: string;
  terms?: boolean;
}

            }
/** @description Retorna a lista de pedidos do cliente */
 "GET /api/v2/clients/:id/orders": {
              
            }
/** @description Lista os endereços do cliente utilizados nos pedidos que foram confirmados */
 "GET /api/v2/clients/:id/addresses": {
              
            }
/** @description Lista os endereços cadastrados pelo cliente */
 "GET /api/v2/clients/:client_id/registered_addresses": {
              
            }
/** @description Permite criar um endereço do cliente */
 "POST /api/v2/clients/:client_id/registered_addresses": {
              searchParams:  {
  street_name?: string;
  street_number?: string;
  complement?: string;
  neighborhood?: string;
  label?: string;
  zip?: string;
  reference?: string;
}

            }
/** @description Delete o endereço cadastrado pelo cliente */
 "DELETE /api/v2/clients/:client_id/registered_addresses/:id": {
              
            }
/** @description Permite atualizar um endereço do cliente */
 "PATCH /api/v2/clients/:client_id/registered_addresses/:id": {
              searchParams:  {
  street_name?: string;
  street_number?: string;
  complement?: string;
  neighborhood?: string;
  label?: string;
  zip?: string;
  reference?: string;
}

            }
/** @description Cria uma senha para o cliente e envia por email */
 "POST /api/v2/clients/recover_password": {
              
            }
/** @description Retorna o saldo de crétitos do cliente */
 "GET /api/v2/clients/:id/credits": {
              
            }
/** @description Retorna as transfertências de crétidos realizadas */
 "GET /api/v2/clients/:id/credits/transfers": {
              
            }
/** @description Lista os bônus do cliente que ainda não foram utilizados */
 "GET /api/v2/clients/:id/bonuses": {
              
            }
/** @description Solicita a remoção (esquecimento) dos dados pessoais de um cliente, de acordo com a LGPD */
 "PATCH /api/v2/clients/:id/remove_personal_data": {
              
            }
/** @description Faz o login do cliente pelo token salvo no campo auth_token */
 "GET /api/v2/auth/email/:token": {
              
            }
/** @description Faz o login do cliente por usuário e senha */
 "POST /api/v2/auth/client": {
              searchParams:  {
  email?: string;
  password?: string;
}

            }
/** @description Faz o pagamento do carrinho usando a forma de pagamento informada */
 "POST /api/v2/carts/:cart_id/payment": {
              searchParams:  {
  /**
   * Meio de pagamento
   */
  payment_method?: {"0": "p"; "1": "i"; "2": "x"};
  /**
   * Canal de venda do carrinho
   */
  channel?:
    | {"0": "e"; "1": "c"; "2": "o"; "3": "m"; "4": "m"; "5": "e"; "6": "r"; "7": "c"; "8": "e"}
    | {"0": "d"; "1": "i"; "2": "r"; "3": "e"; "4": "c"; "5": "t"};
}

            }
/** @description Lista os menus */
 "GET /api/v2/menus": {
              
            }
/** @description Cria um menu */
 "POST /api/v2/menus": {
              searchParams:  {
  label?: string;
  tooltip?: string;
  description?: string;
  type?: string;
  url?: string;
  page_id?: number;
  parent_id?: number;
  position?: string;
  new_position?: string;
  external?: boolean;
  tag_id?: number;
}

            }
/** @description Retorna um menu */
 "GET /api/v2/menus/:id": {
              
            }
/** @description Remove um menu */
 "DELETE /api/v2/menus/:id": {
              
            }
/** @description Atualiza um menu */
 "PATCH /api/v2/menus/:id": {
              searchParams:  {
  label?: string;
  tooltip?: string;
  description?: string;
  type?: string;
  url?: string;
  page_id?: number;
  parent_id?: number;
  position?: string;
  new_position?: string;
  external?: boolean;
  tag_id?: number;
}

            }
/** @description Lista as posições dos menus */
 "GET /api/v2/menus/positions": {
              
            }
/** @description Reordena os menus na ordem em que seus ids são listados no request */
 "POST /api/v2/menus/reorder": {
              searchParams:  {
  /**
   * A ordem dos elementos será replicada para os menus
   */
  ids?: number[];
}

            }
/** @description Retorna os menus em árvore, organizados pela posição */
 "GET /api/v2/menus/tree": {
              
            }
/** @description Retorna uma mensagem do site */
 "GET /api/v2/site_message": {
              
            }
/** @description Remove uma mensagem do site */
 "DELETE /api/v2/site_message": {
              
            }
/** @description Cria ou atualiza uma mensagem do site */
 "PATCH /api/v2/site_message": {
              searchParams:  {
  title?: string;
  description?: string;
  call_to_action?: string;
}

            }
/** @description Lista as imagens associadas a loja */
 "GET /api/v2/shop/images": {
              
            }
/** @description Permite cadastrar uma imagem */
 "POST /api/v2/shop/images": {
              searchParams:  {
  position?: string;
  file_uid?: string;
}

            }
/** @description Permite remover uma imagem da loja */
 "DELETE /api/v2/shop/images/:id": {
              
            }
/** @description Permite adicionar um atributo customizado de produto */
 "POST /api/v2/shop/product_attributes": {
              searchParams:  {
  index?: number;
  name?: string;
  mandatory?: boolean;
}

            }
/** @description Permite listar as personalizações */
 "GET /api/v2/customizations": {
              
            }
/** @description Permite criar uma personalização */
 "POST /api/v2/customizations": {
              searchParams:  {
  group_name?: string;
  group_type?: string;
  name?: string;
  label?: string;
  image_uid?: string;
  image_name?: string;
  price?: number;
  quantity?: number;
  handling_days?: number;
  tag_id?: number;
  sku?: string;
  pattern?: string;
}

            }
/** @description Permite retornar uma personalização */
 "GET /api/v2/customizations/:id": {
              
            }
/** @description Permite remover uma personalização */
 "DELETE /api/v2/customizations/:id": {
              
            }
/** @description Permite alterar uma personalização */
 "PATCH /api/v2/customizations/:id": {
              searchParams:  {
  group_name?: string;
  group_type?: string;
  name?: string;
  label?: string;
  image_uid?: string;
  image_name?: string;
  price?: string;
  quantity?: string;
  handling_days?: string;
  tag_id?: string;
  sku?: string;
  pattern?: string;
}

            }
/** @description Permite listar os itens do pedido */
 "GET /api/v2/orders/:order_id/items": {
              
            }
/** @description Permite listar as personalizações de cada item do pedido */
 "GET /api/v2/orders/:order_id/items/:item_id/customizations": {
              
            }
/** @description Permite listar as personalizações de cada item do carrinho */
 "GET /api/v2/carts/:cart_id/items/:item_id/customizations": {
              
            }
/** @description Permite remover uma customização do item do carrinho */
 "DELETE /api/v2/carts/:cart_id/items/:item_id/customizations": {
              
            }
/** @description Lista os mapeamentos */
 "GET /api/v2/mappings": {
              
            }
/** @description Cria um mapeamento */
 "POST /api/v2/mappings": {
              searchParams:  {
  key?: string;
  from?: string[];
  to?: string;
}

            }
/** @description Retorna os dados de um mapeamento */
 "GET /api/v2/mappings/:id": {
              
            }
/** @description Remove um mapeamento */
 "DELETE /api/v2/mappings/:id": {
              
            }
/** @description Atualiza um mapeamento */
 "PATCH /api/v2/mappings/:id": {
              searchParams:  {
  key?: string;
  from?: string[];
  to?: string;
}

            }
/** @description Retorna a lista de banners */
 "GET /api/v2/banners": {
              
            }
/** @description Retorna os dados de um banner */
 "GET /api/v2/banners/:id": {
              
            }
/** @description Retorna todos os banners disponíveis agrupados por tag */
 "GET /api/v2/banners/all": {
              
            }
/** @description Permite calcular o frete para pedidos internacionais */
 "GET /api/v2/carts/:cart_id/shipping_methods/intl": {
              
            }
/** @description Lista as amostras disponíveis para determinado carrinho */
 "GET /api/v2/carts/:cart_id/samples": {
              
            }
/** @description Retorna o endereço de entrega */
 "GET /api/v2/carts/:cart_id/shipping_address": {
              
            }
/** @description Adiciona um endereço de entrega no carrinho */
 "POST /api/v2/carts/:cart_id/shipping_address": {
              searchParams: /**
 * Modelo de endereço de envio para carrinho e pedido
 */
export interface EnderecoDeEnvio {
  /**
   * Nome do cliente
   */
  first_name?: string;
  /**
   * Sobrenome do cliente
   */
  last_name?: string;
  /**
   * Nome da empresa (para clientes jurídicos)
   */
  company_name?: string;
  /**
   * Email do cliente
   */
  email?: string;
  /**
   * Código de Discagem Direta à Distância (DDD)
   */
  first_phone_area?: string;
  /**
   * Telefone do cliente
   */
  first_phone?: string;
  /**
   * Código de Discagem Direta à Distância (DDD)
   */
  second_phone_area?: string;
  /**
   * Telefone do cliente
   */
  second_phone?: string;
  /**
   * Nome do recebedor
   */
  recipient_name?: {
    [k: string]: unknown;
  };
  /**
   * Logradouro
   */
  street_name?: string;
  /**
   * Número
   */
  street_number?: string;
  /**
   * Complemento
   */
  complement?: string;
  /**
   * Bairro
   */
  neighborhood?: string;
  /**
   * Ponto de referência
   */
  reference?: string;
  /**
   * Código de Endereçamento Postal (CEP)
   */
  zip?: string;
  documents?: {
    /**
     * Cadastro de Pessoa Física
     */
    cpf?: string;
    /**
     * Registro Geral
     */
    rg?: string;
    /**
     * Cadastro Nacional de Pessoas Jurídicas
     */
    cnpj?: string;
    /**
     * Inscrição Estadual
     */
    ie?: string;
  }[];
}

            }
/** @description Associa um código de cupom ao carrinho */
 "POST /api/v2/carts/:cart_id/coupon_code": {
              searchParams:  {
  /**
   * Código do cupom
   */
  code?: string;
}

            }
/** @description Lista todos os channels usados nos pedidos criados */
 "GET /api/v2/orders/channels": {
              
            }
/** @description Lista todos os estados usados nos pedidos criados */
 "GET /api/v2/orders/states": {
              
            }
/** @description Retorna o preço do produto e das variantes */
 "GET /api/v2/products/:product_id/price": {
              
            }
/** @description Lista as imagens do produto */
 "GET /api/v2/products/:product_id/images": {
              
            }
/** @description Cria uma imagem do produto */
 "POST /api/v2/products/:product_id/images": {
              searchParams:  {
  file_url?: string;
  /**
   * IDs da variantes associadas a imagem
   */
  variant_ids?: number[];
}

            }
/** @description Deleta uma imagem do produto */
 "DELETE /api/v2/products/:product_id/images/:id": {
              
            }
/** @description Reordena as imagens do produto */
 "POST /api/v2/products/:product_id/images/reorder": {
              searchParams:  {
  ids?: number[];
}

            }
/** @description Associa a imagem com uma variante */
 "POST /api/v2/products/:product_id/images/:id/add_variant": {
              searchParams:  {
  variant_id?: number;
}

            }
/** @description Remove a associação da imagem com uma variante */
 "POST /api/v2/products/:product_id/images/:id/remove_variant": {
              searchParams:  {
  variant_id?: number;
}

            }
/** @description Retorna uma lista de pacotes de um pedido */
 "GET /api/v2/orders/:order_code/packages": {
              
            }
/** @description Indica para a API que dererminado evento aconteceu e que ela deve disparar as ações relacionadas */
 "POST /api/v2/events": {
              
            }
/** @description Permite a listagem de recebíveis (comissão) de um usuário vendedor da loja, quando ocorre split de pagamentos via Pagarme  */
 "GET /api/v2/users/:id/payables": {
              
            }
/** @description Retorna um produto pelo código identificador (`product_id`) */
 "GET /api/v2/products/:product_id": {
              
            }
/** @description Remove um produto do catálogo pelo código indentificador (`product_id`) */
 "DELETE /api/v2/products/:product_id": {
              
            }
/** @description Atualiza informações de um produto no catálogo pelo código identificador (`product_id`) */
 "PATCH /api/v2/products/:product_id": {
              searchParams: /**
 * Modelo simplificado de um produto para atualização e criação
 */
export interface SimpleProduct {
  /**
   * Código de Referência do produto
   */
  reference?: string;
  /**
   * Nome do produto
   */
  name?: string;
  /**
   * Descrição do produto
   */
  description?: string;
  /**
   * Indica se o produto está ativo (`true`) ou invativo (`false`)
   */
  active?: boolean;
  /**
   * Tags associadas ao produto
   */
  tag_list?: string;
  /**
   * Tipo de produto
   */
  product_type?:
    | {"0": "p"; "1": "r"; "2": "o"; "3": "d"; "4": "u"; "5": "c"; "6": "t"}
    | {"0": "s"; "1": "a"; "2": "m"; "3": "p"; "4": "l"; "5": "e"}
    | {
        "0": "s";
        "1": "u";
        "2": "b";
        "3": "s";
        "4": "c";
        "5": "r";
        "6": "i";
        "7": "p";
        "8": "t";
        "9": "i";
        "10": "o";
        "11": "n";
      };
}

            }
/** @description Recebe uma avaliação e recalcula a pontuação atual */
 "POST /api/v2/products/:product_id/rate": {
              
            }
/** @description Permite remover uma variante */
 "DELETE /api/v2/products/:product_id/variants/:variant_id": {
              
            }
/** @description Atualiza as informações de um variante */
 "PATCH /api/v2/products/:product_id/variants/:variant_id": {
              searchParams:  {
  sku?: string;
  name?: string;
  quantity?: number;
  main?: boolean;
  /**
   * Massa do produto, em gramas
   */
  weight?: number;
  /**
   * Largura do produto, em centímetros
   */
  width?: number;
  /**
   * Altura do produto, em centímetros
   */
  height?: number;
  /**
   * Comprimento do produito, em centímetros
   */
  length?: number;
  /**
   * Dias de manuseio da variante
   */
  handling_days?: number;
  price?: number;
  /**
   * Customização da variante
   */
  custom_attributes?: {};
  min_quantity?: number;
  norder?: number;
  property1?: {
    name?: string;
    value?: string;
    defining?: boolean;
  };
  property2?: {
    name?: string;
    value?: string;
    defining?: boolean;
  };
  property3?: {
    name?: string;
    value?: string;
    defining?: boolean;
  };
  barcode?: string;
  /**
   * Quantidade de itens vendidos
   */
  quantity_sold?: number;
}

            }
/** @description Deleta uma imagem do produto */
 "DELETE /api/v2/products/:product_id/images/:image_id": {
              
            }
/** @description Associa a imagem com uma variante */
 "POST /api/v2/products/:product_id/images/:image_id/add_variant": {
              searchParams:  {
  variant_id?: number;
}

            }
/** @description Remove a associação da imagem com uma variante */
 "POST /api/v2/products/:product_id/images/:image_id/remove_variant": {
              searchParams:  {
  variant_id?: number;
}

            }
/** @description Retorna as informações de um carrinho pelo seu `id` ou `token` */
 "GET /api/v2/carts/:cart_id": {
              
            }
/** @description Permite excluir um carrinho */
 "DELETE /api/v2/carts/:cart_id": {
              
            }
/** @description Permite atualizar os atributos de um carrinho */
 "PATCH /api/v2/carts/:cart_id": {
              searchParams: /**
 * Parâmetros criação e atualização de carrinho
 */
export interface ParametrosDeCarrinhoResumido {
  /**
   * Agente que criou o carrinho
   */
  agent?: string;
  /**
   * Código de Endereçamento Postal (CEP) do destinatário do pedido
   */
  zip?: string;
  /**
   * Código identificador `ID` do cliente
   */
  client_id?: number;
  /**
   * Código identificador `ID` do desconto do carrinho
   */
  coupon_code?: string;
  /**
   * @deprecated
   * Email do cliente
   */
  email?: string;
  /**
   * Token do desconto
   */
  rebate_token?: string;
}

            }
/** @description Remove um item do carrinho */
 "DELETE /api/v2/carts/:cart_id/items/:item_id": {
              
            }
/** @description Atualiza um item do carrinho */
 "PATCH /api/v2/carts/:cart_id/items/:item_id": {
              searchParams: /**
 * Modelo de carcaterística de produto para item no carrinho
 */
export interface Produto {
  /**
   * Código SKU da variante do produto
   */
  sku?: string;
  /**
   * Unidades do produto disponíveis fisicamente
   */
  quantity?: number;
  /**
   * Campo para registro de observações, chave ou valores necessários
   */
  extra?: {};
  /**
   * Código identificador do local do produto
   */
  place_id?: number;
  /**
   * Código de cupom
   */
  store_coupon_code?: string;
  /**
   * [Personalização](http://ajuda.vnda.com.br/pt-BR/articles/1763398-funcionalidades-produtos-personalizados) do produto
   */
  customizations?: {
    /**
     * [Personalização](http://ajuda.vnda.com.br/pt-BR/articles/1763398-funcionalidades-produtos-personalizados) incluídas no Admin da loja.
     * Se por exemplo a customização do produto é a cor, o parâmetro para a requisição deve ser `Color` ao invés de `CUstomization`.
     */
    Customization?: string;
  }[];
}

            }
/** @description Atualiza o método para o envio dos itens do carrinho */
 "PATCH /api/v2/carts/:cart_id/shipping_methods/:value_method": {
              searchParams: /**
 * Modelo que representa as formas de entrega na API
 */
export interface ShippingMethods {
  /**
   * Nome do tipo de entrega, como por exemplo Normal, Expressa e Agendada
   */
  name?: string;
  /**
   * Identificador do método de envio
   */
  value?: string;
  /**
   * Preço de envio
   */
  price?: number;
  /**
   * Descrição do tipo de envio e prazo
   */
  description?: string;
  /**
   * Número em dias do prazo de envio
   */
  delivery_days?: number;
  /**
   * Valor restante da compra para que o carrinho fique elegível para frete grátis
   */
  value_needed_to_discount?: number;
  /**
   * Código identificador `ID` do tipo de envio
   */
  shipping_method_id?: number;
  /**
   * Mensagem ou observação sobre a forma de envio
   */
  notice?: string;
  /**
   * Empresa responsável pelo envio
   */
  fulfillment_company?: string;
}

            }
/** @description Calculo os método de envio disponíveis para o carrinho */
 "GET /api/v2/carts/:cart_id/shipping_methods": {
              
            }
/** @description Calcula as parcelas de pagamento para valor total do carrinho */
 "GET /api/v2/carts/:cart_id/installments": {
              
            }
/** @description Retorna os dados de um pedido pelo `code` ou `token` do pedido */
 "GET /api/v2/orders/:order_code": {
              
            }
/** @description Atualiza o campo de dados extras de um pedido pelo `code` do pedido */
 "PATCH /api/v2/orders/:order_code": {
              searchParams:  {
  /**
   * Campo para registro de observações, chave ou valores necessários
   */
  extra?: {};
}

            }
/** @description Retorna a *timeline* de eventos ocorridos em um pedido */
 "GET /api/v2/orders/:order_code/events": {
              
            }
/** @description Retorna a avaliação que o cliente fez em um pedido */
 "GET /api/v2/orders/:order_code/reviews": {
              
            }
/** @description Retorna os descontos de um pedido pelo `code` ou `token` do pedido */
 "GET /api/v2/orders/:order_code/discounts": {
              
            }
/** @description Retorna o endereço de envio pelo `code` do pedido */
 "GET /api/v2/orders/:order_code/shipping_address": {
              
            }
/** @description Atualiza dados de endereço do pedido */
 "PATCH /api/v2/orders/:order_code/shipping_address": {
              searchParams: /**
 * Modelo de endereço de envio para carrinho e pedido
 */
export interface EnderecoDeEnvio {
  /**
   * Nome do cliente
   */
  first_name?: string;
  /**
   * Sobrenome do cliente
   */
  last_name?: string;
  /**
   * Nome da empresa (para clientes jurídicos)
   */
  company_name?: string;
  /**
   * Email do cliente
   */
  email?: string;
  /**
   * Código de Discagem Direta à Distância (DDD)
   */
  first_phone_area?: string;
  /**
   * Telefone do cliente
   */
  first_phone?: string;
  /**
   * Código de Discagem Direta à Distância (DDD)
   */
  second_phone_area?: string;
  /**
   * Telefone do cliente
   */
  second_phone?: string;
  /**
   * Nome do recebedor
   */
  recipient_name?: {
    [k: string]: unknown;
  };
  /**
   * Logradouro
   */
  street_name?: string;
  /**
   * Número
   */
  street_number?: string;
  /**
   * Complemento
   */
  complement?: string;
  /**
   * Bairro
   */
  neighborhood?: string;
  /**
   * Ponto de referência
   */
  reference?: string;
  /**
   * Código de Endereçamento Postal (CEP)
   */
  zip?: string;
  documents?: {
    /**
     * Cadastro de Pessoa Física
     */
    cpf?: string;
    /**
     * Registro Geral
     */
    rg?: string;
    /**
     * Cadastro Nacional de Pessoas Jurídicas
     */
    cnpj?: string;
    /**
     * Inscrição Estadual
     */
    ie?: string;
  }[];
}

            }
/** @description Captura o pagamento no adquirente para pedidos com pagamento por cartão de crédito. */
 "POST /api/v2/orders/:order_code/capture": {
              
            }
/** @description Confirma um pedido */
 "POST /api/v2/orders/:order_code/confirm": {
              searchParams:  {
  /**
   * Parâmetro para incluir o retorno [da requisição de captura do pagamento](https://developers.vnda.com.br/reference/post-api-v2-orders-capture).
   * Esse parâmetro é **obrigatório** para pedidos com pagamento por cartão de crédito.
   */
  confirmation_data?: string;
}

            }
/** @description Faz o estorno do pagamento no adquirente do cartão de crédito
Operação válida para pedidos pagos com cartão de crédito */
 "POST /api/v2/orders/:order_code/chargeback": {
              
            }
/** @description Altera o status do pedido para `cancelado` */
 "POST /api/v2/orders/:order_code/cancel": {
              searchParams:  {
  /**
   * Parâmetro para incluir uma confirmação de estorno de pagamento para o cliente.
   * Para pedidos com pagamento via cartão de crédito, é obrigatório que nesse campo seja incluído no parâmetro o retorno [da requisição de estorno de pagamento](https://developers.vnda.com.br/reference/post-api-v2-orders-order-code-chargeback).
   */
  cancelation_data?: string;
}

            }
/** @description Retorna os itens de um pedido pelo código do pedido */
 "GET /api/v2/orders/:order_code/items": {
              
            }
/** @description Lista as personalizações de um item do pedido pelos códigos do item e do pedido */
 "GET /api/v2/orders/:order_code/items/:item_id/customizations": {
              
            }
/** @description Retorna os pedidos de um cliente pelo seu `id_client` */
 "GET /api/v2/clients/:id_client/orders": {
              
            }
/** @description Retorna as notas fisicais de um pacote do pedido */
 "GET /api/v2/orders/:order_code/packages/:package_code/invoices": {
              
            }
/** @description Inclui nota fiscal no pacote de um pedido */
 "POST /api/v2/orders/:order_code/packages/:package_code/invoices": {
              searchParams: /**
 * Modelo que representa uma nota fiscal na API
 */
export interface Invoice {
  /**
   * Número da nota fiscal
   */
  number?: number;
  /**
   * Número de série da nota fiscal
   */
  series?: number;
  /**
   * Data e horário da criação da nota fiscal
   */
  issued_at?: string;
  /**
   * Chave da nota fiscal
   */
  key?: string;
  volumes?: number;
}

            }
/** @description Remove uma nota fiscal */
 "DELETE /api/v2/orders/:order_code/packages/:package_code/invoices/:number": {
              
            }
/** @description Atualiza uma nota fiscal */
 "PATCH /api/v2/orders/:order_code/packages/:package_code/invoices/:number": {
              searchParams: /**
 * Modelo que representa uma nota fiscal na API
 */
export interface Invoice {
  /**
   * Número da nota fiscal
   */
  number?: number;
  /**
   * Número de série da nota fiscal
   */
  series?: number;
  /**
   * Data e horário da criação da nota fiscal
   */
  issued_at?: string;
  /**
   * Chave da nota fiscal
   */
  key?: string;
  volumes?: number;
}

            }
/** @description Permite listar os pedidos pendentes do feed */
 "GET /api/feed/orders": {
              
            }
/** @description Permite marcar os pedidos para que eles sejam filtrados da listagem do feed */
 "POST /api/feed/orders": {
              searchParams:  {
  orders?: {
    /**
     * Código do pedido
     */
    code?: string;
  }[];
}

            }
}