// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/getPhoto.ts";
import * as $$$1 from "./loaders/listPhotos.ts";
import * as $$$2 from "./loaders/searchPhotos.ts";

const manifest = {
  "loaders": {
    "unsplash/loaders/getPhoto.ts": $$$0,
    "unsplash/loaders/listPhotos.ts": $$$1,
    "unsplash/loaders/searchPhotos.ts": $$$2,
  },
  "name": "unsplash",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
