// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/analyzeKeywordDifficulty.ts";
import * as $$$$$$$$$1 from "./actions/analyzeLocalSEO.ts";
import * as $$$$$$$$$2 from "./actions/compareDomainMetrics.ts";
import * as $$$$$$$$$3 from "./actions/generateSEOAudit.ts";
import * as $$$$$$$$$4 from "./actions/trackSERPFeatures.ts";
import * as $$$0 from "./loaders/backlinks/getAnchors.ts";
import * as $$$1 from "./loaders/backlinks/getBacklinks.ts";
import * as $$$2 from "./loaders/backlinks/getBacklinksOverview.ts";
import * as $$$3 from "./loaders/backlinks/getReferringDomains.ts";
import * as $$$4 from "./loaders/keywords/getAdsCompetition.ts";
import * as $$$5 from "./loaders/keywords/getRelatedKeywords.ts";
import * as $$$6 from "./loaders/keywords/getSearchVolume.ts";
import * as $$$7 from "./loaders/serp/getAdResults.ts";
import * as $$$8 from "./loaders/serp/getMapsResults.ts";
import * as $$$9 from "./loaders/serp/getOrganicResults.ts";
import * as $$$10 from "./loaders/traffic/getTrafficByCountry.ts";
import * as $$$11 from "./loaders/traffic/getTrafficByPages.ts";
import * as $$$12 from "./loaders/traffic/getTrafficBySources.ts";
import * as $$$13 from "./loaders/traffic/getTrafficOverview.ts";

const manifest = {
  "loaders": {
    "data-for-seo/loaders/backlinks/getAnchors.ts": $$$0,
    "data-for-seo/loaders/backlinks/getBacklinks.ts": $$$1,
    "data-for-seo/loaders/backlinks/getBacklinksOverview.ts": $$$2,
    "data-for-seo/loaders/backlinks/getReferringDomains.ts": $$$3,
    "data-for-seo/loaders/keywords/getAdsCompetition.ts": $$$4,
    "data-for-seo/loaders/keywords/getRelatedKeywords.ts": $$$5,
    "data-for-seo/loaders/keywords/getSearchVolume.ts": $$$6,
    "data-for-seo/loaders/serp/getAdResults.ts": $$$7,
    "data-for-seo/loaders/serp/getMapsResults.ts": $$$8,
    "data-for-seo/loaders/serp/getOrganicResults.ts": $$$9,
    "data-for-seo/loaders/traffic/getTrafficByCountry.ts": $$$10,
    "data-for-seo/loaders/traffic/getTrafficByPages.ts": $$$11,
    "data-for-seo/loaders/traffic/getTrafficBySources.ts": $$$12,
    "data-for-seo/loaders/traffic/getTrafficOverview.ts": $$$13,
  },
  "actions": {
    "data-for-seo/actions/analyzeKeywordDifficulty.ts": $$$$$$$$$0,
    "data-for-seo/actions/analyzeLocalSEO.ts": $$$$$$$$$1,
    "data-for-seo/actions/compareDomainMetrics.ts": $$$$$$$$$2,
    "data-for-seo/actions/generateSEOAudit.ts": $$$$$$$$$3,
    "data-for-seo/actions/trackSERPFeatures.ts": $$$$$$$$$4,
  },
  "name": "data-for-seo",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
