// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/analyzeKeywordDifficulty.ts";
import * as $$$$$$$$$1 from "./actions/analyzeLocalSEO.ts";
import * as $$$$$$$$$2 from "./actions/async/createAdsCompetitionTask.ts";
import * as $$$$$$$$$3 from "./actions/async/createAdsSerpTask.ts";
import * as $$$$$$$$$4 from "./actions/async/createMapsSerpTask.ts";
import * as $$$$$$$$$5 from "./actions/async/createOrganicSerpTask.ts";
import * as $$$$$$$$$6 from "./actions/async/createRelatedKeywordsTask.ts";
import * as $$$$$$$$$7 from "./actions/async/createSearchVolumeTask.ts";
import * as $$$$$$$$$8 from "./actions/compareDomainMetrics.ts";
import * as $$$$$$$$$9 from "./actions/createAdsCompetitionTask.ts";
import * as $$$$$$$$$10 from "./actions/generateSEOAudit.ts";
import * as $$$$$$$$$11 from "./actions/trackSERPFeatures.ts";
import * as $$$0 from "./loaders/async/getAdsCompetitionResult.ts";
import * as $$$1 from "./loaders/async/getMapsResultsResult.ts";
import * as $$$2 from "./loaders/async/getRelatedKeywordsResult.ts";
import * as $$$3 from "./loaders/async/getSearchVolumeResult.ts";
import * as $$$4 from "./loaders/backlinks/getAnchors.ts";
import * as $$$5 from "./loaders/backlinks/getBacklinks.ts";
import * as $$$6 from "./loaders/backlinks/getBacklinksOverview.ts";
import * as $$$7 from "./loaders/backlinks/getReferringDomains.ts";
import * as $$$8 from "./loaders/keywords/getAdsCompetition.ts";
import * as $$$9 from "./loaders/keywords/getRelatedKeywords.ts";
import * as $$$10 from "./loaders/keywords/getSearchVolume.ts";
import * as $$$11 from "./loaders/live/getBacklinks.ts";
import * as $$$12 from "./loaders/live/getBacklinksOverview.ts";
import * as $$$13 from "./loaders/live/getGoogleDatasetSearchLiveAdvanced.ts";
import * as $$$14 from "./loaders/live/getGoogleEventsLiveAdvanced.ts";
import * as $$$15 from "./loaders/live/getGoogleNewsLiveAdvanced.ts";
import * as $$$16 from "./loaders/live/getOrganicSerpLiveAdvanced.ts";
import * as $$$17 from "./loaders/live/getReferringDomains.ts";
import * as $$$18 from "./loaders/live/getTrafficByCountry.ts";
import * as $$$19 from "./loaders/live/getTrafficByPages.ts";
import * as $$$20 from "./loaders/live/getTrafficBySources.ts";
import * as $$$21 from "./loaders/live/getTrafficOverview.ts";
import * as $$$22 from "./loaders/serp/getAdResults.ts";
import * as $$$23 from "./loaders/serp/getMapsResults.ts";
import * as $$$24 from "./loaders/serp/getOrganicResults.ts";
import * as $$$25 from "./loaders/tasks/getTaskResultAdvanced.ts";
import * as $$$26 from "./loaders/tasks/getTaskResultHtml.ts";
import * as $$$27 from "./loaders/tasks/getTaskResultRegular.ts";
import * as $$$28 from "./loaders/tasks/getTasksFixed.ts";
import * as $$$29 from "./loaders/tasks/getTasksReady.ts";
import * as $$$30 from "./loaders/traffic/getTrafficByCountry.ts";
import * as $$$31 from "./loaders/traffic/getTrafficByPages.ts";
import * as $$$32 from "./loaders/traffic/getTrafficBySources.ts";
import * as $$$33 from "./loaders/traffic/getTrafficOverview.ts";

const manifest = {
  "loaders": {
    "data-for-seo/loaders/async/getAdsCompetitionResult.ts": $$$0,
    "data-for-seo/loaders/async/getMapsResultsResult.ts": $$$1,
    "data-for-seo/loaders/async/getRelatedKeywordsResult.ts": $$$2,
    "data-for-seo/loaders/async/getSearchVolumeResult.ts": $$$3,
    "data-for-seo/loaders/backlinks/getAnchors.ts": $$$4,
    "data-for-seo/loaders/backlinks/getBacklinks.ts": $$$5,
    "data-for-seo/loaders/backlinks/getBacklinksOverview.ts": $$$6,
    "data-for-seo/loaders/backlinks/getReferringDomains.ts": $$$7,
    "data-for-seo/loaders/keywords/getAdsCompetition.ts": $$$8,
    "data-for-seo/loaders/keywords/getRelatedKeywords.ts": $$$9,
    "data-for-seo/loaders/keywords/getSearchVolume.ts": $$$10,
    "data-for-seo/loaders/live/getBacklinks.ts": $$$11,
    "data-for-seo/loaders/live/getBacklinksOverview.ts": $$$12,
    "data-for-seo/loaders/live/getGoogleDatasetSearchLiveAdvanced.ts": $$$13,
    "data-for-seo/loaders/live/getGoogleEventsLiveAdvanced.ts": $$$14,
    "data-for-seo/loaders/live/getGoogleNewsLiveAdvanced.ts": $$$15,
    "data-for-seo/loaders/live/getOrganicSerpLiveAdvanced.ts": $$$16,
    "data-for-seo/loaders/live/getReferringDomains.ts": $$$17,
    "data-for-seo/loaders/live/getTrafficByCountry.ts": $$$18,
    "data-for-seo/loaders/live/getTrafficByPages.ts": $$$19,
    "data-for-seo/loaders/live/getTrafficBySources.ts": $$$20,
    "data-for-seo/loaders/live/getTrafficOverview.ts": $$$21,
    "data-for-seo/loaders/serp/getAdResults.ts": $$$22,
    "data-for-seo/loaders/serp/getMapsResults.ts": $$$23,
    "data-for-seo/loaders/serp/getOrganicResults.ts": $$$24,
    "data-for-seo/loaders/tasks/getTaskResultAdvanced.ts": $$$25,
    "data-for-seo/loaders/tasks/getTaskResultHtml.ts": $$$26,
    "data-for-seo/loaders/tasks/getTaskResultRegular.ts": $$$27,
    "data-for-seo/loaders/tasks/getTasksFixed.ts": $$$28,
    "data-for-seo/loaders/tasks/getTasksReady.ts": $$$29,
    "data-for-seo/loaders/traffic/getTrafficByCountry.ts": $$$30,
    "data-for-seo/loaders/traffic/getTrafficByPages.ts": $$$31,
    "data-for-seo/loaders/traffic/getTrafficBySources.ts": $$$32,
    "data-for-seo/loaders/traffic/getTrafficOverview.ts": $$$33,
  },
  "actions": {
    "data-for-seo/actions/analyzeKeywordDifficulty.ts": $$$$$$$$$0,
    "data-for-seo/actions/analyzeLocalSEO.ts": $$$$$$$$$1,
    "data-for-seo/actions/async/createAdsCompetitionTask.ts": $$$$$$$$$2,
    "data-for-seo/actions/async/createAdsSerpTask.ts": $$$$$$$$$3,
    "data-for-seo/actions/async/createMapsSerpTask.ts": $$$$$$$$$4,
    "data-for-seo/actions/async/createOrganicSerpTask.ts": $$$$$$$$$5,
    "data-for-seo/actions/async/createRelatedKeywordsTask.ts": $$$$$$$$$6,
    "data-for-seo/actions/async/createSearchVolumeTask.ts": $$$$$$$$$7,
    "data-for-seo/actions/compareDomainMetrics.ts": $$$$$$$$$8,
    "data-for-seo/actions/createAdsCompetitionTask.ts": $$$$$$$$$9,
    "data-for-seo/actions/generateSEOAudit.ts": $$$$$$$$$10,
    "data-for-seo/actions/trackSERPFeatures.ts": $$$$$$$$$11,
  },
  "name": "data-for-seo",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
