// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/async/createAdsCompetitionTask.ts";
import * as $$$$$$$$$1 from "./actions/async/createAdsSerpTask.ts";
import * as $$$$$$$$$2 from "./actions/async/createMapsSerpTask.ts";
import * as $$$$$$$$$3 from "./actions/async/createOrganicSerpTask.ts";
import * as $$$$$$$$$4 from "./actions/async/createRelatedKeywordsTask.ts";
import * as $$$$$$$$$5 from "./actions/async/createSearchVolumeTask.ts";
import * as $$$$$$$$$6 from "./actions/createAdsCompetitionTask.ts";
import * as $$$0 from "./loaders/async/getAdsCompetitionResult.ts";
import * as $$$1 from "./loaders/async/getMapsResultsResult.ts";
import * as $$$2 from "./loaders/async/getRelatedKeywordsResult.ts";
import * as $$$3 from "./loaders/async/getSearchVolumeResult.ts";
import * as $$$4 from "./loaders/live/getBacklinks.ts";
import * as $$$5 from "./loaders/live/getBacklinksOverview.ts";
import * as $$$6 from "./loaders/live/getOrganicSerpLiveAdvanced.ts";
import * as $$$7 from "./loaders/live/getReferringDomains.ts";
import * as $$$8 from "./loaders/live/getTrafficByCountry.ts";
import * as $$$9 from "./loaders/live/getTrafficByPages.ts";
import * as $$$10 from "./loaders/live/getTrafficBySources.ts";
import * as $$$11 from "./loaders/live/getTrafficOverview.ts";

const manifest = {
  "loaders": {
    "data-for-seo/loaders/async/getAdsCompetitionResult.ts": $$$0,
    "data-for-seo/loaders/async/getMapsResultsResult.ts": $$$1,
    "data-for-seo/loaders/async/getRelatedKeywordsResult.ts": $$$2,
    "data-for-seo/loaders/async/getSearchVolumeResult.ts": $$$3,
    "data-for-seo/loaders/live/getBacklinks.ts": $$$4,
    "data-for-seo/loaders/live/getBacklinksOverview.ts": $$$5,
    "data-for-seo/loaders/live/getOrganicSerpLiveAdvanced.ts": $$$6,
    "data-for-seo/loaders/live/getReferringDomains.ts": $$$7,
    "data-for-seo/loaders/live/getTrafficByCountry.ts": $$$8,
    "data-for-seo/loaders/live/getTrafficByPages.ts": $$$9,
    "data-for-seo/loaders/live/getTrafficBySources.ts": $$$10,
    "data-for-seo/loaders/live/getTrafficOverview.ts": $$$11,
  },
  "actions": {
    "data-for-seo/actions/async/createAdsCompetitionTask.ts": $$$$$$$$$0,
    "data-for-seo/actions/async/createAdsSerpTask.ts": $$$$$$$$$1,
    "data-for-seo/actions/async/createMapsSerpTask.ts": $$$$$$$$$2,
    "data-for-seo/actions/async/createOrganicSerpTask.ts": $$$$$$$$$3,
    "data-for-seo/actions/async/createRelatedKeywordsTask.ts": $$$$$$$$$4,
    "data-for-seo/actions/async/createSearchVolumeTask.ts": $$$$$$$$$5,
    "data-for-seo/actions/createAdsCompetitionTask.ts": $$$$$$$$$6,
  },
  "name": "data-for-seo",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
