// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/messages/post.ts";
import * as $$$$$$$$$1 from "./actions/messages/react.ts";
import * as $$$$$$$$$2 from "./actions/messages/threads/reply.ts";
import * as $$$$$$$$$3 from "./actions/webhook/broker.ts";
import * as $$$0 from "./loaders/channels.ts";
import * as $$$1 from "./loaders/channels/history.ts";
import * as $$$2 from "./loaders/thread/replies.ts";
import * as $$$3 from "./loaders/user/profile.ts";
import * as $$$4 from "./loaders/users.ts";

const manifest = {
  "loaders": {
    "slack/loaders/channels.ts": $$$0,
    "slack/loaders/channels/history.ts": $$$1,
    "slack/loaders/thread/replies.ts": $$$2,
    "slack/loaders/user/profile.ts": $$$3,
    "slack/loaders/users.ts": $$$4,
  },
  "actions": {
    "slack/actions/messages/post.ts": $$$$$$$$$0,
    "slack/actions/messages/react.ts": $$$$$$$$$1,
    "slack/actions/messages/threads/reply.ts": $$$$$$$$$2,
    "slack/actions/webhook/broker.ts": $$$$$$$$$3,
  },
  "name": "slack",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
