// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/sendBasicEvent.ts";
import * as $$$$$$$$$1 from "./actions/sendEcommerceEvent.ts";
import * as $$$$$$$$$2 from "./actions/sendEvent.ts";
import * as $$$$$$$$$3 from "./actions/testConnection.ts";
import * as $$$$$$$$$4 from "./actions/trackEcommerceEvent.ts";
import * as $$$$$$$$$5 from "./actions/trackPageView.ts";
import * as $$$0 from "./loaders/analyticsScript.ts";
import * as $$$1 from "./loaders/getStapeConfig.ts";
import * as $$$$$$0 from "./sections/Analytics/Stape.tsx";
import * as $$$$$$1 from "./sections/StapeTracker.tsx";

const manifest = {
  "loaders": {
    "stape/loaders/analyticsScript.ts": $$$0,
    "stape/loaders/getStapeConfig.ts": $$$1,
  },
  "sections": {
    "stape/sections/Analytics/Stape.tsx": $$$$$$0,
    "stape/sections/StapeTracker.tsx": $$$$$$1,
  },
  "actions": {
    "stape/actions/sendBasicEvent.ts": $$$$$$$$$0,
    "stape/actions/sendEcommerceEvent.ts": $$$$$$$$$1,
    "stape/actions/sendEvent.ts": $$$$$$$$$2,
    "stape/actions/testConnection.ts": $$$$$$$$$3,
    "stape/actions/trackEcommerceEvent.ts": $$$$$$$$$4,
    "stape/actions/trackPageView.ts": $$$$$$$$$5,
  },
  "name": "stape",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
