// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/cart.ts";
import * as $$$1 from "./loaders/product/productDetailsPage.ts";
import * as $$$2 from "./loaders/product/productList.ts";
import * as $$$3 from "./loaders/product/productListingPage.ts";
import * as $$$4 from "./loaders/product/suggestions.ts";
import * as $$$$$$$$$0 from "./actions/cart/addCoupon.ts";
import * as $$$$$$$$$1 from "./actions/cart/addItems.ts";
import * as $$$$$$$$$2 from "./actions/cart/removeCoupon.ts";
import * as $$$$$$$$$3 from "./actions/cart/removeItem.ts";
import * as $$$$$$$$$4 from "./actions/cart/updateItem.ts";

const manifest = {
  "loaders": {
    "salesforce/loaders/cart.ts": $$$0,
    "salesforce/loaders/product/productDetailsPage.ts": $$$1,
    "salesforce/loaders/product/productList.ts": $$$2,
    "salesforce/loaders/product/productListingPage.ts": $$$3,
    "salesforce/loaders/product/suggestions.ts": $$$4,
  },
  "actions": {
    "salesforce/actions/cart/addCoupon.ts": $$$$$$$$$0,
    "salesforce/actions/cart/addItems.ts": $$$$$$$$$1,
    "salesforce/actions/cart/removeCoupon.ts": $$$$$$$$$2,
    "salesforce/actions/cart/removeItem.ts": $$$$$$$$$3,
    "salesforce/actions/cart/updateItem.ts": $$$$$$$$$4,
  },
  "name": "salesforce",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
