// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/getComponents.ts";
import * as $$$1 from "./loaders/getImagesToFills.ts";
import * as $$$2 from "./loaders/getNodes.ts";
import * as $$$3 from "./loaders/getSimplifiedNodes.ts";
import * as $$$4 from "./loaders/getSpecificnNodeimage.ts";
import * as $$$5 from "./loaders/simplified.ts";

const manifest = {
  "loaders": {
    "figma/loaders/getComponents.ts": $$$0,
    "figma/loaders/getImagesToFills.ts": $$$1,
    "figma/loaders/getNodes.ts": $$$2,
    "figma/loaders/getSimplifiedNodes.ts": $$$3,
    "figma/loaders/getSpecificnNodeimage.ts": $$$4,
    "figma/loaders/simplified.ts": $$$5,
  },
  "name": "figma",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
