// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/appendBlockChildren.ts";
import * as $$$$$$$$$1 from "./actions/createComment.ts";
import * as $$$$$$$$$2 from "./actions/createDatabase.ts";
import * as $$$$$$$$$3 from "./actions/createPage.ts";
import * as $$$$$$$$$4 from "./actions/myAction.ts";
import * as $$$$$$$$$5 from "./actions/updateDatabase.ts";
import * as $$$$$$$$$6 from "./actions/updatePage.ts";
import * as $$$0 from "./loaders/getBlockChildren.ts";
import * as $$$1 from "./loaders/getDatabase.ts";
import * as $$$2 from "./loaders/getPage.ts";
import * as $$$3 from "./loaders/getUsers.ts";
import * as $$$4 from "./loaders/myLoader.ts";
import * as $$$5 from "./loaders/queryDatabase.ts";
import * as $$$6 from "./loaders/searchPages.ts";

const manifest = {
  "loaders": {
    "notion/loaders/getBlockChildren.ts": $$$0,
    "notion/loaders/getDatabase.ts": $$$1,
    "notion/loaders/getPage.ts": $$$2,
    "notion/loaders/getUsers.ts": $$$3,
    "notion/loaders/myLoader.ts": $$$4,
    "notion/loaders/queryDatabase.ts": $$$5,
    "notion/loaders/searchPages.ts": $$$6,
  },
  "actions": {
    "notion/actions/appendBlockChildren.ts": $$$$$$$$$0,
    "notion/actions/createComment.ts": $$$$$$$$$1,
    "notion/actions/createDatabase.ts": $$$$$$$$$2,
    "notion/actions/createPage.ts": $$$$$$$$$3,
    "notion/actions/myAction.ts": $$$$$$$$$4,
    "notion/actions/updateDatabase.ts": $$$$$$$$$5,
    "notion/actions/updatePage.ts": $$$$$$$$$6,
  },
  "name": "notion",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
