// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/extensions/product/detailsPage.ts";
import * as $$$1 from "./loaders/extensions/product/listingPage.ts";
import * as $$$2 from "./loaders/extensions/product/list.ts";
import * as $$$3 from "./loaders/navbar.ts";
import * as $$$$$$0 from "./sections/Seo/SeoPLP.tsx";
import * as $$$$$$1 from "./sections/Seo/SeoPDP.tsx";

const manifest = {
  "loaders": {
    "commerce/loaders/extensions/productDetailsPage.ts": $$$0,
    "commerce/loaders/extensions/productListingPage.ts": $$$1,
    "commerce/loaders/extensions/products.ts": $$$2,
    "commerce/loaders/navbar.ts": $$$3,
  },
  "sections": {
    "commerce/sections/Seo/SeoPDP.tsx": $$$$$$1,
    "commerce/sections/Seo/SeoPLP.tsx": $$$$$$0,
  },
  "name": "commerce",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
