// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/extensions/productDetailsPage.ts";
import * as $$$1 from "./loaders/extensions/productListingPage.ts";
import * as $$$2 from "./loaders/extensions/products.ts";
import * as $$$3 from "./loaders/navbar.ts";
import * as $$$4 from "./loaders/product/extensions/detailsPage.ts";
import * as $$$5 from "./loaders/product/extensions/list.ts";
import * as $$$6 from "./loaders/product/extensions/listingPage.ts";
import * as $$$7 from "./loaders/product/extensions/suggestions.ts";
import * as $$$8 from "./loaders/product/productListingPage.ts";
import * as $$$9 from "./loaders/product/products.ts";
import * as $$$$$$0 from "./sections/Seo/SeoPDP.tsx";
import * as $$$$$$1 from "./sections/Seo/SeoPDPV2.tsx";
import * as $$$$$$2 from "./sections/Seo/SeoPLP.tsx";
import * as $$$$$$3 from "./sections/Seo/SeoPLPV2.tsx";

const manifest = {
  "loaders": {
    "commerce/loaders/extensions/productDetailsPage.ts": $$$0,
    "commerce/loaders/extensions/productListingPage.ts": $$$1,
    "commerce/loaders/extensions/products.ts": $$$2,
    "commerce/loaders/navbar.ts": $$$3,
    "commerce/loaders/product/extensions/detailsPage.ts": $$$4,
    "commerce/loaders/product/extensions/list.ts": $$$5,
    "commerce/loaders/product/extensions/listingPage.ts": $$$6,
    "commerce/loaders/product/extensions/suggestions.ts": $$$7,
    "commerce/loaders/product/productListingPage.ts": $$$8,
    "commerce/loaders/product/products.ts": $$$9,
  },
  "sections": {
    "commerce/sections/Seo/SeoPDP.tsx": $$$$$$0,
    "commerce/sections/Seo/SeoPDPV2.tsx": $$$$$$1,
    "commerce/sections/Seo/SeoPLP.tsx": $$$$$$2,
    "commerce/sections/Seo/SeoPLPV2.tsx": $$$$$$3,
  },
  "name": "commerce",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
