
// deno-fmt-ignore-file
// deno-lint-ignore-file no-explicit-any ban-types ban-unused-ignore
//
// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// To generate this file: deno task start
//        


export interface OpenAPI {
/**
 * Get Product Rating
 */
"GET /reviews-and-ratings/api/rating/:inProductGroupWithId": {
response: {
average?: number
totalCount?: number
}
}
/**
 * Get List Reviews
 */
"GET /reviews-and-ratings/api/reviews": {
response: {
data?: {
id?: string
cacheId?: number
productId?: string
rating?: number
title?: string
text?: string
reviewerName?: string
shopperId?: string
reviewDateTime?: string
verifiedPurchaser?: boolean
sku?: null
approved?: boolean
location?: null
}[]
range?: {
total?: number
from?: number
to?: number
}
}
}
}
