// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/cart/addItem.ts";
import * as $$$$$$$$$1 from "./actions/cart/addItems.ts";
import * as $$$$$$$$$2 from "./actions/cart/simulation.ts";
import * as $$$$$$$$$3 from "./actions/cart/updateCart.ts";
import * as $$$$$$$$$4 from "./actions/cart/updateItem.ts";
import * as $$$$$$$$$5 from "./actions/notifyme.ts";
import * as $$$$$$$$$6 from "./actions/products/createProduct.ts";
import * as $$$$$$$$$7 from "./actions/products/deleteProduct.ts";
import * as $$$$$$$$$8 from "./actions/products/getProduct.ts";
import * as $$$$$$$$$9 from "./actions/products/images/createImage.ts";
import * as $$$$$$$$$10 from "./actions/products/listProducts.ts";
import * as $$$$$$$$$11 from "./actions/products/rateProduct.ts";
import * as $$$$$$$$$12 from "./actions/products/searchProducts.ts";
import * as $$$$$$$$$13 from "./actions/products/updateProduct.ts";
import * as $$$$$$$$$14 from "./actions/products/updateProductByReference.ts";
import * as $$$$$$$$$15 from "./actions/products/variants/createVariant.ts";
import * as $$$$$$$$$16 from "./actions/products/variants/deleteVariant.ts";
import * as $$$$$$$$$17 from "./actions/products/variants/listVariants.ts";
import * as $$$$0 from "./handlers/sitemap.ts";
import * as $$$0 from "./loaders/cart.ts";
import * as $$$1 from "./loaders/extensions/price/list.ts";
import * as $$$2 from "./loaders/extensions/price/listingPage.ts";
import * as $$$3 from "./loaders/productDetailsPage.ts";
import * as $$$4 from "./loaders/productDetailsPageVideo.ts";
import * as $$$5 from "./loaders/productList.ts";
import * as $$$6 from "./loaders/productListingPage.ts";
import * as $$$7 from "./loaders/proxy.ts";

const manifest = {
  "loaders": {
    "vnda/loaders/cart.ts": $$$0,
    "vnda/loaders/extensions/price/list.ts": $$$1,
    "vnda/loaders/extensions/price/listingPage.ts": $$$2,
    "vnda/loaders/productDetailsPage.ts": $$$3,
    "vnda/loaders/productDetailsPageVideo.ts": $$$4,
    "vnda/loaders/productList.ts": $$$5,
    "vnda/loaders/productListingPage.ts": $$$6,
    "vnda/loaders/proxy.ts": $$$7,
  },
  "handlers": {
    "vnda/handlers/sitemap.ts": $$$$0,
  },
  "actions": {
    "vnda/actions/cart/addItem.ts": $$$$$$$$$0,
    "vnda/actions/cart/addItems.ts": $$$$$$$$$1,
    "vnda/actions/cart/simulation.ts": $$$$$$$$$2,
    "vnda/actions/cart/updateCart.ts": $$$$$$$$$3,
    "vnda/actions/cart/updateItem.ts": $$$$$$$$$4,
    "vnda/actions/notifyme.ts": $$$$$$$$$5,
    "vnda/actions/products/createProduct.ts": $$$$$$$$$6,
    "vnda/actions/products/deleteProduct.ts": $$$$$$$$$7,
    "vnda/actions/products/getProduct.ts": $$$$$$$$$8,
    "vnda/actions/products/images/createImage.ts": $$$$$$$$$9,
    "vnda/actions/products/listProducts.ts": $$$$$$$$$10,
    "vnda/actions/products/rateProduct.ts": $$$$$$$$$11,
    "vnda/actions/products/searchProducts.ts": $$$$$$$$$12,
    "vnda/actions/products/updateProduct.ts": $$$$$$$$$13,
    "vnda/actions/products/updateProductByReference.ts": $$$$$$$$$14,
    "vnda/actions/products/variants/createVariant.ts": $$$$$$$$$15,
    "vnda/actions/products/variants/deleteVariant.ts": $$$$$$$$$16,
    "vnda/actions/products/variants/listVariants.ts": $$$$$$$$$17,
  },
  "name": "vnda",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
