// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/editImage.ts";
import * as $$$$$$$$$1 from "./actions/generateImage.ts";
import * as $$$0 from "./loaders/vision.ts";

const manifest = {
  "loaders": {
    "openai-mcp/loaders/vision.ts": $$$0,
  },
  "actions": {
    "openai-mcp/actions/editImage.ts": $$$$$$$$$0,
    "openai-mcp/actions/generateImage.ts": $$$$$$$$$1,
  },
  "name": "openai-mcp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
