// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$0 from "./sections/pageView.tsx";
import * as $$$$$$1 from "./sections/smartHintTracking.tsx";

const manifest = {
  "sections": {
    "smarthint/sections/pageView.tsx": $$$$$$0,
    "smarthint/sections/smartHintTracking.tsx": $$$$$$1,
  },
  "name": "smarthint",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
