// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createBudget.ts";
import * as $$$$$$$$$1 from "./actions/deleteBudget.ts";
import * as $$$$$$$$$2 from "./actions/exportCostData.ts";
import * as $$$$$$$$$3 from "./actions/updateBudget.ts";
import * as $$$0 from "./loaders/anomalies.ts";
import * as $$$1 from "./loaders/budgets.ts";
import * as $$$2 from "./loaders/costAndUsage.ts";
import * as $$$3 from "./loaders/costBreakdown.ts";
import * as $$$4 from "./loaders/costForecast.ts";
import * as $$$5 from "./loaders/reservationCoverage.ts";
import * as $$$6 from "./loaders/savingsPlans.ts";
import * as $$$7 from "./loaders/services.ts";

const manifest = {
  "loaders": {
    "aws/loaders/anomalies.ts": $$$0,
    "aws/loaders/budgets.ts": $$$1,
    "aws/loaders/costAndUsage.ts": $$$2,
    "aws/loaders/costBreakdown.ts": $$$3,
    "aws/loaders/costForecast.ts": $$$4,
    "aws/loaders/reservationCoverage.ts": $$$5,
    "aws/loaders/savingsPlans.ts": $$$6,
    "aws/loaders/services.ts": $$$7,
  },
  "actions": {
    "aws/actions/createBudget.ts": $$$$$$$$$0,
    "aws/actions/deleteBudget.ts": $$$$$$$$$1,
    "aws/actions/exportCostData.ts": $$$$$$$$$2,
    "aws/actions/updateBudget.ts": $$$$$$$$$3,
  },
  "name": "aws",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
