// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/addReaction.ts";
import * as $$$$$$$$$1 from "./actions/addRole.ts";
import * as $$$$$$$$$2 from "./actions/banMember.ts";
import * as $$$$$$$$$3 from "./actions/createChannel.ts";
import * as $$$$$$$$$4 from "./actions/createInvite.ts";
import * as $$$$$$$$$5 from "./actions/createRole.ts";
import * as $$$$$$$$$6 from "./actions/createSlashCommand.ts";
import * as $$$$$$$$$7 from "./actions/createWebhook.ts";
import * as $$$$$$$$$8 from "./actions/deleteChannel.ts";
import * as $$$$$$$$$9 from "./actions/deleteMessage.ts";
import * as $$$$$$$$$10 from "./actions/deleteRole.ts";
import * as $$$$$$$$$11 from "./actions/deleteWebhook.ts";
import * as $$$$$$$$$12 from "./actions/editChannel.ts";
import * as $$$$$$$$$13 from "./actions/editGuild.ts";
import * as $$$$$$$$$14 from "./actions/editMessage.ts";
import * as $$$$$$$$$15 from "./actions/editRole.ts";
import * as $$$$$$$$$16 from "./actions/editWebhook.ts";
import * as $$$$$$$$$17 from "./actions/executeWebhook.ts";
import * as $$$$$$$$$18 from "./actions/kickMember.ts";
import * as $$$$$$$$$19 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$20 from "./actions/oauth/reauthorize.ts";
import * as $$$$$$$$$21 from "./actions/pinMessage.ts";
import * as $$$$$$$$$22 from "./actions/removeReaction.ts";
import * as $$$$$$$$$23 from "./actions/removeRole.ts";
import * as $$$$$$$$$24 from "./actions/sendMessage.ts";
import * as $$$$$$$$$25 from "./actions/setChannelPermissions.ts";
import * as $$$$$$$$$26 from "./actions/timeoutMember.ts";
import * as $$$$$$$$$27 from "./actions/uploadFile.ts";
import * as $$$0 from "./loaders/getChannel.ts";
import * as $$$1 from "./loaders/getChannelMessages.ts";
import * as $$$2 from "./loaders/getCurrentUser.ts";
import * as $$$3 from "./loaders/getGuild.ts";
import * as $$$4 from "./loaders/getGuildChannels.ts";
import * as $$$5 from "./loaders/getGuildMembers.ts";
import * as $$$6 from "./loaders/getGuildRoles.ts";
import * as $$$7 from "./loaders/getMessage.ts";
import * as $$$8 from "./loaders/getMessageHistory.ts";
import * as $$$9 from "./loaders/getMessageReactions.ts";
import * as $$$10 from "./loaders/getUser.ts";
import * as $$$11 from "./loaders/getUserGuilds.ts";
import * as $$$12 from "./loaders/listGuilds.ts";
import * as $$$13 from "./loaders/listWebhooks.ts";
import * as $$$14 from "./loaders/oauth/start.ts";
import * as $$$15 from "./loaders/oauth/whoami.ts";
import * as $$$16 from "./loaders/searchMessages.ts";

const manifest = {
  "loaders": {
    "discord/loaders/getChannel.ts": $$$0,
    "discord/loaders/getChannelMessages.ts": $$$1,
    "discord/loaders/getCurrentUser.ts": $$$2,
    "discord/loaders/getGuild.ts": $$$3,
    "discord/loaders/getGuildChannels.ts": $$$4,
    "discord/loaders/getGuildMembers.ts": $$$5,
    "discord/loaders/getGuildRoles.ts": $$$6,
    "discord/loaders/getMessage.ts": $$$7,
    "discord/loaders/getMessageHistory.ts": $$$8,
    "discord/loaders/getMessageReactions.ts": $$$9,
    "discord/loaders/getUser.ts": $$$10,
    "discord/loaders/getUserGuilds.ts": $$$11,
    "discord/loaders/listGuilds.ts": $$$12,
    "discord/loaders/listWebhooks.ts": $$$13,
    "discord/loaders/oauth/start.ts": $$$14,
    "discord/loaders/oauth/whoami.ts": $$$15,
    "discord/loaders/searchMessages.ts": $$$16,
  },
  "actions": {
    "discord/actions/addReaction.ts": $$$$$$$$$0,
    "discord/actions/addRole.ts": $$$$$$$$$1,
    "discord/actions/banMember.ts": $$$$$$$$$2,
    "discord/actions/createChannel.ts": $$$$$$$$$3,
    "discord/actions/createInvite.ts": $$$$$$$$$4,
    "discord/actions/createRole.ts": $$$$$$$$$5,
    "discord/actions/createSlashCommand.ts": $$$$$$$$$6,
    "discord/actions/createWebhook.ts": $$$$$$$$$7,
    "discord/actions/deleteChannel.ts": $$$$$$$$$8,
    "discord/actions/deleteMessage.ts": $$$$$$$$$9,
    "discord/actions/deleteRole.ts": $$$$$$$$$10,
    "discord/actions/deleteWebhook.ts": $$$$$$$$$11,
    "discord/actions/editChannel.ts": $$$$$$$$$12,
    "discord/actions/editGuild.ts": $$$$$$$$$13,
    "discord/actions/editMessage.ts": $$$$$$$$$14,
    "discord/actions/editRole.ts": $$$$$$$$$15,
    "discord/actions/editWebhook.ts": $$$$$$$$$16,
    "discord/actions/executeWebhook.ts": $$$$$$$$$17,
    "discord/actions/kickMember.ts": $$$$$$$$$18,
    "discord/actions/oauth/callback.ts": $$$$$$$$$19,
    "discord/actions/oauth/reauthorize.ts": $$$$$$$$$20,
    "discord/actions/pinMessage.ts": $$$$$$$$$21,
    "discord/actions/removeReaction.ts": $$$$$$$$$22,
    "discord/actions/removeRole.ts": $$$$$$$$$23,
    "discord/actions/sendMessage.ts": $$$$$$$$$24,
    "discord/actions/setChannelPermissions.ts": $$$$$$$$$25,
    "discord/actions/timeoutMember.ts": $$$$$$$$$26,
    "discord/actions/uploadFile.ts": $$$$$$$$$27,
  },
  "name": "discord",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
