// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/contas-pagar/criar.ts";
import * as $$$$$$$$$1 from "./actions/contas-receber/atualizar.ts";
import * as $$$$$$$$$2 from "./actions/contas-receber/baixar.ts";
import * as $$$$$$$$$3 from "./actions/contas-receber/criar.ts";
import * as $$$$$$$$$4 from "./actions/contatos/atualizar.ts";
import * as $$$$$$$$$5 from "./actions/contatos/criar.ts";
import * as $$$$$$$$$6 from "./actions/contatos/pessoas/atualizar.ts";
import * as $$$$$$$$$7 from "./actions/contatos/pessoas/criar.ts";
import * as $$$$$$$$$8 from "./actions/contatos/pessoas/excluir.ts";
import * as $$$$$$$$$9 from "./actions/estoque/atualizar.ts";
import * as $$$$$$$$$10 from "./actions/expedicao/adicionar-origens.ts";
import * as $$$$$$$$$11 from "./actions/expedicao/alterar-expedicao.ts";
import * as $$$$$$$$$12 from "./actions/expedicao/concluir.ts";
import * as $$$$$$$$$13 from "./actions/expedicao/criar.ts";
import * as $$$$$$$$$14 from "./actions/marcas/atualizar.ts";
import * as $$$$$$$$$15 from "./actions/marcas/criar.ts";
import * as $$$$$$$$$16 from "./actions/notas/atualizar-marcadores.ts";
import * as $$$$$$$$$17 from "./actions/notas/criar-marcador.ts";
import * as $$$$$$$$$18 from "./actions/notas/emitir.ts";
import * as $$$$$$$$$19 from "./actions/notas/excluir-marcadores.ts";
import * as $$$$$$$$$20 from "./actions/notas/incluir-xml.ts";
import * as $$$$$$$$$21 from "./actions/notas/lancar-contas.ts";
import * as $$$$$$$$$22 from "./actions/notas/lancar-estoque.ts";
import * as $$$$$$$$$23 from "./actions/ordem-compra/atualizar-situacao.ts";
import * as $$$$$$$$$24 from "./actions/ordem-compra/atualizar.ts";
import * as $$$$$$$$$25 from "./actions/ordem-compra/criar.ts";
import * as $$$$$$$$$26 from "./actions/ordem-compra/lancar-contas.ts";
import * as $$$$$$$$$27 from "./actions/ordem-compra/lancar-estoque.ts";
import * as $$$$$$$$$28 from "./actions/ordem-servico/atualizar-situacao.ts";
import * as $$$$$$$$$29 from "./actions/ordem-servico/atualizar.ts";
import * as $$$$$$$$$30 from "./actions/ordem-servico/criar.ts";
import * as $$$$$$$$$31 from "./actions/ordem-servico/gerar-nota-fiscal.ts";
import * as $$$$$$$$$32 from "./actions/ordem-servico/lancar-contas.ts";
import * as $$$$$$$$$33 from "./actions/ordem-servico/lancar-estoque.ts";
import * as $$$$$$$$$34 from "./actions/pedidos/atualizar-despacho.ts";
import * as $$$$$$$$$35 from "./actions/pedidos/atualizar-situacao.ts";
import * as $$$$$$$$$36 from "./actions/pedidos/atualizar.ts";
import * as $$$$$$$$$37 from "./actions/pedidos/criar.ts";
import * as $$$$$$$$$38 from "./actions/pedidos/estornar-contas.ts";
import * as $$$$$$$$$39 from "./actions/pedidos/estornar-estoque.ts";
import * as $$$$$$$$$40 from "./actions/pedidos/gerar-nota-fiscal.ts";
import * as $$$$$$$$$41 from "./actions/pedidos/lancar-contas.ts";
import * as $$$$$$$$$42 from "./actions/pedidos/lancar-estoque.ts";
import * as $$$$$$$$$43 from "./actions/pedidos/marcadores/atualizar.ts";
import * as $$$$$$$$$44 from "./actions/pedidos/marcadores/criar.ts";
import * as $$$$$$$$$45 from "./actions/pedidos/marcadores/excluir.ts";
import * as $$$$$$$$$46 from "./actions/produtos/atualizar-kit.ts";
import * as $$$$$$$$$47 from "./actions/produtos/atualizar.ts";
import * as $$$$$$$$$48 from "./actions/produtos/criar.ts";
import * as $$$$$$$$$49 from "./actions/produtos/preco/atualizar.ts";
import * as $$$$$$$$$50 from "./actions/produtos/variacoes/atualizar.ts";
import * as $$$$$$$$$51 from "./actions/produtos/variacoes/criar.ts";
import * as $$$$$$$$$52 from "./actions/produtos/variacoes/excluir.ts";
import * as $$$$$$$$$53 from "./actions/separacao/atualizar-situacao.ts";
import * as $$$$$$$$$54 from "./actions/servicos/atualizar.ts";
import * as $$$$$$$$$55 from "./actions/servicos/criar.ts";
import * as $$$$$$$$$56 from "./actions/servicos/transformar-produto.ts";
import * as $$$0 from "./loaders/categorias-receita-despesa.ts";
import * as $$$1 from "./loaders/categorias/todas.ts";
import * as $$$2 from "./loaders/contas-pagar/listar.ts";
import * as $$$3 from "./loaders/contas-pagar/marcadores.ts";
import * as $$$4 from "./loaders/contas-pagar/obter.ts";
import * as $$$5 from "./loaders/contas-receber/listar.ts";
import * as $$$6 from "./loaders/contas-receber/marcadores.ts";
import * as $$$7 from "./loaders/contas-receber/obter.ts";
import * as $$$8 from "./loaders/contatos/listar.ts";
import * as $$$9 from "./loaders/contatos/obter.ts";
import * as $$$10 from "./loaders/contatos/pessoas/listar.ts";
import * as $$$11 from "./loaders/contatos/pessoas/obter.ts";
import * as $$$12 from "./loaders/contatos/tipos.ts";
import * as $$$13 from "./loaders/estoque/obter.ts";
import * as $$$14 from "./loaders/expedicao/etiquetas.ts";
import * as $$$15 from "./loaders/expedicao/expedicao-etiquetas.ts";
import * as $$$16 from "./loaders/expedicao/listar.ts";
import * as $$$17 from "./loaders/expedicao/obter.ts";
import * as $$$18 from "./loaders/formas-envio/listar.ts";
import * as $$$19 from "./loaders/formas-envio/obter.ts";
import * as $$$20 from "./loaders/formas-pagamento/listar.ts";
import * as $$$21 from "./loaders/formas-pagamento/obter.ts";
import * as $$$22 from "./loaders/info.ts";
import * as $$$23 from "./loaders/intermediadores/listar.ts";
import * as $$$24 from "./loaders/intermediadores/obter.ts";
import * as $$$25 from "./loaders/listas-precos/listar.ts";
import * as $$$26 from "./loaders/listas-precos/obter.ts";
import * as $$$27 from "./loaders/marcas/listar.ts";
import * as $$$28 from "./loaders/notas/link.ts";
import * as $$$29 from "./loaders/notas/listar.ts";
import * as $$$30 from "./loaders/notas/marcadores.ts";
import * as $$$31 from "./loaders/notas/obter.ts";
import * as $$$32 from "./loaders/notas/xml.ts";
import * as $$$33 from "./loaders/ordem-compra/listar.ts";
import * as $$$34 from "./loaders/ordem-compra/obter.ts";
import * as $$$35 from "./loaders/ordem-servico/listar.ts";
import * as $$$36 from "./loaders/ordem-servico/obter.ts";
import * as $$$37 from "./loaders/pedidos/listar.ts";
import * as $$$38 from "./loaders/pedidos/marcadores/listar.ts";
import * as $$$39 from "./loaders/pedidos/obter.ts";
import * as $$$40 from "./loaders/produtos/custos.ts";
import * as $$$41 from "./loaders/produtos/kit.ts";
import * as $$$42 from "./loaders/produtos/listar.ts";
import * as $$$43 from "./loaders/produtos/obter.ts";
import * as $$$44 from "./loaders/produtos/tags.ts";
import * as $$$45 from "./loaders/separacao/listar.ts";
import * as $$$46 from "./loaders/separacao/obter.ts";
import * as $$$47 from "./loaders/servicos/listar.ts";
import * as $$$48 from "./loaders/servicos/obter.ts";
import * as $$$49 from "./loaders/vendedores/listar.ts";

const manifest = {
  "loaders": {
    "tiny/loaders/categorias-receita-despesa.ts": $$$0,
    "tiny/loaders/categorias/todas.ts": $$$1,
    "tiny/loaders/contas-pagar/listar.ts": $$$2,
    "tiny/loaders/contas-pagar/marcadores.ts": $$$3,
    "tiny/loaders/contas-pagar/obter.ts": $$$4,
    "tiny/loaders/contas-receber/listar.ts": $$$5,
    "tiny/loaders/contas-receber/marcadores.ts": $$$6,
    "tiny/loaders/contas-receber/obter.ts": $$$7,
    "tiny/loaders/contatos/listar.ts": $$$8,
    "tiny/loaders/contatos/obter.ts": $$$9,
    "tiny/loaders/contatos/pessoas/listar.ts": $$$10,
    "tiny/loaders/contatos/pessoas/obter.ts": $$$11,
    "tiny/loaders/contatos/tipos.ts": $$$12,
    "tiny/loaders/estoque/obter.ts": $$$13,
    "tiny/loaders/expedicao/etiquetas.ts": $$$14,
    "tiny/loaders/expedicao/expedicao-etiquetas.ts": $$$15,
    "tiny/loaders/expedicao/listar.ts": $$$16,
    "tiny/loaders/expedicao/obter.ts": $$$17,
    "tiny/loaders/formas-envio/listar.ts": $$$18,
    "tiny/loaders/formas-envio/obter.ts": $$$19,
    "tiny/loaders/formas-pagamento/listar.ts": $$$20,
    "tiny/loaders/formas-pagamento/obter.ts": $$$21,
    "tiny/loaders/info.ts": $$$22,
    "tiny/loaders/intermediadores/listar.ts": $$$23,
    "tiny/loaders/intermediadores/obter.ts": $$$24,
    "tiny/loaders/listas-precos/listar.ts": $$$25,
    "tiny/loaders/listas-precos/obter.ts": $$$26,
    "tiny/loaders/marcas/listar.ts": $$$27,
    "tiny/loaders/notas/link.ts": $$$28,
    "tiny/loaders/notas/listar.ts": $$$29,
    "tiny/loaders/notas/marcadores.ts": $$$30,
    "tiny/loaders/notas/obter.ts": $$$31,
    "tiny/loaders/notas/xml.ts": $$$32,
    "tiny/loaders/ordem-compra/listar.ts": $$$33,
    "tiny/loaders/ordem-compra/obter.ts": $$$34,
    "tiny/loaders/ordem-servico/listar.ts": $$$35,
    "tiny/loaders/ordem-servico/obter.ts": $$$36,
    "tiny/loaders/pedidos/listar.ts": $$$37,
    "tiny/loaders/pedidos/marcadores/listar.ts": $$$38,
    "tiny/loaders/pedidos/obter.ts": $$$39,
    "tiny/loaders/produtos/custos.ts": $$$40,
    "tiny/loaders/produtos/kit.ts": $$$41,
    "tiny/loaders/produtos/listar.ts": $$$42,
    "tiny/loaders/produtos/obter.ts": $$$43,
    "tiny/loaders/produtos/tags.ts": $$$44,
    "tiny/loaders/separacao/listar.ts": $$$45,
    "tiny/loaders/separacao/obter.ts": $$$46,
    "tiny/loaders/servicos/listar.ts": $$$47,
    "tiny/loaders/servicos/obter.ts": $$$48,
    "tiny/loaders/vendedores/listar.ts": $$$49,
  },
  "actions": {
    "tiny/actions/contas-pagar/criar.ts": $$$$$$$$$0,
    "tiny/actions/contas-receber/atualizar.ts": $$$$$$$$$1,
    "tiny/actions/contas-receber/baixar.ts": $$$$$$$$$2,
    "tiny/actions/contas-receber/criar.ts": $$$$$$$$$3,
    "tiny/actions/contatos/atualizar.ts": $$$$$$$$$4,
    "tiny/actions/contatos/criar.ts": $$$$$$$$$5,
    "tiny/actions/contatos/pessoas/atualizar.ts": $$$$$$$$$6,
    "tiny/actions/contatos/pessoas/criar.ts": $$$$$$$$$7,
    "tiny/actions/contatos/pessoas/excluir.ts": $$$$$$$$$8,
    "tiny/actions/estoque/atualizar.ts": $$$$$$$$$9,
    "tiny/actions/expedicao/adicionar-origens.ts": $$$$$$$$$10,
    "tiny/actions/expedicao/alterar-expedicao.ts": $$$$$$$$$11,
    "tiny/actions/expedicao/concluir.ts": $$$$$$$$$12,
    "tiny/actions/expedicao/criar.ts": $$$$$$$$$13,
    "tiny/actions/marcas/atualizar.ts": $$$$$$$$$14,
    "tiny/actions/marcas/criar.ts": $$$$$$$$$15,
    "tiny/actions/notas/atualizar-marcadores.ts": $$$$$$$$$16,
    "tiny/actions/notas/criar-marcador.ts": $$$$$$$$$17,
    "tiny/actions/notas/emitir.ts": $$$$$$$$$18,
    "tiny/actions/notas/excluir-marcadores.ts": $$$$$$$$$19,
    "tiny/actions/notas/incluir-xml.ts": $$$$$$$$$20,
    "tiny/actions/notas/lancar-contas.ts": $$$$$$$$$21,
    "tiny/actions/notas/lancar-estoque.ts": $$$$$$$$$22,
    "tiny/actions/ordem-compra/atualizar-situacao.ts": $$$$$$$$$23,
    "tiny/actions/ordem-compra/atualizar.ts": $$$$$$$$$24,
    "tiny/actions/ordem-compra/criar.ts": $$$$$$$$$25,
    "tiny/actions/ordem-compra/lancar-contas.ts": $$$$$$$$$26,
    "tiny/actions/ordem-compra/lancar-estoque.ts": $$$$$$$$$27,
    "tiny/actions/ordem-servico/atualizar-situacao.ts": $$$$$$$$$28,
    "tiny/actions/ordem-servico/atualizar.ts": $$$$$$$$$29,
    "tiny/actions/ordem-servico/criar.ts": $$$$$$$$$30,
    "tiny/actions/ordem-servico/gerar-nota-fiscal.ts": $$$$$$$$$31,
    "tiny/actions/ordem-servico/lancar-contas.ts": $$$$$$$$$32,
    "tiny/actions/ordem-servico/lancar-estoque.ts": $$$$$$$$$33,
    "tiny/actions/pedidos/atualizar-despacho.ts": $$$$$$$$$34,
    "tiny/actions/pedidos/atualizar-situacao.ts": $$$$$$$$$35,
    "tiny/actions/pedidos/atualizar.ts": $$$$$$$$$36,
    "tiny/actions/pedidos/criar.ts": $$$$$$$$$37,
    "tiny/actions/pedidos/estornar-contas.ts": $$$$$$$$$38,
    "tiny/actions/pedidos/estornar-estoque.ts": $$$$$$$$$39,
    "tiny/actions/pedidos/gerar-nota-fiscal.ts": $$$$$$$$$40,
    "tiny/actions/pedidos/lancar-contas.ts": $$$$$$$$$41,
    "tiny/actions/pedidos/lancar-estoque.ts": $$$$$$$$$42,
    "tiny/actions/pedidos/marcadores/atualizar.ts": $$$$$$$$$43,
    "tiny/actions/pedidos/marcadores/criar.ts": $$$$$$$$$44,
    "tiny/actions/pedidos/marcadores/excluir.ts": $$$$$$$$$45,
    "tiny/actions/produtos/atualizar-kit.ts": $$$$$$$$$46,
    "tiny/actions/produtos/atualizar.ts": $$$$$$$$$47,
    "tiny/actions/produtos/criar.ts": $$$$$$$$$48,
    "tiny/actions/produtos/preco/atualizar.ts": $$$$$$$$$49,
    "tiny/actions/produtos/variacoes/atualizar.ts": $$$$$$$$$50,
    "tiny/actions/produtos/variacoes/criar.ts": $$$$$$$$$51,
    "tiny/actions/produtos/variacoes/excluir.ts": $$$$$$$$$52,
    "tiny/actions/separacao/atualizar-situacao.ts": $$$$$$$$$53,
    "tiny/actions/servicos/atualizar.ts": $$$$$$$$$54,
    "tiny/actions/servicos/criar.ts": $$$$$$$$$55,
    "tiny/actions/servicos/transformar-produto.ts": $$$$$$$$$56,
  },
  "name": "tiny",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
