// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/index/product.ts";
import * as $$$0 from "./loaders/product/list.ts";
import * as $$$1 from "./loaders/product/listingPage.ts";
import * as $$$$$$$$$$0 from "./workflows/index/product.ts";

const manifest = {
  "loaders": {
    "typesense/loaders/product/list.ts": $$$0,
    "typesense/loaders/product/listingPage.ts": $$$1,
  },
  "actions": {
    "typesense/actions/index/product.ts": $$$$$$$$$0,
  },
  "workflows": {
    "typesense/workflows/index/product.ts": $$$$$$$$$$0,
  },
  "name": "typesense",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
