// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/bankByCode.ts";
import * as $$$1 from "./loaders/banks.ts";
import * as $$$2 from "./loaders/cep.ts";
import * as $$$3 from "./loaders/cepV2.ts";
import * as $$$4 from "./loaders/cnpj.ts";
import * as $$$5 from "./loaders/ddd.ts";
import * as $$$6 from "./loaders/holidays.ts";
import * as $$$7 from "./loaders/states.ts";

const manifest = {
  "loaders": {
    "brasilapi/loaders/bankByCode.ts": $$$0,
    "brasilapi/loaders/banks.ts": $$$1,
    "brasilapi/loaders/cep.ts": $$$2,
    "brasilapi/loaders/cepV2.ts": $$$3,
    "brasilapi/loaders/cnpj.ts": $$$4,
    "brasilapi/loaders/ddd.ts": $$$5,
    "brasilapi/loaders/holidays.ts": $$$6,
    "brasilapi/loaders/states.ts": $$$7,
  },
  "name": "brasilapi",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
