// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/bankByCode.ts";
import * as $$$1 from "./loaders/banks.ts";
import * as $$$2 from "./loaders/cep.ts";
import * as $$$3 from "./loaders/cepV2.ts";
import * as $$$4 from "./loaders/cnpj.ts";
import * as $$$5 from "./loaders/corretoraPorCnpj.ts";
import * as $$$6 from "./loaders/corretoras.ts";
import * as $$$7 from "./loaders/cotacaoCambio.ts";
import * as $$$8 from "./loaders/cptecCidadePorNome.ts";
import * as $$$9 from "./loaders/cptecCidades.ts";
import * as $$$10 from "./loaders/ddd.ts";
import * as $$$11 from "./loaders/dominioBr.ts";
import * as $$$12 from "./loaders/fipeTables.ts";
import * as $$$13 from "./loaders/holidays.ts";
import * as $$$14 from "./loaders/marcasFipe.ts";
import * as $$$15 from "./loaders/moedas.ts";
import * as $$$16 from "./loaders/municipiosByUF.ts";
import * as $$$17 from "./loaders/ncm.ts";
import * as $$$18 from "./loaders/ncmPorCodigo.ts";
import * as $$$19 from "./loaders/pixParticipantes.ts";
import * as $$$20 from "./loaders/precoFipe.ts";
import * as $$$21 from "./loaders/stateByCode.ts";
import * as $$$22 from "./loaders/states.ts";
import * as $$$23 from "./loaders/taxaPorSigla.ts";
import * as $$$24 from "./loaders/taxas.ts";
import * as $$$25 from "./loaders/veiculosFipe.ts";

const manifest = {
  "loaders": {
    "brasilapi/loaders/bankByCode.ts": $$$0,
    "brasilapi/loaders/banks.ts": $$$1,
    "brasilapi/loaders/cep.ts": $$$2,
    "brasilapi/loaders/cepV2.ts": $$$3,
    "brasilapi/loaders/cnpj.ts": $$$4,
    "brasilapi/loaders/corretoraPorCnpj.ts": $$$5,
    "brasilapi/loaders/corretoras.ts": $$$6,
    "brasilapi/loaders/cotacaoCambio.ts": $$$7,
    "brasilapi/loaders/cptecCidadePorNome.ts": $$$8,
    "brasilapi/loaders/cptecCidades.ts": $$$9,
    "brasilapi/loaders/ddd.ts": $$$10,
    "brasilapi/loaders/dominioBr.ts": $$$11,
    "brasilapi/loaders/fipeTables.ts": $$$12,
    "brasilapi/loaders/holidays.ts": $$$13,
    "brasilapi/loaders/marcasFipe.ts": $$$14,
    "brasilapi/loaders/moedas.ts": $$$15,
    "brasilapi/loaders/municipiosByUF.ts": $$$16,
    "brasilapi/loaders/ncm.ts": $$$17,
    "brasilapi/loaders/ncmPorCodigo.ts": $$$18,
    "brasilapi/loaders/pixParticipantes.ts": $$$19,
    "brasilapi/loaders/precoFipe.ts": $$$20,
    "brasilapi/loaders/stateByCode.ts": $$$21,
    "brasilapi/loaders/states.ts": $$$22,
    "brasilapi/loaders/taxaPorSigla.ts": $$$23,
    "brasilapi/loaders/taxas.ts": $$$24,
    "brasilapi/loaders/veiculosFipe.ts": $$$25,
  },
  "name": "brasilapi",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
