// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/submitReview.ts";
import * as $$$0 from "./loaders/productDetailsPage.ts";
import * as $$$1 from "./loaders/productList.ts";
import * as $$$2 from "./loaders/productListingPage.ts";
import * as $$$3 from "./loaders/review.ts";
import * as $$$4 from "./loaders/reviewForm.ts";
import * as $$$$$$0 from "./sections/Question.tsx";
import * as $$$$$$1 from "./sections/WriteReviewForm.tsx";

const manifest = {
  "loaders": {
    "power-reviews/loaders/productDetailsPage.ts": $$$0,
    "power-reviews/loaders/productList.ts": $$$1,
    "power-reviews/loaders/productListingPage.ts": $$$2,
    "power-reviews/loaders/review.ts": $$$3,
    "power-reviews/loaders/reviewForm.ts": $$$4,
  },
  "sections": {
    "power-reviews/sections/Question.tsx": $$$$$$0,
    "power-reviews/sections/WriteReviewForm.tsx": $$$$$$1,
  },
  "actions": {
    "power-reviews/actions/submitReview.ts": $$$$$$$$$0,
  },
  "name": "power-reviews",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
