// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/advancedSearch.ts";
import * as $$$0 from "./loaders/scrape.ts";
import * as $$$1 from "./loaders/search.ts";

const manifest = {
  "loaders": {
    "serper/loaders/scrape.ts": $$$0,
    "serper/loaders/search.ts": $$$1,
  },
  "actions": {
    "serper/actions/advancedSearch.ts": $$$$$$$$$0,
  },
  "name": "serper",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
