// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/get.ts";
import * as $$$1 from "./loaders/events.ts";
import * as $$$$0 from "./handlers/workflowRunner.ts";
import * as $$$$$$$$$0 from "./actions/start.ts";
import * as $$$$$$$$$1 from "./actions/cancel.ts";
import * as $$$$$$$$$2 from "./actions/signal.ts";
import { AppManifest } from "$live/types.ts";

const manifest = {
  "loaders": {
    "apps/workflows/loaders/events.ts": $$$1,
    "apps/workflows/loaders/get.ts": $$$0,
  },
  "handlers": {
    "apps/workflows/handlers/workflowRunner.ts": $$$$0,
  },
  "actions": {
    "apps/workflows/actions/cancel.ts": $$$$$$$$$1,
    "apps/workflows/actions/signal.ts": $$$$$$$$$2,
    "apps/workflows/actions/start.ts": $$$$$$$$$0,
  },
};

export type Manifest = typeof manifest;

export const name = "apps/workflows";

export default manifest satisfies AppManifest;
