// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/chat.ts";

const manifest = {
  "actions": {
    "brand-assistant/actions/chat.ts": $$$$$$$$$0,
  },
  "name": "brand-assistant",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
