// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/submitRating.ts";
import * as $$$$$$$$$1 from "./actions/submitReview.ts";
import * as $$$$$$$$$2 from "./actions/submitView.ts";
import * as $$$0 from "./loaders/Author.ts";
import * as $$$4 from "./loaders/Blogpost.ts";
import * as $$$1 from "./loaders/BlogPostItem.ts";
import * as $$$5 from "./loaders/BlogpostList.ts";
import * as $$$6 from "./loaders/BlogpostListing.ts";
import * as $$$2 from "./loaders/BlogPostPage.ts";
import * as $$$3 from "./loaders/BlogRelatedPosts.ts";
import * as $$$7 from "./loaders/Category.ts";
import * as $$$9 from "./loaders/extensions/BlogpostList.ts";
import * as $$$10 from "./loaders/extensions/BlogpostList/ratings.ts";
import * as $$$11 from "./loaders/extensions/BlogpostList/reviews.ts";
import * as $$$12 from "./loaders/extensions/BlogpostListing.ts";
import * as $$$13 from "./loaders/extensions/BlogpostListing/ratings.ts";
import * as $$$14 from "./loaders/extensions/BlogpostListing/reviews.ts";
import * as $$$15 from "./loaders/extensions/BlogpostPage.ts";
import * as $$$16 from "./loaders/extensions/BlogpostPage/ratings.ts";
import * as $$$17 from "./loaders/extensions/BlogpostPage/reviews.ts";
import * as $$$8 from "./loaders/GetCategories.ts";
import * as $$$$$$0 from "./sections/Seo/SeoBlogPost.tsx";
import * as $$$$$$1 from "./sections/Seo/SeoBlogPostListing.tsx";
import * as $$$$$$2 from "./sections/Template.tsx";

const manifest = {
  "loaders": {
    "blog/loaders/Author.ts": $$$0,
    "blog/loaders/Blogpost.ts": $$$4,
    "blog/loaders/BlogPostItem.ts": $$$1,
    "blog/loaders/BlogpostList.ts": $$$5,
    "blog/loaders/BlogpostListing.ts": $$$6,
    "blog/loaders/BlogPostPage.ts": $$$2,
    "blog/loaders/BlogRelatedPosts.ts": $$$3,
    "blog/loaders/Category.ts": $$$7,
    "blog/loaders/extensions/BlogpostList.ts": $$$9,
    "blog/loaders/extensions/BlogpostList/ratings.ts": $$$10,
    "blog/loaders/extensions/BlogpostList/reviews.ts": $$$11,
    "blog/loaders/extensions/BlogpostListing.ts": $$$12,
    "blog/loaders/extensions/BlogpostListing/ratings.ts": $$$13,
    "blog/loaders/extensions/BlogpostListing/reviews.ts": $$$14,
    "blog/loaders/extensions/BlogpostPage.ts": $$$15,
    "blog/loaders/extensions/BlogpostPage/ratings.ts": $$$16,
    "blog/loaders/extensions/BlogpostPage/reviews.ts": $$$17,
    "blog/loaders/GetCategories.ts": $$$8,
  },
  "sections": {
    "blog/sections/Seo/SeoBlogPost.tsx": $$$$$$0,
    "blog/sections/Seo/SeoBlogPostListing.tsx": $$$$$$1,
    "blog/sections/Template.tsx": $$$$$$2,
  },
  "actions": {
    "blog/actions/submitRating.ts": $$$$$$$$$0,
    "blog/actions/submitReview.ts": $$$$$$$$$1,
    "blog/actions/submitView.ts": $$$$$$$$$2,
  },
  "name": "blog",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
