// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/deployMap.ts";
import * as $$$0 from "./loaders/listPlaces.ts";

const manifest = {
  "loaders": {
    "roblox/loaders/listPlaces.ts": $$$0,
  },
  "actions": {
    "roblox/actions/deployMap.ts": $$$$$$$$$0,
  },
  "name": "roblox",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
