// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/appendValues.ts";
import * as $$$$$$$$$1 from "./actions/batchUpdateValues.ts";
import * as $$$$$$$$$2 from "./actions/createSpreadsheet.ts";
import * as $$$$$$$$$3 from "./actions/updateValues.ts";
import * as $$$0 from "./loaders/authClient.ts";
import * as $$$1 from "./loaders/getBatchValues.ts";
import * as $$$2 from "./loaders/getSpreadsheet.ts";
import * as $$$3 from "./loaders/getValues.ts";
import * as $$$$$$0 from "./sections/login.tsx";

const manifest = {
  "loaders": {
    "google-sheets/loaders/authClient.ts": $$$0,
    "google-sheets/loaders/getBatchValues.ts": $$$1,
    "google-sheets/loaders/getSpreadsheet.ts": $$$2,
    "google-sheets/loaders/getValues.ts": $$$3,
  },
  "sections": {
    "google-sheets/sections/login.tsx": $$$$$$0,
  },
  "actions": {
    "google-sheets/actions/appendValues.ts": $$$$$$$$$0,
    "google-sheets/actions/batchUpdateValues.ts": $$$$$$$$$1,
    "google-sheets/actions/createSpreadsheet.ts": $$$$$$$$$2,
    "google-sheets/actions/updateValues.ts": $$$$$$$$$3,
  },
  "name": "google-sheets",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
