// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/library/saveAlbums.ts";
import * as $$$$$$$$$1 from "./actions/player/play.ts";
import * as $$$$$$$$$2 from "./actions/playlists/addTracks.ts";
import * as $$$0 from "./loaders/oauth/whoami.ts";
import * as $$$1 from "./loaders/player/getDevices.ts";
import * as $$$2 from "./loaders/users/getCurrentUser.ts";

const manifest = {
  "loaders": {
    "spotify/loaders/oauth/whoami.ts": $$$0,
    "spotify/loaders/player/getDevices.ts": $$$1,
    "spotify/loaders/users/getCurrentUser.ts": $$$2,
  },
  "actions": {
    "spotify/actions/library/saveAlbums.ts": $$$$$$$$$0,
    "spotify/actions/player/play.ts": $$$$$$$$$1,
    "spotify/actions/playlists/addTracks.ts": $$$$$$$$$2,
  },
  "name": "spotify",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;