// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/code/suggestions.ts";
import * as $$$$$$$$$1 from "./actions/code/vision.ts";
import * as $$$$$$$$$2 from "./actions/deployments/create.ts";
import * as $$$$$$$$$3 from "./actions/github/setStatus.ts";
import * as $$$$$$$$$4 from "./actions/github/webhooks/broker.ts";
import * as $$$$$$$$$5 from "./actions/platforms/assign.ts";
import * as $$$$$$$$$6 from "./actions/sites/create.ts";
import * as $$$$$$$$$7 from "./actions/sites/linkRepo.ts";
import * as $$$$$$$$$8 from "./actions/sites/newDomain.ts";
import * as $$$$$$$$$9 from "./actions/sites/unlinkRepo.ts";
import * as $$$0 from "./loaders/assistants/code.ts";
import * as $$$1 from "./loaders/deploy.ts";
import * as $$$2 from "./loaders/platforms/forSite.ts";

const manifest = {
  "loaders": {
    "deco-sites/admin/loaders/assistants/code.ts": $$$0,
    "deco-sites/admin/loaders/deploy.ts": $$$1,
    "deco-sites/admin/loaders/platforms/forSite.ts": $$$2,
  },
  "actions": {
    "deco-sites/admin/actions/code/suggestions.ts": $$$$$$$$$0,
    "deco-sites/admin/actions/code/vision.ts": $$$$$$$$$1,
    "deco-sites/admin/actions/deployments/create.ts": $$$$$$$$$2,
    "deco-sites/admin/actions/github/setStatus.ts": $$$$$$$$$3,
    "deco-sites/admin/actions/github/webhooks/broker.ts": $$$$$$$$$4,
    "deco-sites/admin/actions/platforms/assign.ts": $$$$$$$$$5,
    "deco-sites/admin/actions/sites/create.ts": $$$$$$$$$6,
    "deco-sites/admin/actions/sites/linkRepo.ts": $$$$$$$$$7,
    "deco-sites/admin/actions/sites/newDomain.ts": $$$$$$$$$8,
    "deco-sites/admin/actions/sites/unlinkRepo.ts": $$$$$$$$$9,
  },
  "name": "deco-sites/admin",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
