// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/audioIsolation.ts";
import * as $$$$$$$$$1 from "./actions/createVoiceClone.ts";
import * as $$$$$$$$$2 from "./actions/textToSoundEffects.ts";
import * as $$$$$$$$$3 from "./actions/textToSpeech.ts";
import * as $$$$$$$$$4 from "./actions/textToVoiceWithTimestamps.ts";
import * as $$$$$$$$$5 from "./actions/transcribeAudio.ts";
import * as $$$$$$$$$6 from "./actions/voiceChanger.ts";

const manifest = {
  "actions": {
    "eleven-labs/actions/audioIsolation.ts": $$$$$$$$$0,
    "eleven-labs/actions/createVoiceClone.ts": $$$$$$$$$1,
    "eleven-labs/actions/textToSoundEffects.ts": $$$$$$$$$2,
    "eleven-labs/actions/textToSpeech.ts": $$$$$$$$$3,
    "eleven-labs/actions/textToVoiceWithTimestamps.ts": $$$$$$$$$4,
    "eleven-labs/actions/transcribeAudio.ts": $$$$$$$$$5,
    "eleven-labs/actions/voiceChanger.ts": $$$$$$$$$6,
  },
  "name": "eleven-labs",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
