// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createField.ts";
import * as $$$$$$$$$1 from "./actions/createRecords.ts";
import * as $$$$$$$$$2 from "./actions/createTable.ts";
import * as $$$$$$$$$3 from "./actions/deleteRecords.ts";
import * as $$$$$$$$$4 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$5 from "./actions/permissioning/addNewPermitions.ts";
import * as $$$$$$$$$6 from "./actions/updateField.ts";
import * as $$$$$$$$$7 from "./actions/updateRecords.ts";
import * as $$$$$$$$$8 from "./actions/updateTable.ts";
import * as $$$0 from "./loaders/getBaseSchema.ts";
import * as $$$1 from "./loaders/getRecord.ts";
import * as $$$2 from "./loaders/listBases.ts";
import * as $$$3 from "./loaders/listRecords.ts";
import * as $$$4 from "./loaders/oauth/start.ts";
import * as $$$5 from "./loaders/permissioning/listAllowedTablesBases.ts";
import * as $$$6 from "./loaders/permissioning/validatePermissions.ts";
import * as $$$7 from "./loaders/searchRecords.ts";
import * as $$$8 from "./loaders/whoami.ts";

const manifest = {
  "loaders": {
    "airtable/loaders/getBaseSchema.ts": $$$0,
    "airtable/loaders/getRecord.ts": $$$1,
    "airtable/loaders/listBases.ts": $$$2,
    "airtable/loaders/listRecords.ts": $$$3,
    "airtable/loaders/oauth/start.ts": $$$4,
    "airtable/loaders/permissioning/listAllowedTablesBases.ts": $$$5,
    "airtable/loaders/permissioning/validatePermissions.ts": $$$6,
    "airtable/loaders/searchRecords.ts": $$$7,
    "airtable/loaders/whoami.ts": $$$8,
  },
  "actions": {
    "airtable/actions/createField.ts": $$$$$$$$$0,
    "airtable/actions/createRecords.ts": $$$$$$$$$1,
    "airtable/actions/createTable.ts": $$$$$$$$$2,
    "airtable/actions/deleteRecords.ts": $$$$$$$$$3,
    "airtable/actions/oauth/callback.ts": $$$$$$$$$4,
    "airtable/actions/permissioning/addNewPermitions.ts": $$$$$$$$$5,
    "airtable/actions/updateField.ts": $$$$$$$$$6,
    "airtable/actions/updateRecords.ts": $$$$$$$$$7,
    "airtable/actions/updateTable.ts": $$$$$$$$$8,
  },
  "name": "airtable",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
