// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/following/followArtists.ts";
import * as $$$$$$$$$1 from "./actions/library/removeAlbums.ts";
import * as $$$$$$$$$2 from "./actions/library/removeTracks.ts";
import * as $$$$$$$$$3 from "./actions/library/saveAlbums.ts";
import * as $$$$$$$$$4 from "./actions/library/saveTracks.ts";
import * as $$$$$$$$$5 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$6 from "./actions/player/next.ts";
import * as $$$$$$$$$7 from "./actions/player/pause.ts";
import * as $$$$$$$$$8 from "./actions/player/play.ts";
import * as $$$$$$$$$9 from "./actions/player/previous.ts";
import * as $$$$$$$$$10 from "./actions/player/seek.ts";
import * as $$$$$$$$$11 from "./actions/playlists/addTracks.ts";
import * as $$$$$$$$$12 from "./actions/playlists/removeTracks.ts";
import * as $$$0 from "./loaders/albums/getAlbum.ts";
import * as $$$2 from "./loaders/albums/getAlbums.ts";
import * as $$$1 from "./loaders/albums/getAlbumTracks.ts";
import * as $$$3 from "./loaders/artists/getArtist.ts";
import * as $$$4 from "./loaders/artists/getArtistAlbums.ts";
import * as $$$6 from "./loaders/artists/getArtists.ts";
import * as $$$5 from "./loaders/artists/getArtistTopTracks.ts";
import * as $$$7 from "./loaders/artists/getRelatedArtists.ts";
import * as $$$8 from "./loaders/following/getFollowedArtists.ts";
import * as $$$9 from "./loaders/library/checkSavedTracks.ts";
import * as $$$10 from "./loaders/library/getSavedAlbums.ts";
import * as $$$11 from "./loaders/library/getSavedTracks.ts";
import * as $$$12 from "./loaders/oauth/start.ts";
import * as $$$13 from "./loaders/oauth/whoami.ts";
import * as $$$14 from "./loaders/player/getCurrentTrack.ts";
import * as $$$15 from "./loaders/player/getDevices.ts";
import * as $$$16 from "./loaders/player/getPlaybackState.ts";
import * as $$$17 from "./loaders/player/getRecentlyPlayed.ts";
import * as $$$18 from "./loaders/playlists/getFeaturedPlaylists.ts";
import * as $$$19 from "./loaders/playlists/getPlaylist.ts";
import * as $$$20 from "./loaders/playlists/getPlaylistTracks.ts";
import * as $$$21 from "./loaders/search/search.ts";
import * as $$$22 from "./loaders/tracks/getTrack.ts";
import * as $$$23 from "./loaders/tracks/getTracks.ts";
import * as $$$24 from "./loaders/users/getCurrentUser.ts";
import * as $$$25 from "./loaders/users/getTopArtists.ts";
import * as $$$26 from "./loaders/users/getTopTracks.ts";
import * as $$$27 from "./loaders/users/getUserPlaylists.ts";

const manifest = {
  "loaders": {
    "spotify/loaders/albums/getAlbum.ts": $$$0,
    "spotify/loaders/albums/getAlbums.ts": $$$2,
    "spotify/loaders/albums/getAlbumTracks.ts": $$$1,
    "spotify/loaders/artists/getArtist.ts": $$$3,
    "spotify/loaders/artists/getArtistAlbums.ts": $$$4,
    "spotify/loaders/artists/getArtists.ts": $$$6,
    "spotify/loaders/artists/getArtistTopTracks.ts": $$$5,
    "spotify/loaders/artists/getRelatedArtists.ts": $$$7,
    "spotify/loaders/following/getFollowedArtists.ts": $$$8,
    "spotify/loaders/library/checkSavedTracks.ts": $$$9,
    "spotify/loaders/library/getSavedAlbums.ts": $$$10,
    "spotify/loaders/library/getSavedTracks.ts": $$$11,
    "spotify/loaders/oauth/start.ts": $$$12,
    "spotify/loaders/oauth/whoami.ts": $$$13,
    "spotify/loaders/player/getCurrentTrack.ts": $$$14,
    "spotify/loaders/player/getDevices.ts": $$$15,
    "spotify/loaders/player/getPlaybackState.ts": $$$16,
    "spotify/loaders/player/getRecentlyPlayed.ts": $$$17,
    "spotify/loaders/playlists/getFeaturedPlaylists.ts": $$$18,
    "spotify/loaders/playlists/getPlaylist.ts": $$$19,
    "spotify/loaders/playlists/getPlaylistTracks.ts": $$$20,
    "spotify/loaders/search/search.ts": $$$21,
    "spotify/loaders/tracks/getTrack.ts": $$$22,
    "spotify/loaders/tracks/getTracks.ts": $$$23,
    "spotify/loaders/users/getCurrentUser.ts": $$$24,
    "spotify/loaders/users/getTopArtists.ts": $$$25,
    "spotify/loaders/users/getTopTracks.ts": $$$26,
    "spotify/loaders/users/getUserPlaylists.ts": $$$27,
  },
  "actions": {
    "spotify/actions/following/followArtists.ts": $$$$$$$$$0,
    "spotify/actions/library/removeAlbums.ts": $$$$$$$$$1,
    "spotify/actions/library/removeTracks.ts": $$$$$$$$$2,
    "spotify/actions/library/saveAlbums.ts": $$$$$$$$$3,
    "spotify/actions/library/saveTracks.ts": $$$$$$$$$4,
    "spotify/actions/oauth/callback.ts": $$$$$$$$$5,
    "spotify/actions/player/next.ts": $$$$$$$$$6,
    "spotify/actions/player/pause.ts": $$$$$$$$$7,
    "spotify/actions/player/play.ts": $$$$$$$$$8,
    "spotify/actions/player/previous.ts": $$$$$$$$$9,
    "spotify/actions/player/seek.ts": $$$$$$$$$10,
    "spotify/actions/playlists/addTracks.ts": $$$$$$$$$11,
    "spotify/actions/playlists/removeTracks.ts": $$$$$$$$$12,
  },
  "name": "spotify",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
