// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/build.ts";

const manifest = {
  "actions": {
    "js-bundler/actions/build.ts": $$$$$$$$$0,
  },
  "name": "js-bundler",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
