// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$0 from "./loaders/listMember.ts";
import * as $$$1 from "./loaders/lists.ts";
import * as $$$2 from "./loaders/options/lists.ts";
import * as $$$$$$$$$0 from "./actions/subscribe.ts";
import * as $$$$$$$$$1 from "./actions/unsubscribe.ts";

const manifest = {
  "loaders": {
    "mailchimp/loaders/listMember.ts": $$$0,
    "mailchimp/loaders/lists.ts": $$$1,
    "mailchimp/loaders/options/lists.ts": $$$2,
  },
  "actions": {
    "mailchimp/actions/subscribe.ts": $$$$$$$$$0,
    "mailchimp/actions/unsubscribe.ts": $$$$$$$$$1,
  },
  "name": "mailchimp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
