swagger: "2.0"
info:
  description: Bulk de dados do saldo devedor do cliente
  version: 1.0.0
  title: Geração do Saldo Devedor do Cliente
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/bulk-data/v1"
tags:
  - name: Saldo devedor Cliente
    description: Bulk de dados do saldo devedor presente do cliente
paths:
  /customer-debt-balance:
    get:
      tags:
        - Saldo devedor cliente
      summary: >-
        Gera as informações referentes ao saldo devedor do cliente informado.
      operationId: getCurrentDebtBalance
      produces:
        - application/json
      parameters:
        - name: "startDueDate"
          in: "query"
          required: true
          type: "string"
          format: "date"
          description: "Data de vencimento inicial para incluir na pesquisa.<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
        - name: "endDueDate"
          in: "query"
          required: true
          type: "string"
          format: "date"
          description: "Data de vencimento final para incluir na pesquisa.<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
        - name: "correctionDate"
          in: "query"
          required: false
          type: "string"
          format: "date"
          description: "Data de correção até para incluir na pesquisa.<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
        - name: "positionDate"
          in: "query"
          required: false
          type: "string"
          format: "date"
          description: "Data da posição em para incluir na pesquisa.<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
        - name: "changeStartDate"
          in: "query"
          required: false
          type: "string"
          format: "date"
          description: "Data da alteração inicial para incluir na pesquisa.<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
        - name: "billReceivableId"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          description: "Número do título para incluir na pesquisa."
        - name: "companyId"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          description: "Código da empresa para incluir na pesquisa."
        - name: "customerId"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          description: "Código do cliente para incluir na pesquisa."
        - name: "costCenterId"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          description: "Código do centro de custo para incluir na pesquisa."
        - name: "unitNumber"
          in: "query"
          required: false
          type: "string"
          description: "Código da unidade para incluir na pesquisa."
        - name: "documentsId"
          in: "query"
          required: false
          type: "array"
          items:
            type: "string"
          description: "Lista de códigos de documentos para incluir na pesquisa (separados por vírgula)."
        - name: "bearersId"
          in: "query"
          required: false
          type: "array"
          items:
            type: "integer"
            format: "int32"
          description: "Lista de códigos dos portadores para incluir na pesquisa (separados por vírgula)."
        - name: "paymentTermsId"
          in: "query"
          required: false
          type: "array"
          items:
            type: "string"
          description: "Lista das condições de pagamento para incluir na consulta.<br>(exemplo: AT - Ato, PM - Parcelas Mensais, PA - Parcelas Anuais)"
        - name: "paymentTermsIdNotIn"
          in: "query"
          required: false
          type: "array"
          items:
            type: "string"
          description: "Lista das condições de pagamento para NÃO incluir na consulta.<br>(exemplo: AT, PM)"
        - name: "interestAmount"
          in: "query"
          required: false
          type: "number"
          format: "double"
          default: "0.0"
          description: "Valor dos juros para incluir na consulta (padrão: 0.0)."
        - name: "commercialDiscount"
          in: "query"
          required: false
          type: "number"
          format: "double"
          default: "0.0"
          description: "Valor do desconto comercial para incluir na consulta (padrão: 0.0)."
        - name: "calculatePresentValue"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para calcular o valor presente."
        - name: "includeAdministrativeRateAmount"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para considerar o valor da taxa administrativa no saldo."
        - name: "includeInsuranceAmount"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para considerar o valor do seguro no saldo."
        - name: "correctAnnualInstallment"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta o valor do saldo das parcelas com correção anual."
        - name: "includeReceiptsByAdvanceRebate"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para considerar baixas de abatimento de adiantamento."
        - name: "includeConditionalDiscountValid"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para considerar os descontos condicionais válidos."
        - name: "calculateAdditionsUserInformation"
          in: "query"
          required: false
          type: "boolean"
          description: "Incluir na consulta para considerar os valores enviados pelo usuário na API<br>(proratedIndexerAdditions, fineAdditions, interestAmountAdditions, interestTypeAdditions, calculateAdditionsDate)."
        - name: "calculateAdditionsValue"
          in: "query"
          required: false
          type: "boolean"
          default: true
          description: "Incluir na consulta para calcular o valor dos acréscimos (padrão: true)"
        - name: "proratedIndexerAdditions"
          in: "query"
          required: false
          type: "integer"
          format: "int32"
          default: 0
          description: "Código do indexador para pró-rata para incluir na consulta (padrão: 0-REAL)."
        - name: "fineAdditions"
          in: "query"
          required: false
          type: "number"
          format: "double"
          default: 0.0
          description: "Percentual da multa para calcular os acréscimos na consulta (padrão: 0.0)."
        - name: "interestAmountAdditions"
          in: "query"
          required: false
          type: "number"
          format: "double"
          default: 0.0
          description: "Percentual dos juros para calcular os acréscimos na consulta (padrão: 0.0)."
        - name: "interestTypeAdditions"
          in: "query"
          required: false
          type: "string"
          description: "Tipo de juros para incluir na consulta (exemplo: N - Nenhum, P - Price, A - S.A.C, S - Simples, C - Composto, F - Fixo)."
        - name: "calculateAdditionsDate"
          in: "query"
          required: false
          type: "string"
          format: "date"
          description: "Data para calcular os acréscimos na consulta (padrão: Data atual).<br>Formato: yyyy-MM-dd (exemplo: 1990-12-01)."
          default: "Data corrente"

      responses:
        "200":
          description: Saldo devedor presente gerado
          schema:
            $ref: "#/definitions/BulkCustomerDebtBalanceResponse"
        "404":
          description: Cliente físico ou jurídico inválido.
          schema:
            $ref: "#/definitions/ResponseErrorMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseErrorMenssage"

definitions:
  BulkCustomerDebtBalanceResponse:
    type: "object"
    properties:
      billReceivableId:
        type: "integer"
        format: "int32"
        description: "ID do título a receber."
      company:
        $ref: "#/definitions/Company"
      costCenter:
        $ref: "#/definitions/CostCenter"
      customer:
        $ref: "#/definitions/Customer"
      secondaryCustomers:
        type: "array"
        items:
          $ref: "#/definitions/Customer"
        description: "Lista de clientes secundários."
      emissionDate:
        type: "string"
        format: "date"
        description: "Data de emissão."
      accountingDate:
        type: "string"
        format: "date"
        description: "Data contábil."
      totalValue:
        type: "number"
        format: "double"
        description: "Valor total."
      lastRenegotiationDate:
        type: "string"
        format: "date"
        description: "Data da última repactuação."
      correctionDate:
        type: "string"
        description: "Data de correção."
      document:
        type: "string"
        description: "Documento associado."
      cancellationDate:
        type: "string"
        format: "date"
        description: "Data de cancelamento."
      units:
        type: "array"
        items:
          $ref: "#/definitions/Unit"
        description: "Lista de unidades associadas."
      installments:
        type: "array"
        items:
          $ref: "#/definitions/Installment"
        description: "Lista de parcelas associadas."

  Company:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID da empresa."
      name:
        type: "string"
        description: "Nome da empresa."

  CostCenter:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID do centro de custo."
      name:
        type: "string"
        description: "Nome do centro de custo."

  Customer:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID do cliente."
      name:
        type: "string"
        description: "Nome do cliente."
      document:
        type: "string"
        description: "Documento do cliente."

  Unit:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "ID da unidade."
      number:
        type: "string"
        description: "Número da unidade."

  PaymentTerm:
    type: "object"
    properties:
      id:
        type: "string"
        description: "Identificador da condição de pagamento."
      descrition:
        type: "string"
        description: "Descrição da condição de pagamento."

  Installment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int32"
        description: "Identificador da parcela."
      paymentTerms:
        $ref: "#/definitions/PaymentTerm"
      correctionBaseDate:
        type: "string"
        format: "date-time"
        description: "Data base para correção."
      originalValue:
        type: "number"
        format: "double"
        description: "Valor original da parcela."
      correctedValue:
        type: "number"
        format: "double"
        description: "Valor corrigido da parcela."
      indexerName:
        type: "string"
        description: "Nome do indexador."
      dueDate:
        type: "string"
        format: "date-time"
        description: "Data de vencimento."
      accoutingReceiptDate:
        type: "string"
        format: "date-time"
        description: "Data de recebimento contábil."
      receiptDate:
        type: "string"
        format: "date-time"
        description: "Data de recebimento."
      receiptBankAccount:
        type: "string"
        description: "Conta bancária de recebimento."
      netReceivedAmount:
        type: "number"
        format: "double"
        description: "Valor líquido recebido."
      penalty:
        type: "number"
        format: "double"
        description: "Valor da multa."
      interest:
        type: "number"
        format: "double"
        description: "Valor dos juros."
      lateFee:
        type: "number"
        format: "double"
        description: "Valor da taxa de atraso."
      currentBalance:
        type: "number"
        format: "double"
        description: "Saldo atual."
      updatedValue:
        type: "number"
        format: "double"
        description: "Valor atualizado."
      additionsValue:
        type: "number"
        format: "double"
        description: "Valor de acréscimos."
      contractualInterest:
        type: "number"
        format: "double"
        description: "Juros contratuais."
      daysLate:
        type: "integer"
        format: "int32"
        description: "Dias de atraso."
      correctionDate:
        type: "string"
        description: "Data de correção."
      daysForPresentValueDiscount:
        type: "integer"
        format: "int32"
        description: "Dias para desconto de valor presente."
      presentValueInterest:
        type: "number"
        format: "double"
        description: "Juros de valor presente."
      presentValue:
        type: "number"
        format: "double"
        description: "Valor presente."
      discountedCommercialValue:
        type: "number"
        format: "double"
        description: "Valor comercial com desconto."
      interestBaseDate:
        type: "string"
        format: "date-time"
        description: "Data base para juros."
      installmentInterest:
        type: "number"
        format: "double"
        description: "Juros da parcela."
      installmentNumber:
        type: "string"
        description: "Número da parcela."
      status:
        type: "string"
        description: "Status da parcela."

  ResponseErrorMenssage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para análise do desenvolvedor
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário
