swagger: "2.0"
info:
  description: BulkData de Contratos de Vendas.
  version: "1.0"
  title: Contratos de vendas
  license:
    name: Softplan - Todos os direitos reservados
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/bulk-data/v1"
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  /sales:
    get:
      tags:
        - BulkData de Contratos de Vendas.
      summary: Realiza leitura dos contratos de vendas.
      operationId: getSales
      parameters:
        - name: enterpriseId
          in: query
          description: Código do empreendimento.
          required: true
          type: integer
        - name: createdAfter
          in: query
          description: Período do contrato inicial. Formato YYYY-MM-DD. Exemplo -> 1990-12-10.
          format: yyyy-MM-dd
          required: true
          type: string
        - name: createdBefore
          in: query
          description: Período do contrato final. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
          format: yyyy-MM-dd
          required: true
          type: string
        - name: situation
          in: query
          description: Situação do contrato(PROPOSAL, SOLD or CANCELED).
          required: true
          type: string
        - name: valueGroupingDescription
          in: query
          description: Valor do agrupamento. Para filtrar por mais de um valor de agrupamento, informe os valores separados por vírgula. Exemplo -> Q1,L2
          required: false
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Resultado da pesquisa retornado com sucesso.
          schema:
            $ref: "#/definitions/GetSales"
        "400":
          description: Requisição mal formada.
          schema:
            $ref: "#/definitions/ResponseMessage"
        "500":
          description: Erro interno no servidor.
          schema:
            $ref: "#/definitions/ResponseMessage"

definitions:
  GetSales:
    type: object
    required:
      - data
    properties:
      data:
        type: array
        description: Lista de contrato de vendas retornados como resultado da pesquisa.
        items:
          $ref: "#/definitions/Sales"

  Sales:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Id do contrato de vendas.
      enterpriseId:
        type: integer
        format: int32
        description: Código do empreendimento.
      receivableBillId:
        type: integer
        format: int32
        description: Número do título a receber.
      refundBillId:
        type: integer
        format: int32
        description: Número do título de devolução (caso contrato seja cancelado).
      proRataIndexer:
        type: integer
        format: int32
        description: Código do indexador de pró-rata. Usado apenas para acréscimo de mora mensal.
      number:
        type: string
        description: Número do contrato.
      situation:
        type: string
        description: Situação do contrato. (Solicitado, Autorizado, Emitido ou Cancelado).
      externalId:
        type: string
        description: Identificador externo.
      note:
        type: string
        description: Observação do contrato.
      cancellationReason:
        type: string
        description: Descrição do motivo de cancelamento.
      interestType:
        type: string
        description: Tipo de juros para acréscimos de mora.
      lateInterestCalculationType:
        type: string
        description: Tipo de cálculo de acréscimos de mora.
      financialInstitutionNumber:
        type: string
        description: Número da instituição financeira.
      discountType:
        type: string
        description: Tipo de desconto do contrato.
      correctionType:
        type: string
        description: Tipo de correção.
      anualCorrectionType:
        type: string
        description: Tipo de correção anual.
      associativeCredit:
        type: string
        description: Indica se tem crédito associativo.
      discountPercentage:
        type: number
        description: Percentual de desconto do contrato.
      value:
        type: number
        description: Valor do contrato.
      totalSellingValue:
        type: number
        description: Valor total de venda.
      interestPercentage:
        type: number
        format: double
        description: Percentual de juros ao mês para acréscimos de mora. Usado apenas para acréscimo de mora mensal.
      fineRate:
        type: number
        format: double
        description: Percentual de multa para acréscimo de mora. Usado apenas para acréscimo de mora mensal.
      dailyLateInterestValue:
        type: number
        format: double
        description: Valor de mora diário em reais.
      creationDate:
        type: string
        description: Data da criação do contrato. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      contractDate:
        type: string
        description: Data do contrato.
      issueDate:
        type: string
        description: Data de emissão do contrato. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      cancellationDate:
        type: string
        description: Data de cancelamento do contrato. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      financialInstitutionDate:
        type: string
        description: Data da instituição financeira. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      customers:
        type: array
        description: Clientes.
        items:
          $ref: "#/definitions/Customers"
      units:
        type: array
        description: Unidades
        items:
          $ref: "#/definitions/Units"
      paymentConditions:
        type: array
        description: Condições de pagamento
        items:
          $ref: "#/definitions/PaymentConditions"
      brokers:
        type: array
        description: Corretores
        items:
          $ref: "#/definitions/Brokers"

  Customers:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Id do cliente do contrato.
      main:
        type: boolean
        description: True se o cliente for principal.
      spouse:
        type: boolean
        description: True se o cliente for cônjuge.
      participationPercentage:
        type: number
        description: Percentual de participação do cliente.
      personType:
        type: string
        description: Tipo de pessoa (física ou jurídica).
      cpf:
        type: string
        description: CPF para pessoa física.
      name:
        type: string
        description: Nome.
      email:
        type: string
        description: E-mail.
      birthDate:
        type: string
        description: Data de nascimento para pessoa física. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      marriageDate:
        type: string
        description: Data de casamento para pessoa física. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      civilStatus:
        type: string
        description: Estado civil para pessoa física.
      fatherName:
        type: string
        description: Nome do pai para pessoa física.
      motherName:
        type: string
        description: Nome da mãe para pessoa física.
      sex:
        type: string
        description: Sexo para pessoa física. Podendo ser Masculino/Feminino/Anônimo (dependendo da LGPD).
      cnpj:
        type: string
        description: CNPJ para pessoa jurídica.
      nationality:
        type: string
        description: Nacionalidade para pessoa física.
      numberIdentityCard:
        type: string
        description: Número da carteira de identidade (RG) para pessoa física.
      profession:
        type: string
        description: Profissão para pessoa física.
      contactName:
        type: string
        description: Nome do contato para pessoa jurídica.
      fantasyName:
        type: string
        description: Nome fantasia para pessoa jurídica.
      spouseData:
        $ref: "#/definitions/Spouse"
      phones:
        type: array
        description: Telefones do cliente
        items:
          $ref: "#/definitions/Phone"
      addresses:
        type: array
        description: Endereços do cliente
        items:
          $ref: "#/definitions/Address"

  Spouse:
    description: Cônjuge para pessoa física.
    type: object
    properties:
      cpf:
        type: string
        description: CPF do cônjuge.
      name:
        type: string
        description: Nome do cônjuge.
      email:
        type: string
        description: E-mail do cônjuge.
      sex:
        type: string
        description: Sexo do cônjuge. Podendo ser Masculino/Feminino/Anônimo (dependendo da LGPD).
      civilStatus:
        type: string
        description: Descrição estado civil do cônjuge.
      birthDate:
        type: string
        description: Data de nascimento do cônjuge. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      numberIdentityCard:
        type: string
        description: Número da carteira de identidade (RG) do cônjuge.

  Phone:
    type: object
    properties:
      type:
        type: string
        description: Tipo de telefone.
      number:
        type: string
        description: Número de telefone, com o DDD.
      main:
        type: boolean
        description: True quando o telefone for principal.
      note:
        type: string
        description: Observação do telefone.
      idd:
        type: string
        description: DDI do Telefone.

  Address:
    type: object
    properties:
      type:
        type: string
        description: Tipo do endereço.
      streetName:
        type: string
        description: Logradouro do endereço.
      number:
        type: string
        description: Número do endereço.
      complement:
        type: string
        description: Complemento do endereço.
      neighborhood:
        type: string
        description: Bairro do endereço.
      cityId:
        type: integer
        description: Identificador do munícipio do endereço.
      city:
        type: string
        description: Nome do munícipio do endereço.
      state:
        type: string
        description: Nome do estado do endereço.
      zipCode:
        type: string
        description: Código de endereçamento postal (CEP) do endereço.
      mail:
        type: boolean
        description: Identifica se é o endereço de correspondencia do cliente.

  Units:
    description: Unidades do contrao de venda
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Id da unidade.
      main:
        type: boolean
        description: True se a unidade for principal.
      participationPercentage:
        type: number
        description: Percentual de participação da unidade.
      name:
        type: string
        description: Nome da unidade.
      propertyType:
        type: string
        description: Tipo de imóvel.
      note:
        type: string
        description: Observação
      commercialStock:
        type: string
        description: Estoque comercial (D = Disponível, V = Vendida, L = Locada, C = Reservada, R = Reserva Técnica, E = Permuta, M = Mutuo, P = Proposta, T = Transferido, G = Vendido/Terceiros).
      legalRegistrationNumber:
        type: string
        description: Matrícula.
      deliveryDate:
        type: string
        description: Data de entrega. Formato YYYY-MM-DD. Exemplo -> 1990-12-25.
      privateArea:
        type: number
        description: Área privativa.
      commonArea:
        type: number
        description: Área comum.
      terrainArea:
        type: number
        description: Área do terreno.
      idealFraction:
        type: number
        description: Fração ideal.
      idealFractionSquareMeter:
        type: number
        description: Fração ideal em m².
      indexedQuantity:
        type: number
        description: Quantidade indexada.
      childUnits:
        type: array
        description: Unidades Filhas
        items:
          $ref: "#/definitions/ChildUnits"
      groupings:
        type: array
        description: Agrupamentos.
        items:
          type: object
          properties:
            groupingDescription:
              type: string
              description: Descrição do agrupador.
            valueGroupingDescription:
              type: string
              description: Descrição do valor do agrupamento.

  ChildUnits:
    description: Unidades filhas
    type: object
    properties:
      name:
        type: string
        description: Descrição da unidade filha.
      order:
        type: string
        description: Numeração.
      privateArea:
        type: number
        description: Área privativa.
      commonArea:
        type: number
        description: Área comum.
      idealFraction:
        type: number
        description: Fração ideal.
      idealFractionSquareMeter:
        type: number
        description: Fração ideal em m².
      locationName:
        type: string
        description: Localização.
      note:
        type: string
        description: Osbservação.

  PaymentConditions:
    description: Condição de pagamento do contrato de venda.
    type: object
    properties:
      conditionTypeId:
        type: string
        description: Código do tipo de condição de pagamento.
      conditionTypeName:
        type: string
        description: Nome do tipo de condição de pagamento.
      bearerId:
        type: string
        description: Código do portador.
      bearerName:
        type: string
        description: Nome do portador.
      installmentsNumber:
        type: integer
        format: int32
        description: Quantidade de parcelas.
      totalValue:
        type: number
        format: double
        description: Valor total da Condição.
      firstPayment:
        type: string
        description: Data do primeiro vencimento.  Formato YYYY-MM-DD. Exemplo -> 1990-12-25.

  Brokers:
    description: Corretores do contrato de venda.
    type: object
    properties:
      id:
        type: number
        description: Código do corretor.
      name:
        type: string
        description: Nome do corretor.
      main:
        type: boolean
        description: True se o corretor for o principal.

  ResponseMessage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para análise do desenvolvedor.
        example: Developer description message
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário.
        example: Client description message.
