swagger: "2.0"
info:
  description: Bulk data de movimentos de caixa e bancos.
  version: 1.0.0
  title: Movimentos de Caixa e Bancos
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/bulk-data/v1"
tags:
  - name: Bulk-data caixas e bancos
    description: Bulk data de movimentos de Caixa e Bancos
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  "/bank-movement":
    get:
      tags:
        - Bulk-data caixas e bancos
      summary: Retorna movimentos financeiros, caso possua.
      operationId: getBankMovements
      parameters:
        - name: startDate
          in: query
          description: Data de início do período da consulta
          required: true
          type: string
          format: "date (Formato ISO 8601 yyyy-MM-dd | Exemplo: 2018-01-01)"
        - name: endDate
          in: query
          description: Data do fim do período da consulta
          required: true
          type: string
          format: "date (Formato ISO 8601 yyyy-MM-dd | Exemplo: 2018-01-01)"
        - name: selectionType
          in: query
          description: Seleção da data do período. Para filtrar por data de movimentação bancária (M), data de competência da parcela (B). Por padrão ao não enviar nenhum valor será filtrado por data de movimentação bancária. Se filtrado por data de competência da parcela, não serão apresentados movimentos que não tenham títulos vinculados.
          required: false
          type: string
          format: "string case insensitive (M ou B)"
        - name: companyId
          in: query
          description: Código da empresa cadastrada no Sienge
          required: false
          type: integer
        - name: costCentersId
          in: query
          description: Códigos de centro de custo cadastrados no Sienge
          required: false
          type: array
          items:
            type: integer
        - name: onlyDetachedMovement
          in: query
          description: Seleção de movimentos avulsos. Se vazio ou preenchido como 'N', serão retornados todos os movimentos. Se preenchido como 'S', serão retornados apenas movimentos de caixa e banco avulsos.
          required: false
          type: string
          format: "string case insensitive (N ou S)"
        - name: buildingId
          in: query
          description: Código da obra cadastrada no Sienge
          required: false
          type: integer
      produces:
        - application/json
        - file
      responses:
        "200":
          description: Movimentos financeiros encontrados
          schema:
            $ref: "#/definitions/GetResponseBulkDataBankMovement"
        "404":
          description: Movimentos não encontradas
          schema:
            $ref: "#/definitions/ResponseMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMenssage"
  "/bank-movement/by-movements":
    get:
      tags:
        - Bulk-data caixas e bancos
      summary: Retorna movimentos financeiros, caso possua.
      operationId: getBankMovementsByIds
      parameters:
        - name: movementsIds
          in: query
          description: Códigos das movimentações a serem consultadas no Sienge.
          required: true
          type: array
          items:
            type: integer
      produces:
        - application/json
        - file
      responses:
        "200":
          description: Movimentos financeiros encontrados
          schema:
            $ref: "#/definitions/GetResponseBulkDataBankMovement"
        "404":
          description: Movimentos não encontradas
          schema:
            $ref: "#/definitions/ResponseMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMenssage"
definitions:
  GetResponseBulkDataBankMovement:
    type: object
    properties:
      data:
        type: array
        description: Lista de movimentos financeiros
        items:
          $ref: "#/definitions/BankMovement"
  BankMovement:
    type: object
    properties:
      bankMovementId:
        type: integer
        format: int32
        description: "Código do movimento"
      billId:
        type: integer
        format: int32
        description: "Número do título"
      installmentId:
        type: integer
        format: int32
        description: "Número da parcela"
      bankMovementAmount:
        type: number
        format: double
        description: "Valor do movimento"
      documentIdentificationId:
        type: string
        description: "Código do documento"
      documentIdentificationName:
        type: string
        description: "Nome do documento"
      documentIdentificationNumber:
        type: string
        description: "Número do documento"
      bankMovementOriginId:
        type: string
        description: "Código da Origem do Movimento"
      bankMovementHistoricId:
        type: string
        description: "Código do histórico"
      bankMovementHistoricName:
        type: string
        description: "Nome do histórico"
      bankMovementOperationId:
        type: integer
        format: int32
        description: "Código da operação"
      bankMovementOperationName:
        type: string
        description: "Nome da operação"
      bankMovementOperationType:
        type: string
        description: "Tipo da operação"
      bankMovementReconcile:
        type: string
        description: "Conciliado"
      bankMovementDate:
        type: string
        format: "date (Formato ISO 8601 yyyy-MM-dd | Exemplo: 2018-01-01)"
        description: "Data da movimentação"
      billDate:
        type: string
        format: "date (Formato ISO 8601 yyyy-MM-dd | Exemplo: 2018-01-01)"
        description: "Data de competência da parcela vinculada à movimentação"
      accountNumber:
        type: string
        description: "Número da conta corrente"
      companyId:
        type: integer
        format: int32
        description: "Código da empresa"
      companyName:
        type: string
        description: "Nome da empresa"
      groupCompanyId:
        type: integer
        format: int32
        description: "Código da empresa"
      groupCompanyName:
        type: string
        description: "Nome da empresa"
      holdingId:
        type: integer
        format: int32
        description: "Código da holding"
      holdingName:
        type: string
        description: "Nome da holding"
      subsidiaryId:
        type: integer
        format: int32
        description: "Código da holding"
      subsidiaryName:
        type: string
        description: "Nome da holding"
      creditorId:
        type: integer
        description: "Código do credor"
      creditorName:
        type: string
        description: "Nome do credor"
      clientId:
        type: integer
        description: "Código do cliente"
      clientName:
        type: string
        description: "Nome do cliente"
      financialCategories:
        type: array
        items:
          $ref: "#/definitions/FinancialCategory"
        description: Apropriação financeira do movimento
      departamentCosts:
        type: array
        items:
          $ref: "#/definitions/DepartamentCost"
        description: Apropriação de departamento
      buldingCosts:
        type: array
        items:
          $ref: "#/definitions/BuldingCost"
        description: Apropriação de obra

  FinancialCategory:
    type: object
    properties:
      companyId:
        type: integer
        format: int32
        description: "Código da empresa da conta corrente"
      companyName:
        type: string
        description: "Nome da empresa da conta corrente"
      costCenterId:
        type: integer
        format: int32
        description: "Código do centro de custo"
      costCenterName:
        type: string
        description: "Nome do centro de custo"
      financialCategoryId:
        type: string
        description: "Código do plano financeiro"
      financialCategoryName:
        type: string
        description: "Descrição do plano financeiro"
      financialCategoryReducer:
        type: string
        description: "Indica se é plano financeiro redutor"
      financialCategoryType:
        type: string
        description: "Indica plano financeiro de receita ou despesa"
      financialCategoryRate:
        type: number
        format: double
        description: "Percentual de apropriação"
      businessAreaId:
        type: integer
        format: int32
        description: "Código da área de negócio do centro de custo da apropriação"
      businessAreaName:
        type: string
        description: "Nome da área de negócio do centro de custo da apropriação"
      projectId:
        type: integer
        format: int32
        description: "Código do projeto do centro de custo da apropriação"
      projectName:
        type: string
        description: "Nome do projeto do centro de custo da apropriação"
      businessTypeId:
        type: integer
        format: int32
        description: "Código do tipo de negócio do centro de custo da apropriação"
      businessTypeName:
        type: string
        description: "Nome do tipo de negócio do centro de custo da apropriação"
      groupCompanyId:
        type: integer
        format: int32
        description: "Código do grupo de empresa da conta corrente"
      groupCompanyName:
        type: string
        description: "Nome do grupo de empresa da conta corrente"
      holdingId:
        type: integer
        format: int32
        description: "Código da holding da conta corrente"
      holdingName:
        type: string
        description: "Nome da holding da conta corrente"
      subsidiaryId:
        type: integer
        format: int32
        description: "Código da subsidiária da empresa da conta corrente"
      subsidiaryName:
        type: string
        description: "Nome da subsidiária da empresa da conta corrente"
  DepartamentCost:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: "Código do departamento"
      name:
        type: string
        description: "Nome do departamento"
      rate:
        type: number
        format: double
        description: "Percentual de apropriação"

  BuldingCost:
    type: object
    properties:
      buildingId:
        type: integer
        format: int32
        description: "Código da obra"
      name:
        type: string
        description: "Nome da obra"
      buildingUnitId:
        type: integer
        format: int32
        description: "Código da unidade construtiva"
      buildingUnitName:
        type: string
        description: "Nome da unidade construtiva"
      costEstimationSheetId:
        type: string
        description: "Código do item de orçamento"
      costEstimationSheetName:
        type: string
        description: "Nome do item de orçamento"
      rate:
        type: number
        format: double
        description: "Percentual de apropriação"

  ResponseMenssage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para analise do desenvolvedor
        example: Developer description message
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário
        example: Client description message.
