swagger: "2.0"
info:
  description: API de municípios.
  version: 1.0.0
  title: Municípios
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/v1"
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  /cities:
    get:
      tags:
        - Municípios
      summary: Busca uma lista de municípios
      operationId: getAllCities
      parameters:
        - name: limit
          in: query
          description: >-
            Quantidade máxima de resultados da pesquisa a serem retornados.
            Valor default são 100 e o valor máximo permitdo são 200.
          required: false
          type: integer
          default: 100
          maximum: 200
          minimum: 1
          format: int32
        - name: offset
          in: query
          description: >-
            Deslocamento entre o começo da lista e um dado elemento. Valor
            default são 0.
          required: false
          type: integer
          default: 0
          format: int32
        - name: name
          in: query
          description: >-
            Nome do município
          required: false
          type: string
        - name: stateCode
          in: query
          description: >-
            Sigla da unidade federativa do município
          required: false
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Municípios encontrados
          schema:
            $ref: "#/definitions/GetResponseDocument"
        "400":
          description: Requisição mal formada
          schema:
            $ref: "#/definitions/ResponseMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMenssage"
definitions:
  Cities:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Código
      name:
        type: string
        description: Nome da cidade
      state:
        type: object
        description: >-
          Estado
        properties:
          id:
            type: integer
            format: int32
            description: Código
          name:
            type: string
            description: Nome do estado
          code:
            type: string
            description: UF
  GetResponseDocument:
    type: object
    required:
      - links
      - resultSetMetadata
      - results
    properties:
      resultSetMetadata:
        $ref: "#/definitions/ResultSetMetadata"
      results:
        type: array
        description: Lista de municípios retornados como resultado da pesquisa
        items:
          $ref: "#/definitions/Cities"
  ResultSetMetadata:
    type: object
    required:
      - count
      - limit
      - offset
    properties:
      count:
        type: integer
        format: int64
        description: >-
          Total de resultados disponíveis na base de dados como resultado da pesquisa efetuada
      offset:
        type: integer
        format: int32
        description: >-
          Deslocamento entre o começo da lista e um dado elemento. Valor default são 0.
      limit:
        type: integer
        format: int32
        description: >-
          Quantidade máxima de resultados da pesquisa a serem retornados. Valor
          default são 100 e o valor máximo permitdo são 200.
        minimum: 1
        maximum: 200
  ResponseMenssage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para análise do desenvolvedor
        example: Developer description message
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário
        example: Client description message.
