swagger: "2.0"
info:
  description: API de empresas.
  version: 1.0.0
  title: Empresas
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/v1"
tags:
  - name: Companies
    description: API para listagem de empresas
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  "/companies/{companyId}":
    get:
      tags:
        - companies
      summary: Busca a empresa no Sienge
      operationId: getCompany
      parameters:
        - name: companyId
          in: path
          description: Código da empresa a ser apresentado
          required: true
          type: integer
      produces:
        - application/json
      responses:
        "200":
          description: Empresa encontrada
          schema:
            $ref: "#/definitions/Company"
        "404":
          description: Empresa não encontrada
          schema:
            $ref: "#/definitions/ResponseMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMenssage"
  /companies:
    get:
      tags:
        - companies
      summary: Busca uma lista de empresas ordenadas pelo código id
      operationId: getAllCompanies
      parameters:
        - name: limit
          in: query
          description: >-
            Quantidade máxima de resultados da pesquisa a serem retornados.
            Valor default é 100 e o valor máximo permitdo é 200.
          required: false
          type: integer
          default: 100
          maximum: 200
          minimum: 1
          format: int32
        - name: offset
          in: query
          description: >-
            Deslocamento entre o começo da lista e um dado elemento. Valor
            default é 0.
          required: false
          type: integer
          default: 0
          format: int32
      produces:
        - application/json
      responses:
        "200":
          description: Empresa encontrada
          schema:
            $ref: "#/definitions/GetResponseDocument"
        "400":
          description: Requisição mal formada
          schema:
            $ref: "#/definitions/ResponseMenssage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMenssage"
definitions:
  Company:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Código da empresa
      name:
        type: string
        description: Nome da empresa
      tradeName:
        type: string
        description: Nome da fantasia da empresa
      cnpj:
        type: string
        description: CNPJ da empresa
  GetResponseDocument:
    type: object
    required:
      - links
      - resultSetMetadata
      - results
    properties:
      resultSetMetadata:
        $ref: "#/definitions/ResultSetMetadata"
      results:
        type: array
        description: Lista de Empresas retornadas como resultado da pesquisa
        items:
          $ref: "#/definitions/Company"
  ResultSetMetadata:
    type: object
    required:
      - count
      - limit
      - offset
    properties:
      count:
        type: integer
        format: int64
        description: >-
          Total de resultados disponíveis na base de dados como resultado da
          pesquisa efetuada
      offset:
        type: integer
        format: int32
        description: >-
          Deslocamento entre o começo da lista e um dado elemento. Valor default
          é 0.
      limit:
        type: integer
        format: int32
        description: >-
          Quantidade máxima de resultados da pesquisa a serem retornados. Valor
          default é 100 e o valor máximo permitdo é 200.
        minimum: 1
        maximum: 200
  ResponseMenssage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para analise do desenvolvedor
        example: Developer description message
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário
        example: Client description message.
