swagger: "2.0"
info:
  description: API de profissões.
  version: 1.0.0
  title: Profissões
host: api.sienge.com.br
basePath: "/{subdominio-do-cliente}/public/api/v1"
schemes:
  - https
securityDefinitions:
  basicAuth:
    type: basic
    description: HTTP Basic Authentication. Works over `HTTP` and `HTTPS`
security:
  - basicAuth: []
paths:
  /professions:
    get:
      tags:
        - Profissões
      summary: Busca uma lista de profissões
      operationId: getAllProfessions
      parameters:
        - name: limit
          in: query
          description: >-
            Quantidade máxima de resultados da pesquisa a serem retornados.
            Valor default é 100 e o valor máximo permitdo é 200.
          required: false
          type: integer
          default: 100
          maximum: 200
          minimum: 1
          format: int32
        - name: offset
          in: query
          description: >-
            Deslocamento entre o começo da lista e um dado elemento. Valor
            default é 0.
          required: false
          type: integer
          default: 0
          format: int32
        - name: name
          in: query
          description: >-
            Filtro por nome de profissão.
          required: false
          type: string
      produces:
        - application/json
      responses:
        "200":
          description: Profissões encontradas
          schema:
            $ref: "#/definitions/GetResponseDocument"
        "400":
          description: Requisição mal formada
          schema:
            $ref: "#/definitions/ResponseMessage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMessage"
    post:
      tags:
        - Profissões
      summary: Persiste uma lista de profissões.
      operationId: insertProfessions
      parameters:
        - in: body
          name: body
          description: Lista de profissões
          required: true
          schema:
            $ref: "#/definitions/ProfessionsInsert"
      responses:
        "201":
          description: Contrato criado
        "400":
          description: Requisição mal formada
          schema:
            $ref: "#/definitions/ResponseMessage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMessage"

  "/professions/{id}":
    get:
      tags:
        - Profissões
      summary: Busca uma profissão.
      operationId: getProfession
      parameters:
        - name: id
          in: path
          description: Id da profissão.
          required: true
          type: integer
          format: int32
      produces:
        - application/json
      responses:
        "200":
          description: Profissão encontrada.
          schema:
            $ref: "#/definitions/GetResponseDocument"
        "400":
          description: Requisição mal formada
          schema:
            $ref: "#/definitions/ResponseMessage"
        "500":
          description: Erro interno no servidor
          schema:
            $ref: "#/definitions/ResponseMessage"
definitions:
  ProfessionsInsert:
    type: array
    description: Lista de profissões para serem persistidas
    items:
      type: string
      example: "Engenheiro(a)"
  Profession:
    type: object
    properties:
      id:
        type: integer
        format: int32
        description: Código da profissão
      name:
        type: string
        description: Nome da profissão
  GetResponseDocument:
    type: object
    required:
      - links
      - resultSetMetadata
      - results
    properties:
      resultSetMetadata:
        $ref: "#/definitions/ResultSetMetadata"
      results:
        type: array
        description: Lista de profissões retornadas como resultado da pesquisa
        items:
          $ref: "#/definitions/Profession"
  ResultSetMetadata:
    type: object
    required:
      - count
      - limit
      - offset
    properties:
      count:
        type: integer
        format: int64
        description: >-
          Total de resultados disponíveis na base de dados como resultado da pesquisa efetuada
      offset:
        type: integer
        format: int32
        description: >-
          Deslocamento entre o começo da lista e um dado elemento. Valor default é 0.
      limit:
        type: integer
        format: int32
        description: >-
          Quantidade máxima de resultados da pesquisa a serem retornados. Valor
          default é 100 e o valor máximo permitdo é 200.
        minimum: 1
        maximum: 200
  ResponseMessage:
    type: object
    properties:
      status:
        type: integer
        description: Status Http
      developerMessage:
        type: string
        description: Mensagem de resposta para análise do desenvolvedor
        example: Developer description message
      clientMessage:
        type: string
        description: Mensagem de resposta para o usuário
        example: Client description message
