// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/messages/mark-read.ts";
import * as $$$$$$$$$1 from "./actions/messages/send-interactive.ts";
import * as $$$$$$$$$2 from "./actions/messages/send-media.ts";
import * as $$$$$$$$$3 from "./actions/messages/send-template.ts";
import * as $$$$$$$$$4 from "./actions/messages/send-text.ts";
import * as $$$$$$$$$5 from "./actions/setup-webhook.ts";
import * as $$$$$$$$$6 from "./actions/setup.ts";
import * as $$$$$$$$$7 from "./actions/webhook.ts";
import * as $$$0 from "./loaders/check-connection.ts";

const manifest = {
  "loaders": {
    "whatsapp/loaders/check-connection.ts": $$$0,
  },
  "actions": {
    "whatsapp/actions/messages/mark-read.ts": $$$$$$$$$0,
    "whatsapp/actions/messages/send-interactive.ts": $$$$$$$$$1,
    "whatsapp/actions/messages/send-media.ts": $$$$$$$$$2,
    "whatsapp/actions/messages/send-template.ts": $$$$$$$$$3,
    "whatsapp/actions/messages/send-text.ts": $$$$$$$$$4,
    "whatsapp/actions/setup-webhook.ts": $$$$$$$$$5,
    "whatsapp/actions/setup.ts": $$$$$$$$$6,
    "whatsapp/actions/webhook.ts": $$$$$$$$$7,
  },
  "name": "whatsapp",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
