// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/createRow.ts";
import * as $$$0 from "./loaders/getCount.ts";
import * as $$$1 from "./loaders/getData.ts";
import * as $$$2 from "./loaders/getDocumentName.ts";
import * as $$$3 from "./loaders/getKeys.ts";

const manifest = {
  "loaders": {
    "sheet-db-sienge/loaders/getCount.ts": $$$0,
    "sheet-db-sienge/loaders/getData.ts": $$$1,
    "sheet-db-sienge/loaders/getDocumentName.ts": $$$2,
    "sheet-db-sienge/loaders/getKeys.ts": $$$3,
  },
  "actions": {
    "sheet-db-sienge/actions/createRow.ts": $$$$$$$$$0,
  },
  "name": "sheet-db-sienge",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
