// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/admin.ts";
import * as $$$$$$$$$$$1 from "./apps/handlebars.ts";
import * as $$$$$$$$$$$2 from "./apps/verified-reviews.ts";
import * as $$$$$$$$$$$3 from "./apps/workflows.ts";

const manifest = {
  "apps": {
    "decohub/apps/admin.ts": $$$$$$$$$$$0,
    "decohub/apps/handlebars.ts": $$$$$$$$$$$1,
    "decohub/apps/verified-reviews.ts": $$$$$$$$$$$2,
    "decohub/apps/workflows.ts": $$$$$$$$$$$3,
  },
  "name": "decohub",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
