// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/vtex.ts";
import * as $$$$$$$$$$$1 from "./apps/wake.ts";
import * as $$$$$$$$$$$2 from "./apps/shopify.ts";
import * as $$$$$$$$$$$3 from "./apps/workflows.ts";
import * as $$$$$$$$$$$4 from "./apps/linx.ts";
import * as $$$$$$$$$$$5 from "./apps/ai-assistants.ts";
import * as $$$$$$$$$$$6 from "./apps/verified-reviews.ts";
import * as $$$$$$$$$$$7 from "./apps/algolia.ts";
import * as $$$$$$$$$$$8 from "./apps/nuvemshop.ts";
import * as $$$$$$$$$$$9 from "./apps/brand-assistant.ts";
import * as $$$$$$$$$$$10 from "./apps/typesense.ts";
import * as $$$$$$$$$$$11 from "./apps/analytics.ts";
import * as $$$$$$$$$$$12 from "./apps/vnda.ts";
import * as $$$$$$$$$$$13 from "./apps/implementation.ts";
import * as $$$$$$$$$$$14 from "./apps/weather.ts";
import * as $$$$$$$$$$$15 from "./apps/admin.ts";
import * as $$$$$$$$$$$16 from "./apps/sourei.ts";
import * as $$$$$$$$$$$17 from "./apps/handlebars.ts";
import * as $$$$$$$$$$$18 from "./apps/power-reviews.ts";

const manifest = {
  "apps": {
    "decohub/apps/admin.ts": $$$$$$$$$$$15,
    "decohub/apps/ai-assistants.ts": $$$$$$$$$$$5,
    "decohub/apps/algolia.ts": $$$$$$$$$$$7,
    "decohub/apps/analytics.ts": $$$$$$$$$$$11,
    "decohub/apps/brand-assistant.ts": $$$$$$$$$$$9,
    "decohub/apps/handlebars.ts": $$$$$$$$$$$17,
    "decohub/apps/implementation.ts": $$$$$$$$$$$13,
    "decohub/apps/linx.ts": $$$$$$$$$$$4,
    "decohub/apps/nuvemshop.ts": $$$$$$$$$$$8,
    "decohub/apps/power-reviews.ts": $$$$$$$$$$$18,
    "decohub/apps/shopify.ts": $$$$$$$$$$$2,
    "decohub/apps/sourei.ts": $$$$$$$$$$$16,
    "decohub/apps/typesense.ts": $$$$$$$$$$$10,
    "decohub/apps/verified-reviews.ts": $$$$$$$$$$$6,
    "decohub/apps/vnda.ts": $$$$$$$$$$$12,
    "decohub/apps/vtex.ts": $$$$$$$$$$$0,
    "decohub/apps/wake.ts": $$$$$$$$$$$1,
    "decohub/apps/weather.ts": $$$$$$$$$$$14,
    "decohub/apps/workflows.ts": $$$$$$$$$$$3,
  },
  "name": "decohub",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
