// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/daily-notes/append.ts";
import * as $$$$$$$$$1 from "./actions/links/create.ts";
import * as $$$$$$$$$2 from "./actions/notes/create.ts";
import * as $$$0 from "./loaders/graphs.ts";
import * as $$$1 from "./loaders/graphs/books.ts";
import * as $$$2 from "./loaders/graphs/links.ts";
import * as $$$3 from "./loaders/me.ts";

const manifest = {
  "loaders": {
    "reflect/loaders/graphs.ts": $$$0,
    "reflect/loaders/graphs/books.ts": $$$1,
    "reflect/loaders/graphs/links.ts": $$$2,
    "reflect/loaders/me.ts": $$$3,
  },
  "actions": {
    "reflect/actions/daily-notes/append.ts": $$$$$$$$$0,
    "reflect/actions/links/create.ts": $$$$$$$$$1,
    "reflect/actions/notes/create.ts": $$$$$$$$$2,
  },
  "name": "reflect",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
