// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/channels/update.ts";
import * as $$$$$$$$$1 from "./actions/channels/updateDefaults.ts";
import * as $$$$$$$$$2 from "./actions/channels/updateSections.ts";
import * as $$$$$$$$$3 from "./actions/comments/create.ts";
import * as $$$$$$$$$4 from "./actions/comments/pin.ts";
import * as $$$$$$$$$5 from "./actions/comments/rate.ts";
import * as $$$$$$$$$6 from "./actions/comments/reply.ts";
import * as $$$$$$$$$7 from "./actions/livestreams/bind.ts";
import * as $$$$$$$$$8 from "./actions/livestreams/create.ts";
import * as $$$$$$$$$9 from "./actions/livestreams/createStream.ts";
import * as $$$$$$$$$10 from "./actions/livestreams/delete.ts";
import * as $$$$$$$$$11 from "./actions/livestreams/transition.ts";
import * as $$$$$$$$$12 from "./actions/livestreams/update.ts";
import * as $$$$$$$$$13 from "./actions/livestreams/updateThumbnail.ts";
import * as $$$$$$$$$14 from "./actions/oauth/callback.ts";
import * as $$$$$$$$$15 from "./actions/videos/delete.ts";
import * as $$$$$$$$$16 from "./actions/videos/update.ts";
import * as $$$$$$$$$17 from "./actions/videos/updateCategory.ts";
import * as $$$$$$$$$18 from "./actions/videos/updateThumbnail.ts";
import * as $$$0 from "./loaders/analytics/channelStats.ts";
import * as $$$1 from "./loaders/analytics/videoStats.ts";
import * as $$$2 from "./loaders/channels/get.ts";
import * as $$$3 from "./loaders/comments/list.ts";
import * as $$$4 from "./loaders/comments/threads.ts";
import * as $$$5 from "./loaders/livestreams/list.ts";
import * as $$$6 from "./loaders/livestreams/streams.ts";
import * as $$$7 from "./loaders/oauth/start.ts";
import * as $$$8 from "./loaders/videos/captions.ts";
import * as $$$9 from "./loaders/videos/categories.ts";
import * as $$$10 from "./loaders/videos/channelVideos.ts";
import * as $$$11 from "./loaders/videos/details.ts";
import * as $$$12 from "./loaders/videos/list.ts";
import * as $$$13 from "./loaders/videos/search.ts";

const manifest = {
  "loaders": {
    "youtube/loaders/analytics/channelStats.ts": $$$0,
    "youtube/loaders/analytics/videoStats.ts": $$$1,
    "youtube/loaders/channels/get.ts": $$$2,
    "youtube/loaders/comments/list.ts": $$$3,
    "youtube/loaders/comments/threads.ts": $$$4,
    "youtube/loaders/livestreams/list.ts": $$$5,
    "youtube/loaders/livestreams/streams.ts": $$$6,
    "youtube/loaders/oauth/start.ts": $$$7,
    "youtube/loaders/videos/captions.ts": $$$8,
    "youtube/loaders/videos/categories.ts": $$$9,
    "youtube/loaders/videos/channelVideos.ts": $$$10,
    "youtube/loaders/videos/details.ts": $$$11,
    "youtube/loaders/videos/list.ts": $$$12,
    "youtube/loaders/videos/search.ts": $$$13,
  },
  "actions": {
    "youtube/actions/channels/update.ts": $$$$$$$$$0,
    "youtube/actions/channels/updateDefaults.ts": $$$$$$$$$1,
    "youtube/actions/channels/updateSections.ts": $$$$$$$$$2,
    "youtube/actions/comments/create.ts": $$$$$$$$$3,
    "youtube/actions/comments/pin.ts": $$$$$$$$$4,
    "youtube/actions/comments/rate.ts": $$$$$$$$$5,
    "youtube/actions/comments/reply.ts": $$$$$$$$$6,
    "youtube/actions/livestreams/bind.ts": $$$$$$$$$7,
    "youtube/actions/livestreams/create.ts": $$$$$$$$$8,
    "youtube/actions/livestreams/createStream.ts": $$$$$$$$$9,
    "youtube/actions/livestreams/delete.ts": $$$$$$$$$10,
    "youtube/actions/livestreams/transition.ts": $$$$$$$$$11,
    "youtube/actions/livestreams/update.ts": $$$$$$$$$12,
    "youtube/actions/livestreams/updateThumbnail.ts": $$$$$$$$$13,
    "youtube/actions/oauth/callback.ts": $$$$$$$$$14,
    "youtube/actions/videos/delete.ts": $$$$$$$$$15,
    "youtube/actions/videos/update.ts": $$$$$$$$$16,
    "youtube/actions/videos/updateCategory.ts": $$$$$$$$$17,
    "youtube/actions/videos/updateThumbnail.ts": $$$$$$$$$18,
  },
  "name": "youtube",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
