// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/myAction.ts";
import * as $$$0 from "./loaders/myLoader.ts";

const manifest = {
  "loaders": {
    "app-template/loaders/myLoader.ts": $$$0,
  },
  "actions": {
    "app-template/actions/myAction.ts": $$$$$$$$$0,
  },
  "name": "app-template",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
