// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$0 from "./actions/imageToVideo.ts";
import * as $$$$$$$$$$0 from "./actions/textToVideo.ts";
import * as $$$$$$$$$$1 from "./actions/referenceToVideo.ts";
import * as $$$$$$$$$$2 from "./actions/startEndToVideo.ts";
import * as $$$0 from "./loaders/getGenerationResult.ts";
import * as $$$$0 from "./loaders/resultPreview.ts";
const manifest = {
  "actions": {
    "vidu/actions/imageToVideo.ts": $$$$$$$$$0,
    "vidu/actions/textToVideo.ts": $$$$$$$$$$0,
    "vidu/actions/referenceToVideo.ts": $$$$$$$$$$1,
    "vidu/actions/startEndToVideo.ts": $$$$$$$$$$2,
  },
  "loaders": {
    "vidu/loaders/getGenerationResult.ts": $$$0,
    "vidu/loaders/resultPreview.ts": $$$$0,
  },
  "name": "vidu",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
